### ISSUE TITLE
Error Saving Content 8.8.0 bug?

### ISSUE THREAD

**Issue by joshgk00** [2sic/2sxc#1133]
I've got version 8.8.0 installed on DNN 9. At one point everything was working fine. I recently went back to the site to make some changes and now I'm getting an error when trying to save content and save changes to the content type fields. The screenshot below shows the error. 
https://www.screencast.com/t/vCsAzZ92M

I'm also seeing this in the event log,
AbsoluteURL:/desktopmodules/2sxc/api/eav/entities/savemany
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:b1e249a5-6fe0-4870-a0a5-08681f941043
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:CrfYapVaqiY50M0PTHbIYCCUze8=
Message:The type initializer for 'ExtentPlaceholderCreator' threw an exception.
StackTrace:
at System.Data.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.GetPropagatorResultForPrimitiveType(PrimitiveType primitiveType, PropagatorResult& result) at System.Data.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.Visit(EdmMember node) at System.Data.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.CreateEntitySetPlaceholder(EntitySet entitySet) at System.Data.Mapping.Update.Internal.Propagator.Visit(DbScanExpression node) at System.Data.Mapping.Update.Internal.Propagator.Visit(DbProjectExpression node) at System.Data.Mapping.Update.Internal.UpdateTranslator.d__0.MoveNext() at System.Linq.Enumerable.d__71`1.MoveNext() at System.Data.Mapping.Update.Internal.UpdateCommandOrderer..ctor(IEnumerable`1 commands, UpdateTranslator translator) at System.Data.Mapping.Update.Internal.UpdateTranslator.Update(IEntityStateManager stateManager, IEntityAdapter adapter) at System.Data.Objects.ObjectContext.SaveChanges(SaveOptions options) at ToSic.Eav.BLL.EavDataController.SaveChanges(SaveOptions options, OriginalSaveChangesEvent baseEvent) in C:\Projects\eav-server\ToSic.Eav\BLL\EavDataController.cs:line 233 at ToSic.Eav.EavContext.SaveChanges(SaveOptions options) in C:\Projects\eav-server\ToSic.Eav.Persistence.EF4\Persistence\EavContext.cs:line 27 at ToSic.Eav.BLL.Parts.DbEntity.UpdateEntity(Int32 repositoryId, IDictionary newValues, Boolean autoSave, ICollection`1 dimensionIds, Boolean masterRecord, List`1 updateLog, Boolean preserveUndefinedValues, Boolean isPublished, Boolean forceNoBranch) in C:\Projects\eav-server\ToSic.Eav\BLL\Parts\DbEntity.cs:line 304 at ToSic.Eav.Import.Import.PersistOneImportEntity(ImportEntity importEntity) in C:\Projects\eav-server\ToSic.Eav\ImportExport\Import.cs:line 342 at ToSic.Eav.Import.Import.RunImport(IEnumerable`1 newAttributeSets, IEnumerable`1 newEntities) in C:\Projects\eav-server\ToSic.Eav\ImportExport\Import.cs:line 126 at ToSic.Eav.WebApi.EntitiesController.SaveMany(Int32 appId, List`1 items) in C:\Projects\eav-server\ToSic.Eav.WebApi\EntitiesController.cs:line 210 at ToSic.SexyContent.EAVExtensions.EavApiProxies.EntitiesController.SaveMany(Int32 appId, List`1 items) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\WebApi\EavApiProxies\EntitiesController.cs:line 114 at lambda_method(Closure , Object , Object[] ) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() at System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext()
InnerMessage:Exception has been thrown by the target of an invocation.
InnerStackTrace:
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Data.SqlClient.SqlSpatialServices.GeometryFromText(String geometryText) at System.Data.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.InitializeTypeDefaultMap() at System.Data.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator..cctor()
Source:System.Data.Entity

**Comment by iJungleboy** [comment]
Short info: never heard of this before, sounds like something internal from the Entity-Framework to the DB, so most likely a installation specific issue. To 95% not really 2sxc-related. Maybe a .net framework issue or DB connection. 

At the moment we couldn't do anything about this. Please find out more about it (did the server just have an update / did you reconfigure the iis, does this happen regularly, what about upgrading to 2sxc 8.11)...

**Comment by iJungleboy** [comment]
So far I have two people reporting this - but with different versions of 2sxc. 

I'll close this and ask you to continue on #1136 - but please post your not their too and give me more info regarding what version of DNN/Evoq you're using, and if there is anything more detailed you can tell me.
