### ISSUE TITLE
ExtendPlaceholderCreator error when trying to save in 2sxc

### ISSUE THREAD

**Issue by dnastone** [2sic/2sxc#1136]
Summary of Issue ATM by @iJungleboy

- There seems to be cases where the Entity-Framework fails to save in 2sxc - complaining about `ExtentPlaceholderCreator`
- so far 2 people have reported it, @dnastone and @joshgk00
- It seems to happen on DNN 9.0.2 (so it could easily be a DNN-issue), it's unclear if other DNN versions are affected
- It seems to happen on 2sxc 8.11, but @joshgk00 also reported it on 2sxc 8.8
- in the case of @dnastone the error already occured during installation, so it could be a follow-up error

Original Message from @dnastone 
hello,

i get error messages like this window all the time:

![21-03-_2017_11-35-38](https://cloud.githubusercontent.com/assets/11678580/24143858/69f7c930-0e2b-11e7-998e-9c272438f0f1.png)

thanks for help

**Comment by iJungleboy** [comment]
Please provide more information: Versions of DNN/2sxc, etc.

**Comment by dnastone** [comment]
dnn 9.0.2 and 2six 8.11.0
everything works fine and then this error happens i have no idea why. it happend every time. changing content, creating content and i can't change into the edit mode from the cms when this happen.

i had the same problem after upgrading 2sexy 8.4.8 to 8.11.0 the script for complete ugrade doesn't work. there i had dnn 7.4.2

i posted this error from the admin event log there:

http://stackoverflow.com/questions/42907550/error-after-installing-to-the-newest-version

**Comment by dnastone** [comment]
at the dnn 9.0.2 portal i found a lot of error messages at the event log here are some:

`AbsoluteURL:/en/API/2sxc/view/module/savetemplateid
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:fef21a4b-801c-4400-b3a7-8f6fa2dcd31a
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:nV4KTFIF2hMTAbq2WgfbVBP/4lI=
Message:The type initializer for 'ExtentPlaceholderCreator' threw an exception.
StackTrace:
at System.Data.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.GetPropagatorResultForPrimitiveType(PrimitiveType primitiveType, PropagatorResult& result) at System.Data.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.Visit(EdmMember node) at System.Data.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.CreateEntitySetPlaceholder(EntitySet entitySet) at System.Data.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.CreatePlaceholder(EntitySetBase extent, UpdateTranslator parent) at System.Data.Mapping.Update.Internal.Propagator.Visit(DbScanExpression node) at System.Data.Common.CommandTrees.DbScanExpression.Accept[TResultType](DbExpressionVisitor`1 visitor) at System.Data.Mapping.Update.Internal.UpdateExpressionVisitor`1.Visit(DbExpression expression) at System.Data.Mapping.Update.Internal.Propagator.Visit(DbProjectExpression node) at System.Data.Common.CommandTrees.DbProjectExpression.Accept[TResultType](DbExpressionVisitor`1 visitor) at System.Data.Mapping.Update.Internal.Propagator.Propagate(UpdateTranslator parent, EntitySet table, DbQueryCommandTree umView) at System.Data.Mapping.Update.Internal.UpdateTranslator.d__44.MoveNext() at System.Linq.Enumerable.d__58`1.MoveNext() at System.Data.Mapping.Update.Internal.UpdateCommandOrderer..ctor(IEnumerable`1 commands, UpdateTranslator translator) at System.Data.Mapping.Update.Internal.UpdateTranslator.ProduceCommands() at System.Data.Mapping.Update.Internal.UpdateTranslator.Update(IEntityStateManager stateManager, IEntityAdapter adapter) at System.Data.EntityClient.EntityAdapter.Update(IEntityStateManager entityCache) at System.Data.Objects.ObjectContext.SaveChanges(SaveOptions options) at ToSic.Eav.BLL.EavDataController.SaveChanges(SaveOptions options, OriginalSaveChangesEvent baseEvent) in C:\Projects\eav-server\ToSic.Eav\BLL\EavDataController.cs:line 233 at ToSic.Eav.EavContext.SaveChanges(SaveOptions options) in C:\Projects\eav-server\ToSic.Eav.Persistence.EF4\Persistence\EavContext.cs:line 27 at System.Data.Objects.ObjectContext.SaveChanges() at ToSic.Eav.BLL.Parts.DbEntity.AddEntity(AttributeSet attributeSet, Int32 attributeSetId, IDictionary values, Nullable`1 configurationSet, Nullable`1 keyNumber, Nullable`1 keyGuid, String keyString, Int32 assignmentObjectTypeId, Int32 sortOrder, Nullable`1 entityGuid, ICollection`1 dimensionIds, List`1 updateLog, Boolean isPublished, Nullable`1 publishedEntityId) in C:\Projects\eav-server\ToSic.Eav\BLL\Parts\DbEntity.cs:line 178 at ToSic.Eav.BLL.Parts.DbEntity.AddEntity(Int32 attributeSetId, IDictionary values, Nullable`1 configurationSet, Nullable`1 key, Int32 assignmentObjectTypeId, Int32 sortOrder, Nullable`1 entityGuid, ICollection`1 dimensionIds, Boolean isPublished) in C:\Projects\eav-server\ToSic.Eav\BLL\Parts\DbEntity.cs:line 116 at ToSic.SexyContent.ContentGroupManager.CreateNewContentGroup(Nullable`1 templateId) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentGroupManager.cs:line 68 at ToSic.SexyContent.ContentGroupManager.UpdateOrCreateContentGroup(ContentGroup contentGroup, Int32 templateId) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentGroupManager.cs:line 106 at ToSic.SexyContent.ContentBlocks.ContentGroupReferenceManagerBase.SaveTemplateId(Int32 templateId, Boolean forceCreateContentGroup, Nullable`1 newTemplateChooserState) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentBlocks\ContentGroupReferenceManagerBase.cs:line 54 at lambda_method(Closure , Object , Object[] ) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext()
InnerMessage:Exception has been thrown by the target of an invocation.
InnerStackTrace:
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Data.SqlClient.SqlSpatialServices.GeometryFromText(String geometryText) at System.Data.Spatial.DbGeometry.FromText(String wellKnownText) at System.Data.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator.InitializeTypeDefaultMap() at System.Data.Mapping.Update.Internal.Propagator.ExtentPlaceholderCreator..cctor()
Source:System.Data.Entity
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
<b>Server-Name</b>: rs216170`

**Comment by dnastone** [comment]
`AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:badb0a85-abb6-4d46-add2-00f735f02fec
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:m/C7XbBDlXMV5nHzoBehBsaVrnE=
Message:Object reference not set to an instance of an object.
StackTrace:
at ToSic.SexyContent.View.InitModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 160 at ToSic.SexyContent.View.get_ModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 111
InnerMessage:
InnerStackTrace:
Source:ToSic.SexyContent
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
<b>Server-Name</b>: rs216170`

**Comment by dnastone** [comment]
a other bug from 2sexy. with dnn 9 the drag and drop function of the module doesn't work. i can't move the module from pane to a other pane.

**Comment by iJungleboy** [comment]
It's important to keep each issue in an own thread, so I put the drag-drop issue here: #1137

**Comment by dnastone** [comment]
hello,
did you found something for the ExtentPlaceholderCreator error?

**Comment by iJungleboy** [comment]
@dnastone haven't been able to look into it yet, and not a top priority as you're the only one reporting it. ATM I still believe that it's something with your setup, related to your iis / sql. We can't prioritize it ATM.

**Comment by joshgk00** [comment]
So I'm thinking that this issue might be environment related, but still not sure what's causing it. When I originally reported the issue, I believe the site was running on DNN 9.0.0. Upgrading to DNN 9.0,2 didn't fix it and upgrading 2sxc from 8.8 to 8.11 didn't fix the issue either. 

The server environment that the site was running on was Windows 2008 R2 and IIS 7.5, SQL 2008, .NET 4.5. This is the development server environment that I was using. I took a backup of the site and moved it over to the production server which is Windows Server 2012 R2, IIS 8.0, SQL 2016 Express, .NET 4.6, 

So it may be an issue with one or more of the older technologies like IIS or SQL or .NET. I have other sites using DNN 9.0.2 on the newer environment and 2sxc seems to work fine. Maybe @dnastone your current environment might be similar to my development environment?

**Comment by dnastone** [comment]
one server where the error happens are a 2012 R2 server + SQL 2012 and .net framework 4.6.1.

lokal where the error doesn't happen i'm using sql 2016.

on the other webhosting provider i don't know the server edition, but i think it's 2012. the sql server are 2012. 

maybe the error could depend to the sql version. with 2016 it works.

**Comment by iJungleboy** [comment]
To all: We have a sponsor who asked us to look into it, and it looks like it's caused by a third party component with some unofficial DLLs breaking the Entity Framework functionality. We probably have a solution in a few hours.

**Comment by raphael-m** [comment]
Cause for the issue was - in the case we solved - a wrong version of *Microsoft.SqlServer.Types.dll* being used. 2sxc uses an older Entity Framework version which does not work well with *Microsoft.SqlServer.Types* version 13.x. Open your application's web.config to verify if an [assembly binding](https://msdn.microsoft.com/en-us/library/0ash1ksb(v=vs.110).aspx) entry exists for that assembly.
 
In our case, the binding and the local *Microsoft.SqlServer.Types.dll* has been created by a module called *Evotiva-DNNBackup*. If you have that installed:
* If you don't use the backup module, uninstall it (this should automatically remove both the web.config entry and the dll file).
* Try to use a different version of the dll by changing the assembly binding to another version (we have not tried this) or remove/comment the assembly binding in web.config which allows 2sxc to use the correct version.

**Comment by horacioj** [comment]
>some unofficial DLLs breaking the Entity Framework functionality. 

FYI, it is not " unofficial" at all. It is the official Microsoft's DAC package, using their (Microsoft's)  very own and official Microsoft.SqlServer.Types.dll. The package is from 10/23/2016

DNNBackup includes DAC since version 8.0
Version 7.8.3 is the latest one not using it, and it is available at http://www.evotiva.com/Downloads
Users can use 7.8.3 until 2sxc is fixed to use a more recent official versions of Microsoft's DLLs.

Best regards,
Horacio

**Comment by iJungleboy** [comment]
@horacioj thanks for that feedback. we had checked nuget and didn't find this dll version, so we thought it was inofficial. Thanks for the update.

**Comment by horacioj** [comment]
The very own Microsoft's DLL hell...  :)
