### ISSUE TITLE
Improve Exception-Message if CultureDimension-QueryString is missing

### ISSUE THREAD

**Issue by BeniGemperle** [2sic/2sxc#127]
Current Message is:
DotNetNuke.Services.Exceptions.PageLoadException: Specified argument was out of the range of valid values.
Parameter name: index ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: index
   at System.Web.UI.ControlCollection.get_Item(Int32 index)
   at ToSic.SexyContent.EditContentGroup.Page_PreRender(Object sender, EventArgs e) in c:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\EditContentGroup.ascx.cs:line 232
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   --- End of inner exception stack trace ---

Should be handled in EditContentGroup.Page_Load() at line 217 or later

**Comment by iJungleboy** [comment]
So is this already resolved?

**Comment by iJungleboy** [comment]
will close for now, assume the error is not relevant or doesn't happen any more.
