### ISSUE TITLE
Error on saving any content entity

### ISSUE THREAD

**Issue by TwoHeadsBrewing** [2sic/2sxc#1293]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI

**Current behavior**
After upgrading to 2SXC 9.5 from 8.12, I can no longer edit any content items.  I get an error that says,
"Had an error talking to server (status 400).
Message: Bad Request
Detail: Error getting List of Stream
Stream Name: Default
DataSource Name:  EntityTypeFilter"

**Expected behavior**
Edit item, save and successfully close.

**Minimal reproduction of the problem with instructions**
Edit any item and then click the "Save" button.

**What is the motivation / use case for changing the behavior?**
N/A

**Please tell us about your environment:**
Amazon AWS EC2 instance running Windows Server 2012 R2

* **2sxc version(s):** 9.5
* **Browser:** all
* **DNN:** Evoq 8.4.1
* **Language:** All

Error information from the log:
AbsoluteURL:/desktopmodules/2sxc/api/eav/entities/savemany
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:05ea58f3-37e8-4abc-816e-bbf4da180b8c
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:FkYYsBX5J2/Eeuph6B78Wg==
Message:Error getting List of Stream. Stream Name: Default DataSource Name: EntityTypeFilter
StackTrace:
   at ToSic.Eav.DataSources.DataStream.get_LightList() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 158
   at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 83
   at ToSic.SexyContent.ContentGroupManager.GetContentGroup(Guid contentGroupGuid) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentGroupManager.cs:line 46
   at ToSic.SexyContent.ContentGroupManager.GetContentGroupOrGeneratePreview(Guid groupGuid, Guid previewTemplateGuid) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentGroupManager.cs:line 141
   at ToSic.SexyContent.ContentGroupManager.GetContentGroupForModule(Int32 moduleId, Int32 tabId) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentGroupManager.cs:line 135
   at ToSic.SexyContent.ContentBlocks.ModuleContentBlock..ctor(ModuleInfo moduleInfo, IEnumerable`1 overrideParams) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentBlocks\ModuleContentBlock.cs:line 58
   at ToSic.SexyContent.WebApi.Helpers.GetSxcOfApiRequest(HttpRequestMessage request, Boolean allowNoContextFound) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Sxc WebApi\Helpers.cs:line 45
   at ToSic.SexyContent.WebApi.SxcApiController.get_AppAndDataHelpers() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Sxc WebApi\SxcApiController.cs:line 24
   at ToSic.SexyContent.WebApi.EavApiProxies.EntitiesController.SaveMany(Int32 appId, List`1 items, Boolean partOfPage) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Sxc WebApi\EavApiProxies\EntitiesController.cs:line 118
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext()
InnerMessage:Error getting List of Stream. Stream Name: Default DataSource Name: PublishingFilter
InnerStackTrace:
   at ToSic.Eav.DataSources.DataStream.get_LightList() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 158
   at ToSic.Eav.DataSources.EntityTypeFilter.GetList() in C:\Projects\eav-server\ToSic.Eav.DataSources\EntityTypeFilter.cs:line 59
   at ToSic.Eav.DataSources.DataStream.get_LightList() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 136
Source:ToSic.Eav.DataSources
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: WIN-VGD4FFTN042

**Comment by TwoHeadsBrewing** [comment]
Also, I just noticed that on any content edit form there is only the options to "Hide this item" or "Hide changes as draft".  There is no option to "Show this item" as there was prior to the upgrade to 9.5.

**Comment by iJungleboy** [comment]
Are you using dnn or evoq? because 9.5 has a new feature which kicks-in when the page has a publish-workflow...

**Comment by TwoHeadsBrewing** [comment]
I'm using Evoq 8.4.1

**Comment by iJungleboy** [comment]
2sxc 9.5 "respects" Evoq page workflow settings and thereby forces the user to draft-save, till they publish  the page. Evoq is notified (by 2sxc) of changes, so the page will then offer a publish button. 

Is this a problem, or simply a surprise?

**Comment by TwoHeadsBrewing** [comment]
The problem is that the item is never saved and an error is thrown.  The user cannot change anything.

**Comment by iJungleboy** [comment]
We may already have a solution, but I'm not sure. I changed some minor details which apply to this, but we haven't released 9.5.1 yet as we need one more feature. I'll give you a pre-release here, could you give it a quick try?
[2sic_2SexyContent_09.05.01_Install.zip](https://github.com/2sic/2sxc/files/1304130/2sic_2SexyContent_09.05.01_Install.zip)

**Comment by TwoHeadsBrewing** [comment]
I applied this update, and it did not solve the issue.  When I look into the debug window, each of these data entities "IsPublished" is set to "false".  However, in the database this value is "true".

**Comment by iJungleboy** [comment]
The DB state is normal - as the draft-item technically has another number in the DB. It's just provided internally as the same id, one draft, the other published.

**Comment by TwoHeadsBrewing** [comment]
What do you recommend as a solution?  Is it possible to roll back to a previous version of 2sxc?

**Comment by iJungleboy** [comment]
Rollback is very easy. Just go to the extensions and modify the version number of content & app to be the version you want, then re-install that version.

**Comment by iJungleboy** [comment]
Since I cannot just reproduce the issue - do you have any more idea what could be the cause?

**Comment by TwoHeadsBrewing** [comment]
Is there any prior version that would be a good choice?  And are there any incompatible versions since version 8.12 I should avoid?

**Comment by iJungleboy** [comment]
From our point of view 9.5 should be the most stable of all 9, but we have build the solution that you should also be able to roll back to 8.12 without problems. So of course it would be better if we could solve the problem :)

As I'm sitting at the PC right now, could I maybe have a brief admin/host access to the system and have a look? you could send it to info 2sxc org

**Comment by TwoHeadsBrewing** [comment]
I'm attempting a rollback to 8.12 as a quick fix, but if that doesn't work I will forward you login information on our testing server.  Thanks for you help thus far!

**Comment by TwoHeadsBrewing** [comment]
Just an FYI, rolling back to Pre-Release 3 of 9.5 and then back to 8.12 did not solve the problem.  The error is still thrown and there is no option to "Show this item" by the save button on any data entity.

**Comment by iJungleboy** [comment]
this is strange. could you verify that you rolled back? check the versions of the DLLs and also in the admin-dialogs, mouse-over the pi-symbol in the corner - it should show you the version it's running.

**Comment by TwoHeadsBrewing** [comment]
It is still showing version 9.5.1.  However, I did re-install the older version.  I re-set the version to 8.0.0 and then performed an install.

**Comment by TwoHeadsBrewing** [comment]
Another piece of information:  When I attempt to edit the content, I will get the error.  After that happens there is a "Draft" created in the page history even though the change was not successfully made.  I've also found some pages that will allow me to edit, but only save as a hidden draft.  I have to click the Edit button, then I can click the "Publish" button and the change will be applied.

I currently have each page/tab Workflow set to "Direct Publish".  So shouldn't 2SXC skip any subroutines that have to do with drafts or versioning?

**Comment by TwoHeadsBrewing** [comment]
This is really a big issue for us.  We have this tool in production on 125 live sites, and at this point we are either not able to save, or only able to "Save as draft".  Is there any update on this, or on a method to roll back to a previous version of 2sxc?

**Comment by iJungleboy** [comment]
To your direct-publish: no, at leatst by definition 2sxc should create a version all the time - Evoq creates a new version of the page even with direct publish. This allows evoq users to edit a page, and then "release" it as a larger chunk. that's how text-html does it. 

To your; could we disable this - ATM there is no "switch" that would do this. 

To your: downgrade: the previously described method should work, but if it fails, you can always just replace the DLLs and the whole desktopmodules/tosic-sexycontent folder, and it should have the same effecct as a downgrade. 

To get your issue fixed we need to know more about what's happening - but of course we can't do that once you downgrade. Wanna give us access?

**Comment by iJungleboy** [comment]
Turns out that it's not really a 2sxc 9.5 issue, the problem was deeper. 

For some reason, the data in the DB had the language en-US twice - I presume this happened a long time ago, and was not a problem before because it was ignored. Now it found it, and complains. Here's how I found the duplicate language:

```
SELECT TOP (1000) [DimensionID]
      ,[Parent]
      ,[Name]
      ,[SystemKey]
      ,[ExternalKey]
      ,[Active]
      ,[ZoneID]
  FROM [dbo].[ToSIC_EAV_Dimensions]
  Where ZoneId = 2 -- the zone-id of the current portal
```
I got two zones with en-US, one with the id 146, one with 147
Then I checked if any values were attached to these languages. Turns out only one was in use. This is how I checked

```
SELECT TOP (1000) [ValueID]
      ,[DimensionID]
      ,[ReadOnly]
  FROM [dbo].[ToSIC_EAV_ValuesDimensions]
  Where DimensionId = 146
  
SELECT TOP (1000) [ValueID]
      ,[DimensionID]
      ,[ReadOnly]
  FROM [dbo].[ToSIC_EAV_ValuesDimensions]
  Where DimensionId = 147
```

because one wasn't in use, I first test-deleted it using a transaction which I rolled back, since that looked good, I did it again, completing the transaction:

```
Begin transaction
Delete 
  FROM [dbo].[ToSIC_EAV_Dimensions]
  Where DimensionId = 147
  
SELECT TOP (1000) [DimensionID]
      ,[Parent]
      ,[Name]
      ,[SystemKey]
      ,[ExternalKey]
      ,[Active]
      ,[ZoneID]
  FROM [dbo].[ToSIC_EAV_Dimensions]
  Where ZoneId = 2

-- Rollback
Commit
```
Saving then worked again!

Note that I also installed the latest 2sxc 9.5.1 which fixes some more bugs, so your dev system now has  newer release. we'll publish it today for everyone, this is what you'll also want on your live system.

**Comment by TwoHeadsBrewing** [comment]
That is quite an odd issue, thanks for tracking that down.  I'd really like to see a revision to the "Drafts" feature, where if the workflow for the page is set to "Direct Publish" it would not require actual publishing of the page.  Or, at the very least, if a Save on the content would trigger the "Edit Page" action.  That way the user is immediately aware that they need to publish their recent change.

With the current behavior, a user now makes a change to the data, but still needs to click the "Edit" button, and then click the "Publish" button.  It works, but it's more clicks for no functionality.  I think saving as a draft should only be triggered when the workflow options are set to "Save Draft".
