### ISSUE TITLE
Error on updating any Content module (09.05.02)

### ISSUE THREAD

**Issue by mick-bsi** [2sic/2sxc#1307]
Hi,

We have a strange bug since we upgraded to 9.5.2 version, we can't save anymore and get that error :

> Had an error talking to the server (status 400).
> Message: Bad Request
> Detail: The association between entity types 'ToSicEavValues' and 'ToSicEavValuesDimensions' has been severed but the foreign key for this relationship cannot be set to null. If the dependent entity should be deleted, then setup the relationship to use cascade deletes.

To be more precise : **only the first save works** then we can't update...
This is on a 3 languages website but bug still occurs if we deactivate the 2 additional languages.

Error log :
`   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.HandleConceptualNulls()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.CascadeDelete()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.GetEntriesToSave()
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at Microsoft.EntityFrameworkCore.DbContext.SaveChanges(Boolean acceptAllChangesOnSuccess)
   at ToSic.Eav.Repository.Efc.DbDataController.SaveChanges(Boolean acceptAllChangesOnSuccess, SaveChangesEvent baseEvent) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 200
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.<>c__DisplayClass8_1.b__3() in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_newSave.cs:line 151
   at ToSic.Eav.Repository.Efc.DbDataController.DoInTransaction(Action action) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 242
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.SaveEntity(IEntity newEnt, SaveOptions so) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_newSave.cs:line 226
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.<>c__DisplayClass10_1.b__2() in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_newSave.cs:line 241
   at ToSic.Eav.Repository.Efc.DbDataController.DoAndSave(Action action) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 225
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.<>c__DisplayClass10_0.b__1() in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_newSave.cs:line 240
   at ToSic.Eav.Repository.Efc.Parts.DbVersioning.QueueDuringAction(Action action) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbVersioning.cs:line 56
   at ToSic.Eav.Repository.Efc.DbDataController.DoInTransaction(Action action) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 242
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.SaveEntity(List`1 entities, SaveOptions saveOptions) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_newSave.cs:line 245
   at ToSic.Eav.Apps.Parts.EntitiesManager.<>c__DisplayClass10_0.b__0()
   at ToSic.Eav.Repository.Efc.Parts.DbRelationship.DoWhileQueueingRelationships(Action action) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbRelationship.cs:line 22
   at ToSic.Eav.Apps.Parts.EntitiesManager.Save(List`1 entities, SaveOptions saveOptions)
   at ToSic.Eav.WebApi.EntitiesController.SaveMany(Int32 appId, List`1 items, Boolean partOfPage) in C:\Projects\eav-server\ToSic.Eav.WebApi\EntitiesController.cs:line 197
   at ToSic.SexyContent.WebApi.EavApiProxies.EntitiesController.<>c__DisplayClass4_0.b__0(VersioningActionInfo args) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Sxc WebApi\EavApiProxies\EntitiesController.cs:line 119
   at ToSic.SexyContent.WebApi.EavApiProxies.EntitiesController.SaveMany(Int32 appId, List`1 items, Boolean partOfPage) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Sxc WebApi\EavApiProxies\EntitiesController.cs:line 132
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass13.b__c(Object instance, Object[] methodParameters)
   at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func`1 func, CancellationToken cancellationToken)`

* **2sxc version(s):** 9.5.2
* **Browser:** All
* **DNN:** 7.4.2
* **Language:** Any

**Comment by marcingarbarczyk** [comment]
Hello,
tried you use this commit https://github.com/2sic/2sxc/releases/tag/v09.05.02 ?

**Comment by mick-bsi** [comment]
Yes we used that one.

**Comment by iJungleboy** [comment]
I can reproduce this

**Comment by iJungleboy** [comment]
Just released a pre-release of 09.06, pls check and verify, thx!

**Comment by mick-bsi** [comment]
Seems to be OK, thank you ;)
