### ISSUE TITLE
Enhancement: Support Installations which have custom object qualifiers

### ISSUE THREAD

**Issue by hismightiness** [2sic/2sxc#1366]
This is a bug and a violation of DNN best practices.  :( 

This, despite the following comment I found in a SqlDataProvider file:

"_Check for custom Object Qualifier - break installation if it's configured (2sxc does not support object qualifier)_"

There are numerous oddities that occur due to the module not running all SQL queries using SProcs.  As a result, the queries often run, attempting to target DB objects with the wrong names on sites using object qualifiers.  For example, the `Modules` table may not exist, but `xyz_Modules` will.

All SqlDataProvider files should be updated to use the following pattern for all queries that execute against _core DB objects_.

`{databaseOwner}[{objectQualifier}ObjectName]`

**Example Usage:**
`SELECT * FROM {databaseOwner}[{objectQualifier}Modules] WHERE [ModuleID] = @ModuleID;`

In addition, any code that manually runs SQL queries should instead have a SProc created and the code-based query should be updated to execute the SProc instead.  If there are dynamic queries where this is not possible, then the query should still be updated to be aware of object qualifiers.

This issue is keeping me from upgrading a client site to DNN 9.1.1 and it's filling the event log up with exceptions.

**Example Exceptions:**
_Invalid object name 'Modules'._
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action'1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource'1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at ToSic.SexyContent.Installer.V8.Version080501() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Installer\V8.cs:line 151
   at ToSic.SexyContent.Installer.InstallationController.UpgradeModule(String version) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Installer\InstallationController.cs:line 187
   at ToSic.SexyContent.Installer.InstallationController.FinishAbortedUpgrade() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Installer\InstallationController.cs:line 220
   at ToSic.SexyContent.WebApi.View.ModuleController.FinishInstallation() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Sxc WebApi\View\ModuleController.cs:line 309
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass13.b__c(Object instance, Object[] methodParameters)
   at System.Threading.Tasks.TaskHelpers.RunSynchronously[TResult](Func'1 func, CancellationToken cancellationToken)

**NUMEROUS instances of this one...**
_Search: Error while indexing module 3183 on tab 958, portal 8_
at ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Environment\Dnn7\DnnBusinessController.cs:line 89
   at DotNetNuke.Services.Search.ModuleIndexer.IndexSearchDocuments(Int32 portalId, Int32 scheduleId, DateTime startDateLocal, Action'1 indexer)
_Object reference not set to an instance of an object._
at ToSic.SexyContent.Search.SearchController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Search\SearchController.cs:line 58
   at ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\Environment\Dnn7\DnnBusinessController.cs:line 85

**Comment by iJungleboy** [comment]
related to #910 which is also about object qualifiers.

**Comment by iJungleboy** [comment]
Note: just to clarify our position on this: we're totally open to adding this functionality - but it's 3-5 days of work to implement correctly and test against all possible scenarios. 

Since we (2sic) have no use for it, someone else must contribute and help maintain this. 

Since 2sxc ca. 9.3 or so has a "full batch upgrade" mode for new installations, now is a fairly good time to contribute this, as the test-work and risk is lower than it was before. But still: 3-5 days is realistic, and there's a certain ongoing commitment to regularly support breaking things related to this if someone wants to contribute it.
