### ISSUE TITLE
Some errors in the eventlog after upgrade

### ISSUE THREAD

**Issue by trouble2** [2sic/2sxc#1387]
In the eventlog, sometimes we can see the following error.
Perhaps it could be something?

at ToSic.SexyContent.View.InitModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 187
   at ToSic.SexyContent.View.get_ModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 138

**Comment by iJungleboy** [comment]
This is very unspecific. I would need more details to follow up on this. I'll close it for now, but feel free to add more information - in which case I'll reopen it.

**Comment by trouble2** [comment]
Sure, no problem just thought it could help you....

**Comment by iJungleboy** [comment]
I think I found this one... was an incorrect null/zero check.
