### ISSUE TITLE
After upgrade to dnn 9.2 sqldatasource error

### ISSUE THREAD

**Issue by mvanlaar** [2sic/2sxc#1493]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] Content Types or data management
[x] DNN parts

**Current behavior**

After update to 9.2 in a dev env i'm getting this error:

System.Exception: SqlDataSource - The ConnectionString property has not been initialized at ToSic.Eav.DataSources.SqlDataSource.GetList() in C:\Projects\eav-server\ToSic.Eav.DataSources\SqlDataSource.cs:line 213 at ToSic.Eav.DataSources.DataStream.get_List() 

**Expected behavior**

In 9.1.1 i'm not getting this error and the page load correctly.

**Minimal reproduction of the problem with instructions**

Upgrade 9.1.1. to 9.2 site with custom sql connectionstring used in template based on razor. 

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

9.2 dnn. iis 8. .net 4.6
2sxc 9.14 lts
* **2sxc version(s):** 9.14 LTS 
* **Browser:** [all]
* **DNN:** [9.2 ] 
* **Language:** [any/all]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
Please note: there are other issues with DNN 9.2 as well. We'll look into it and release a new version once it's cleared up. 

Can you give a bit more information: does everything stop working or just certain bits? I'm not sure because based on the description.

**Comment by mvanlaar** [comment]
my app is no more working. I cannot edit the datasource any more.

![naamloos](https://user-images.githubusercontent.com/72070/37907895-f3341814-30f5-11e8-8624-c435f83619d4.png)
![naamloos3](https://user-images.githubusercontent.com/72070/37907897-f36327f8-30f5-11e8-9dae-63226cd11e87.png)
![naamloos2](https://user-images.githubusercontent.com/72070/37907898-f3880bcc-30f5-11e8-97e2-3d15d900604a.png)

**Comment by iJungleboy** [comment]
Is it just this one app, or is everything in 2sxc failing?

**Comment by iJungleboy** [comment]
Could you also provide an extensive log of what's happening? See https://2sxc.org/en/blog/post/releasing-2sxc-9-6-with-extensive-logging

**Comment by mvanlaar** [comment]
the strange thing is that after a restart of the app pool i cannot reproduce the error.

**Comment by mvanlaar** [comment]
Extensive logging:



<div class="dnnFormMessage dnnFormWarning">Error: System.Exception: Error getting List of Stream.
Stream Name: Default
DataSource Name: SqlDataSource ---&gt; System.Exception: SqlDataSource - The ConnectionString property has not been initialized
   at ToSic.Eav.DataSources.SqlDataSource.GetList() in C:\Projects\eav-server\ToSic.Eav.DataSources\SqlDataSource.cs:line 213
   at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 106
   --- End of inner exception stack trace ---
   at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 114
   at ToSic.SexyContent.Razor.SexyContentWebPage.AsDynamic(IDataStream stream) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\SexyContentWebPage.cs:line 98
   at ASP._Page_Portals_0_2sxc_Search_Integration_Demo__HotelList_cshtml.Execute()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at System.Web.WebPages.WebPageBase.&lt;&gt;c__DisplayClass7.&lt;RenderPageCore&gt;b__6(TextWriter writer)
   at System.Web.WebPages.WebPageBase.Write(HelperResult result)
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at ToSic.SexyContent.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 62
   at ToSic.SexyContent.Engines.RazorEngine.RenderTemplate() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 90
   at ToSic.SexyContent.Engines.EngineBase.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\Engines\EngineBase.cs:line 92
   at ToSic.SexyContent.SxcInstance.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\SxcInstance.cs:line 179</div>

**Comment by mvanlaar** [comment]
After update to 9.20 the module functions and this is the extensive logging:

2sxc extensive log for 593
Sxc.View(50)CB.Mod(d9) - parent#593, content-block#593, z#2, a#5
Sxc.View(50)CB.Mod(d9) - real app, will load data
Sxc.View(50)CB.Mod(d9)App.2sxcAp(55) - prep App z#2, a#5, allowSE:True, P:0
Sxc.View(50)CB.Mod(d9)App.2sxcAp(55) - create app resources? allowSE:True
Sxc.View(50)CB.Mod(d9)App.2sxcAp(55)App.Zone(05) - zone base for z#2
Sxc.View(50)CB.Mod(d9)App.2sxcAp(55) - init app resources
Sxc.View(50)CB.Mod(d9)Sxc.Instnc(71) - get SxcInstance for a:5 cb:593
Sxc.View(50)CB.Mod(d9)Sxc.Instnc(71)App.PermCk(a7) - init for type:, itm: (), meta1: , meta2: 3
Sxc.View(50)CB.Mod(d9)DNN.Enviro(2c)DNN.Publsh(22) - checking requirements first time for mod:593
Sxc.View(50)CB.Mod(d9)DNN.Enviro(2c)DNN.Publsh(22) - decision: DraftOptional
Sxc.View(50)CB.Mod(d9)App.2sxcAp(55) - init data drafts:True, vers:False, hasConf:True
Sxc.View(50)CB.Mod(d9)App.2sxcAp(55)CG.Manage(bb) - find content-group for mid#593 and tab#140
Sxc.View(50)CB.Mod(d9)App.2sxcAp(55)CG.Manage(bb) - get CG or gen preview for grp#f2798b72-8954-440e-b094-98b48f12c06e, preview#00000000-0000-0000-0000-000000000000
Sxc.View(50)CB.Mod(d9)App.2sxcAp(55)CG.Manage(bb) - get CG#f2798b72-8954-440e-b094-98b48f12c06e
Sxc.View(50)CB.Mod(d9)Sxc.Instnc(71) - template override - check
Sxc.View(50)CB.Mod(d9)Sxc.Instnc(71) - template override - none
Sxc.View(50) - user is editor, will add context
Sxc.View(50)Dnn.Render(32) - will auto-register client dependencies (js/css
Sxc.View(50)CB.Mod(d9)Sxc.Instnc(71) - render
Sxc.View(50)CB.Mod(d9)Sxc.Instnc(71) - system is ready, no upgrade-message to show
Sxc.View(50)CB.Mod(d9)Sxc.Instnc(71) - pre-init innerContent content is empty so no errors, will build
Sxc.View(50)CB.Mod(d9)Sxc.Instnc(71) - standard case, found template, will render
Sxc.View(50)CB.Mod(d9)DS.Create(63) - will create view data source
Sxc.View(50)CB.Mod(d9)DS.Create(63) - mid#593, draft:True, template:List
Sxc.View(50)CB.Mod(d9)DS.Factry(37) - get init #2/5, draft:True, config:True
Sxc.View(50)CB.Mod(d9)DS.Create(63) - use pipeline upstream:False
Sxc.View(50)CB.Mod(d9)DS.Create(63) - override template, & pipe#1421
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6) - build pipe#1421 for a#5, draft:True
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6) - add parts to pipe#1421 
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6) - add 'ToSic.Eav.DataSources.SqlDataSource, ToSic.Eav.DataSources' as part#1422(a2f107...)
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6) - add 'ToSic.Eav.DataSources.SqlDataSource, ToSic.Eav.DataSources' as part#1424(2699f2...)
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6) - add 'ToSic.Eav.DataSources.Paging, ToSic.Eav.DataSources' as part#1428(e3ddf7...)
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6) - add 'ToSic.Eav.DataSources.SqlDataSource, ToSic.Eav.DataSources' as part#1430(4c66b2...)
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6) - add 'ToSic.Eav.DataSources.SqlDataSource, ToSic.Eav.DataSources' as part#1437(44e489...)
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6) - add 'ToSic.Eav.DataSources.SqlDataSource, ToSic.Eav.DataSources' as part#1439(d1b4e5...)
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6) - init wirings⋮9
Sxc.View(50)CB.Mod(d9)Sxc.Instnc(71)Htm.RendEn(f0)App.PermCk(f3) - init for type:, itm:724d88bb-e0b4-463f-aa2a-feef04e679f7 (1173), meta1: , meta2: 
Sxc.View(50)CB.Mod(d9)App.2sxcAp(55) - init data drafts:True, vers:False, hasConf:True
Sxc.View(50)CB.Mod(d9)Sxc.Instnc(71)Htm.RendEn(f0) - will render razor template
Sxc.View(50)CB.Mod(d9)Sxc.Instnc(71)Htm.RendEn(f0) - will render into textwriter
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6)DS.Extern(e8) - get from sql:SELECT distinct([activepropertylist].[City]    ) as City_Name    
  FROM [eanprod].[eanprod].[activepropertylist]
  where [activepropertylist].country = 'CO'
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6)DS.Extern(e8) - will used '' as entity field (null if not found)
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6)DS.Extern(e8) - will use 'City_Name' as title field
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6)DS.Extern(e8) - found:75
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6)DS.Extern(b2) - get from sql:SELECT [activepropertylist].[EANHotelID]
,[activepropertylist].[EANHotelID] as Hotel_ID     
 ,[activepropertylist].[SequenceNumber]
      ,[activepropertylist].[Name]
      ,[activepropertylist].[City]
      ,[activepropertylist].[StarRating]
      ,[hotelimagelist].[URL]
	  ,[chainlist].ChainName
  FROM [eanprod].[eanprod].[activepropertylist]
  LEFT OUTER JOIN [eanprod].[eanprod].[hotelimagelist] on [activepropertylist].EANHotelID = [hotelimagelist].EANHotelID and [hotelimagelist].DefaultImage = 1
  LEFT OUTER JOIN [eanprod].[eanprod].[chainlist] on [activepropertylist].ChainCodeID = [chainlist].ChainCodeID AND [activepropertylist].ChainCodeID <> 0
  where [activepropertylist].country = 'CO'
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6)DS.Extern(b2) - will used 'EANHotelID' as entity field (null if not found)
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6)DS.Extern(b2) - will use 'Name' as title field
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6)DS.Extern(b2) - found:739
Sxc.View(50)CB.Mod(d9)DS.PipeFt(c6)DS.Page(fc) - get page:1 with size25 found:25
Sxc.View(50)CB.Mod(d9)Sxc.Instnc(71)Dnn.Render(b5)Sxc.CliInf(cb) - building entire client-context
