### ISSUE TITLE
9.22 cannot add app

### ISSUE THREAD

**Issue by mvanlaar** [2sic/2sxc#1515]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] edit experience / UI
[x] admin experience UI

**Current behavior**
I'm adding a app to a dnn 9.2 site i'm not getting the list of possible apps. 

**Expected behavior**
list of possible apps

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 9.2  
* **Browser:** [all  ]
* **DNN:** [9.2 ] 
* **Language:** [any/all | English | German | other ]

**Anything you would like to add**
Log entry in log file: 

2018-04-11 13:13:38,242 [WIN-7H47NBKLBFK][Thread:23][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Exception: trying to save attribute DisplayName but can't find definition in DB
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.SaveAttributesInDbModel(IEntity newEnt, SaveOptions so, List`1 attributeDefs, ToSicEavEntities dbEnt, Int32 changeId) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_save.cs:line 277
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.<>c__DisplayClass10_0.<SaveEntity>b__9() in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_save.cs:line 176
   at ToSic.Eav.Repository.Efc.DbDataController.DoAndSave(Action action) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 229
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.<>c__DisplayClass10_0.<SaveEntity>b__4() in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_save.cs:line 179
   at ToSic.Eav.Repository.Efc.DbDataController.DoInTransaction(Action action) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 250
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.SaveEntity(IEntity newEnt, SaveOptions so) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_save.cs:line 212
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.<>c__DisplayClass15_1.<SaveEntity>b__3() in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_save.cs:line 352
   at ToSic.Eav.Repository.Efc.DbDataController.DoAndSave(Action action) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 229
   at System.Collections.Generic.List`1.ForEach(Action`1 action)
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.<>c__DisplayClass15_0.<SaveEntity>b__1() in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_save.cs:line 353
   at ToSic.Eav.Repository.Efc.Parts.DbVersioning.QueueDuringAction(Action action) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbVersioning.cs:line 48
   at ToSic.Eav.Repository.Efc.DbDataController.DoInTransaction(Action action) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 250
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.SaveEntity(List`1 entities, SaveOptions saveOptions) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_save.cs:line 355
   at ToSic.Eav.Apps.Parts.EntitiesManager.<>c__DisplayClass12_0.<Save>b__1()
   at ToSic.Eav.Repository.Efc.Parts.DbRelationship.DoWhileQueueingRelationships(Action action) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\Parts\DbRelationship.cs:line 24
   at ToSic.Eav.Apps.Parts.EntitiesManager.<>c__DisplayClass12_0.<Save>b__0()
   at ToSic.Eav.Repository.Efc.DbDataController.DoButSkipAppCachePurge(Action action) in C:\Projects\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 265
   at ToSic.Eav.Apps.Parts.EntitiesManager.Save(List`1 entities, SaveOptions saveOptions)
   at ToSic.Eav.Apps.Parts.EntitiesManager.Save(IEntity entity, SaveOptions saveOptions)
   at ToSic.Eav.Apps.AppManager.MetadataEnsureTypeAndSingleEntity(String scope, String setName, String label, Int32 appAssignment, Dictionary`2 values)
   at ToSic.Eav.Apps.AppManager.EnsureAppIsConfigured(Int32 zoneId, Int32 appId, Log parentLog, String appName)
   at ToSic.Eav.Apps.App..ctor(Int32 zoneId, Int32 appId, Boolean allowSideEffects, Log parentLog, String logMsg)
   at ToSic.Eav.Apps.App..ctor(IEnvironment env, ITenant tenant, Int32 zoneId, Int32 appId, Boolean allowSideEffects, Log parentLog)
   at ToSic.SexyContent.Internal.AppManagement.<>c__DisplayClass0_0.<GetApps>b__0(KeyValuePair`2 eavApp) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\Internal\AppManagement.cs:line 23
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ToSic.SexyContent.ContentBlocks.ContentGroupReferenceManagerBase.GetSelectableApps() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\ContentBlocks\ContentGroupReferenceManagerBase.cs:line 86
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

![error list apps](https://user-images.githubusercontent.com/72070/38613863-d1095682-3d7a-11e8-9f10-f5436fee8148.png)

**Comment by iJungleboy** [comment]
For reasons I cannot explain yet I believe it's a caching issue. Could you restart the web application and try to install an app again?

**Comment by mvanlaar** [comment]
I've restarted the .net application. Cleared the cache in dnn, restarted dnn. The problem is the same. This api call (/en-us/desktopmodules/2sxc/api/view/Module/GetSelectableApps) is outputting An error has occurred. With in the dnn logfiles the above error.

**Comment by iJungleboy** [comment]
We'll look at this the next two days - I believe this is an important one. Sorry for the inconvenience :(

**Comment by iJungleboy** [comment]
I think I have a fix - could you try this installation pack? 
[2sic_2SexyContent_09.22.00_Install.zip](https://github.com/2sic/2sxc/files/1899183/2sic_2SexyContent_09.22.00_Install.zip)

Note also that the dialogs should work now, but the app which caused trouble was defect, so you'll want to delete it once the dialogs work again, and re-install it.

**Comment by mvanlaar** [comment]
IT works now like expected.
