### ISSUE TITLE
Error with ModuleDataSource

### ISSUE THREAD

**Issue by mvanlaar** [2sic/2sxc#1548]
**I'm submitting a ...**  
[x] bug report => search github for a similar issue before submitting 
[] feature request
[] support request => do not submit here, see https://2sxc.org/en/blog/post/moving-discussions-from-codeplex-to-stack-overflow
[] not sure

**...about**   
[] edit experience / UI
[x] admin experience UI
[] Razor templating
[] JS development
[x] Content Types or data management
[] APIs like REST
[] DNN parts
[] other / unknown

**Current behavior**

**Expected behavior**

When i add a new query in the visual query and try to run it. i'm getting the following error.
![image](https://user-images.githubusercontent.com/72070/39580331-39140de2-4ee9-11e8-82a1-c3d39549b892.png)

![image](https://user-images.githubusercontent.com/72070/39580397-65fe232e-4ee9-11e8-9e5e-8adee4d494ce.png)

**Minimal reproduction of the problem with instructions**

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

* **2sxc version(s):** 9.2.0  
* **Browser:** [all]
* **DNN:** [9.2.0] 
* **Language:** [any/all]

**Anything you would like to add**

Error in log directory:

2018-05-03 15:39:12,768 [WIN-7H47NBKLBFK][Thread:112][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Exception: Error getting List of Stream.
Stream Name: Default
DataSource Name: ModuleDataSource ---> System.Exception: value provider didn't have sxc provider - can't use module data source
   at ToSic.SexyContent.DataSources.ModuleDataSource.get_SxcInstance() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\DataSources\ModuleDataSource.cs:line 56
   at ToSic.SexyContent.DataSources.ModuleDataSource.get_ContentGroup() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\DataSources\ModuleDataSource.cs:line 89
   at ToSic.SexyContent.DataSources.ModuleDataSource.GetListContent() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\SexyContent\DataSources\ModuleDataSource.cs:line 119
   at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 106
   --- End of inner exception stack trace ---
   at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 114
   at ToSic.Eav.Serializers.Serializer.<>c__DisplayClass1_0.<Prepare>b__3(String s) in C:\Projects\eav-server\ToSic.Eav.WebApi\Serializers\Serializer.cs:line 34
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ToSic.Eav.Serializers.Serializer.Prepare(IDataSource source, IEnumerable`1 streamsToPublish) in C:\Projects\eav-server\ToSic.Eav.WebApi\Serializers\Serializer.cs:line 33
   at ToSic.Eav.WebApi.QueryController.QueryPipeline(Int32 appId, Int32 id) in C:\Projects\eav-server\ToSic.Eav.WebApi\QueryController.cs:line 117
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

**Comment by mvanlaar** [comment]
This is the same as #1550

**Comment by mvanlaar** [comment]
This is my config:

![image](https://user-images.githubusercontent.com/72070/39594225-538a2f1c-4f0c-11e8-8675-ab2718a7a883.png)

![image](https://user-images.githubusercontent.com/72070/39594243-6461f78e-4f0c-11e8-9712-20fbdf3bac44.png)
