### ISSUE TITLE
400 Bad request when trying to change entity name/description

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#1637]
**I'm submitting a ...**  
[x] bug report

**...about** 
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
In admin panel, when I try to change the name or description of an entity (only one, the others work fine) with the rename (heart) icon, I get a 400 Bad request with these logs: 

```
2sxc-Api:/desktopmodules/2sxc/api/eav/contenttype/get/?appid=76&scope=2SexyContent
2sCTC[91]:Path: https://site.pt/desktopmodules/2sxc/api/eav/contenttype/get/?appid=76&scope=2SexyContent
2sCTC[91]DNN.Enviro[c0]Dnn.Publsh[32]:()
2sCTC[91]DNN.Enviro[ee]Dnn.Publsh[71]:()
2sCTC[91]CB.Mod[44]:parent#1362, content-block#1362, z#3, a#76
2sCTC[91]CB.Mod[44]:real app, will load data
2sCTC[91]CB.Mod[44]DNN.Enviro[ec]Dnn.Publsh[71]:()
2sCTC[91]CB.Mod[44]App.2sxcAp[44]:prep App z#3, a#76, allowSE:True, P:1
2sCTC[91]CB.Mod[44]App.2sxcAp[44]:create app resources? allowSE:True
2sCTC[91]CB.Mod[44]App.2sxcAp[44]App.Zone[6b]:zone base for z#3
2sCTC[91]CB.Mod[44]App.2sxcAp[44]:init app resources
2sCTC[91]CB.Mod[44]Sxc.Instnc[93]:get SxcInstance for a:76 cb:1362
2sCTC[91]CB.Mod[44]DNN.Enviro[59]Dnn.Publsh[74]:()
2sCTC[91]CB.Mod[44]Sxc.Instnc[93]App.PermCk[4d]:init for type:, itm: (), meta1: 0, meta2:
2sCTC[91]CB.Mod[44]Sxc.Instnc[93]App.PermCk[4d]:constructor
2sCTC[91]CB.Mod[44]Sxc.Instnc[93]App.PermCk[4d]:user may...
2sCTC[91]CB.Mod[44]Sxc.Instnc[93]App.PermCk[4d]:Env allows...
2sCTC[91]CB.Mod[44]Sxc.Instnc[93]App.PermCk[4d]:ok: True because:EnvironmentGlobal
2sCTC[91]CB.Mod[44]DNN.Enviro[59]Dnn.Publsh[74]:Requirements(mod:1362) - checking first time (others will be cached)
2sCTC[91]CB.Mod[44]DNN.Enviro[59]Dnn.Publsh[74]:decision: DraftOptional
2sCTC[91]CB.Mod[44]App.2sxcAp[44]:init data drafts:True, vers:False, hasConf:True
2sCTC[91]CB.Mod[44]App.2sxcAp[44]CG.Manage[d1]:find content-group for mid#1362 and tab#394
2sCTC[91]CB.Mod[44]App.2sxcAp[44]CG.Manage[d1]:get CG or gen preview for grp#00000000-0000-0000-0000-000000000000, preview#7a5073e1-9ea2-40f6-8c2f-eeb86da24504
2sCTC[91]CB.Mod[44]Sxc.Instnc[93]:template override - check
2sCTC[91]CB.Mod[44]Sxc.Instnc[93]:template override - none
2sCTC[91]EavCTC[0b]:get a#76, scope:2SexyContent, stats:False
2sCTC[91]EavCTC[0b]AppMan[74]:Zone 3, App 76
2sCTC[91]EavCTC[0b]AppMan[74]App.Base[d3]:Zone 3, App 76

2sxc-Api:Auto-Log Exception
2sCTC[ef]:Path: https://site.pt/desktopmodules/2sxc/api/eav/contenttype/save/?appid=76
2sCTC[ef]DNN.Enviro[84]Dnn.Publsh[c3]:()
2sCTC[ef]DNN.Enviro[7c]Dnn.Publsh[ae]:()
2sCTC[ef]CB.Mod[3d]:parent#1362, content-block#1362, z#3, a#76
2sCTC[ef]CB.Mod[3d]:real app, will load data
2sCTC[ef]CB.Mod[3d]DNN.Enviro[89]Dnn.Publsh[ae]:()
2sCTC[ef]CB.Mod[3d]App.2sxcAp[5b]:prep App z#3, a#76, allowSE:True, P:1
2sCTC[ef]CB.Mod[3d]App.2sxcAp[5b]:create app resources? allowSE:True
2sCTC[ef]CB.Mod[3d]App.2sxcAp[5b]App.Zone[ff]:zone base for z#3
2sCTC[ef]CB.Mod[3d]App.2sxcAp[5b]:init app resources
2sCTC[ef]CB.Mod[3d]Sxc.Instnc[80]:get SxcInstance for a:76 cb:1362
2sCTC[ef]CB.Mod[3d]DNN.Enviro[1d]Dnn.Publsh[8b]:()
2sCTC[ef]CB.Mod[3d]Sxc.Instnc[80]App.PermCk[f3]:init for type:, itm: (), meta1: 0, meta2:
2sCTC[ef]CB.Mod[3d]Sxc.Instnc[80]App.PermCk[f3]:constructor
2sCTC[ef]CB.Mod[3d]Sxc.Instnc[80]App.PermCk[f3]:user may...
2sCTC[ef]CB.Mod[3d]Sxc.Instnc[80]App.PermCk[f3]:Env allows...
2sCTC[ef]CB.Mod[3d]Sxc.Instnc[80]App.PermCk[f3]:ok: True because:EnvironmentGlobal
2sCTC[ef]CB.Mod[3d]DNN.Enviro[1d]Dnn.Publsh[8b]:Requirements(mod:1362) - checking first time (others will be cached)
2sCTC[ef]CB.Mod[3d]DNN.Enviro[1d]Dnn.Publsh[8b]:decision: DraftOptional
2sCTC[ef]CB.Mod[3d]App.2sxcAp[5b]:init data drafts:True, vers:False, hasConf:True
2sCTC[ef]CB.Mod[3d]App.2sxcAp[5b]CG.Manage[8a]:find content-group for mid#1362 and tab#394
2sCTC[ef]CB.Mod[3d]App.2sxcAp[5b]CG.Manage[8a]:get CG or gen preview for grp#00000000-0000-0000-0000-000000000000, preview#7a5073e1-9ea2-40f6-8c2f-eeb86da24504
2sCTC[ef]CB.Mod[3d]Sxc.Instnc[80]:template override - check
2sCTC[ef]CB.Mod[3d]Sxc.Instnc[80]:template override - none

AbsoluteURL:/desktopmodules/2sxc/api/eav/contenttype/save/
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:741cb403-c309-4c33-8d5d-5a5c83f3185e
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:Z6iGOys7Cu0x/axk5Ll4gdjEqmo=
Message:Object reference not set to an instance of an object.
StackTrace:
at ToSic.Eav.WebApi.ContentTypeController.Save(Int32 appId, Dictionary`2 item) in C:\Projects\eav-server\ToSic.Eav.WebApi\ContentTypeController.cs:line 105 at lambda_method(Closure , Object , Object[] ) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext()
InnerMessage:
InnerStackTrace:
Source:ToSic.Eav.WebApi
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
```

* **2sxc version(s):** 9.32
* **DNN:** [9.2.2 ] 
* **Language:** [any/all | English | German | other ]

**Comment by iJungleboy** [comment]
I believe I found the issue and fixed it - will be in the next 2sxc 9.33 (maybe Release Candidate 2)

**Comment by eXistenZe** [comment]
This is still an issue on 3.35

**Comment by iJungleboy** [comment]
This has been a while - could you maybe post a quick screencast or something so I can see what's happening? Maybe w/an updated insights-debug info?

**Comment by eXistenZe** [comment]
This only happens when trying to change the name and/or description of an entity/content type within the data tab (using the "hear" icon).

There a few queries and dropdown selection fetching data from this entity.
```
AbsoluteURL:/pt-pt/desktopmodules/2sxc/api/eav/contenttype/save/
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:73ee94c5-2209-4468-bd67-5a9cce476a55
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:cvlf+fnRiVkIMDhM8r6BZPwKei0=
Message:Object reference not set to an instance of an object.
StackTrace:
at ToSic.Eav.WebApi.ContentTypeController.Save(Int32 appId, Dictionary`2 item) in C:\Projects\eav-server\ToSic.Eav.WebApi\ContentTypeController.cs:line 104 at lambda_method(Closure , Object , Object[] ) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments) at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Web.Http.Filters.ActionFilterAttribute.d__5.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.ActionFilterAttribute.d__0.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext() --- End of stack trace from previous location where exception was thrown --- at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) at System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext()
InnerMessage:
InnerStackTrace:
Source:ToSic.Eav.WebApi
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: cp82
```

```
2sxc-Api:Auto-Log Exception
2sCTC[a7]:Path: https://site.pt/pt-pt/desktopmodules/2sxc/api/eav/contenttype/save/?appid=76
2sCTC[a7]DNN.Enviro[59]Dnn.Publsh[51]:()
2sCTC[a7]DNN.Enviro[7e]Dnn.Publsh[e5]:()
2sCTC[a7]CB.Mod[37]:parent#1373, content-block#1373, z#3, a#76
2sCTC[a7]CB.Mod[37]Sxc.Instnc[15]:get SxcInstance for a:76 cb:1373
2sCTC[a7]CB.Mod[37]DNN.Enviro[00]Dnn.Publsh[aa]:()
2sCTC[a7]CB.Mod[37]:real app, will load data
2sCTC[a7]CB.Mod[37]DNN.Enviro[af]Dnn.Publsh[c7]:()
2sCTC[a7]CB.Mod[37]App.2sxcAp[bd]:prep App z#3, a#76, allowSE:True, hasDataConfig:True, P:1
2sCTC[a7]CB.Mod[37]App.2sxcAp[bd]:create app resources? allowSE:True
2sCTC[a7]CB.Mod[37]App.2sxcAp[bd]App.Zone[c0]:zone base for z#3
2sCTC[a7]CB.Mod[37]App.2sxcAp[bd]:init app resources
2sCTC[a7]CB.Mod[37]App.2sxcAp[bd]CG.Manage[7d]:find content-group for mid#1373 and tab#404
2sCTC[a7]CB.Mod[37]App.2sxcAp[bd]CG.Manage[7d]:get CG or gen preview for grp#00000000-0000-0000-0000-000000000000, preview#9e9921dc-2206-4497-9f92-853e6890bd9a
2sCTC[a7]CB.Mod[37]Sxc.Instnc[15]:template override - check
2sCTC[a7]CB.Mod[37]Sxc.Instnc[15]:template override - none
Server Name: cp82
```

**Comment by eXistenZe** [comment]
![Image of error](https://cdn.pbrd.co/images/I1bluIc.jpg)

**Comment by iJungleboy** [comment]
I just tried it on my system and it works. 
What's strange is that line 104 in your error log is actually just a line of logging-code: 
```
Log.Add($"save a#{appId}, item count:{item.Count}");
```
So that looks extremely harmless. Maybe you could mail me a link to your solution with host access so I could have a quick look at your environment - maybe I could figure something out.

**Comment by eXistenZe** [comment]
Unfortunately (for me) I cannot give you such access. That would be a knife in the back to my researchers to whom I promise data protection.
I would however be very very grateful if you could access my computer with a browser already opened in the site and logged in. Teamviewer perhaps?

**Comment by iJungleboy** [comment]
That would help, but is more work for us :(
Any chance this could be done as paid work -> 2sxc.org/contact
What time zone are you in?

**Comment by eXistenZe** [comment]
GMT (15:19 now).

I'll try to just copy the entity and if successful delete the problematic
one. (Also having issues with xml import - opened new issue).

This issue remains when exporting the full app into a new portal, so i'll
try to delete everything and send you the app for you to test with only the
entity in question.
