### ISSUE TITLE
Error indexing pages with 2sxc instances not yet configured

### ISSUE THREAD

**Issue by sleupold** [2sic/2sxc#1802]
**I'm submitting a ...** 
[x] bug report

**...about** 
[x] DNN parts

**Current behavior**
If you create a page and click "add module", select "Content" and confirm, the module is added to the page without being configured. When leaving in this state, the DNN search indexer logs an error: Error while indexing module 1636 on tab 420, portal 5

StackTrace:
at ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Environment\Dnn7\DnnBusinessController.cs:line 104 
at DotNetNuke.Services.Search.ModuleIndexer.IndexSearchDocuments(Int32 portalId, ScheduleHistoryItem schedule, DateTime startDateLocal, Action`1 indexer)

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:
at ToSic.SexyContent.Environment.Dnn7.Search.SearchController.GetModifiedSearchDocuments(IInstanceInfo instance, DateTime beginDate) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Search\SearchController.cs:line 69 
at ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\2sxc Dnn\Environment\Dnn7\DnnBusinessController.cs:line 98

Source:ToSic.Sxc.Dnn

**Expected behavior**
no error is logged

**Please tell us about your environment:**
Windows Server 2012R2

* **2sxc version(s):** 9.43.1  
* **Browser:** [all]
* **DNN:** [9.3.2 ] 
* **Language:** [any/all]

**Comment by iJungleboy** [comment]
thx, we'll look into this - don't want to clog up the event-log :)

**Comment by iJungleboy** [comment]
I just tried to reproduce this and couldn't get the error index entries. I was using DNN 9.4 RC1 and 2sxc 10.05, but I'm sure nothing changed. Could you re-verify or help me reproduce this issue?

**Comment by iJungleboy** [comment]
Closed because of inactivity, will reopen if it surfaces again.

**Comment by tpperlman** [comment]
This issue has appeared on a new DNN v09.06.01 install running 2SXC v11.02.00. Blank 2SXC module fills event log with errors starting with, "Search: Error while indexing module..."

**Comment by tpperlman** [comment]
I am still having this issue and thousands of entries get added every couple hours. I am now running v11.11.0.

**Comment by tpperlman** [comment]
New site in development running DNN 09.08.00 and 2SXC 11.11.1, log has thousands of entries like the one below. This particular app uses a view with a Default data stream from a query, but I am not sure if that makes a difference.

```
Message:Search: Error while indexing module 424 on tab 21, portal 0

StackTrace:

   at ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Environment\Dnn7\DnnBusinessController.cs:line 107
   at DotNetNuke.Services.Search.ModuleIndexer.IndexSearchDocuments(Int32 portalId, ScheduleHistoryItem schedule, DateTime startDateLocal, Action`1 indexer)

InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

   at ToSic.Eav.Context.IZoneCultureResolverExtensions.SafeCurrentCultureCode(IZoneCultureResolver resolver) in C:\Projects\2sxc\eav-server\ToSic.Eav.Core\Context\IZoneCultureResolverExtensions.cs:line 13
   at ToSic.Eav.DataSources.Queries.QueryBuilder.BuildQuery(QueryDefinition queryDef, ILookUpEngine lookUpEngineToClone, IEnumerable`1 overrideLookUps, Boolean showDrafts) in C:\Projects\2sxc\eav-server\ToSic.Eav.DataSources\Queries\QueryBuilder.cs:line 78
   at ToSic.Eav.DataSources.Queries.Query.CreateOutWithAllStreams() in C:\Projects\2sxc\eav-server\ToSic.Eav.DataSources\Queries\Query.cs:line 105
   at ToSic.Eav.DataSources.Queries.Query.get_Out() in C:\Projects\2sxc\eav-server\ToSic.Eav.DataSources\Queries\Query.cs:line 38
   at ToSic.Sxc.DataSources.BlockDataSourceFactory.GetBlockDataSource(IBlock block, ILookUpEngine configurationProvider) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\DataSources\BlockDataSourceFactory.cs:line 62
   at ToSic.Sxc.Blocks.BlockBase.get_Data() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Blocks\BlockBase.cs:line 145
   at ToSic.Sxc.Search.SearchController.GetModifiedSearchDocuments(IModule module, DateTime beginDate) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\Search\SearchController.cs:line 73
   at ToSic.SexyContent.Environment.Dnn7.DnnBusinessController.GetModifiedSearchDocuments(ModuleInfo moduleInfo, DateTime beginDate) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Environment\Dnn7\DnnBusinessController.cs:line 101

Source:ToSic.Sxc.Dnn
```

**Comment by tpperlman** [comment]
Hi folks, can anyone else verify this issue? Our site is in production now but I've had to throttle the search indexer to daily to keep the logs from filling up.

**Comment by iJungleboy** [comment]
Something seems to cause trouble finding the current culture. 

I'll have to look deeper into it, and/or find a way to only log a certain amount of errors and then stop.

**Comment by iJungleboy** [comment]
I just implemented limiting events logged to 10 (but you could override it in code, in case you really need to debug deeper - after 10 entries it explains how to do that).

**Comment by tpperlman** [comment]
Thank you so much. I am wondering if the issue with the culture is also related to the DNN issue I raised about portal aliases since I know there were some issues in a couple of the latest releases with redirect issues:

https://github.com/dnnsoftware/Dnn.Platform/issues/4306
