### ISSUE TITLE
Version history dialog for entities does not work on non-ML sites

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#19]
Version history does not work on non-ML sites because no defaultCultureDimension is set.

```
Stack Trace:
DotNetNuke.Services.Exceptions.PageLoadException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NotSupportedException: GetEntityVersion without defaultCultureDimension is not yet supported.
   at ToSic.Eav.EavContext.GetEntityVersion(Int32 entityId, Int32 changeId, Nullable`1 defaultCultureDimension)
   at ToSic.Eav.EavContext.GetEntityVersionValues(Int32 entityId, Int32 changeId, Nullable`1 defaultCultureDimension, String multiValuesSeparator)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Web.UI.WebControls.ObjectDataSourceView.InvokeMethod(ObjectDataSourceMethod method, Boolean disposeInstance, Object& instance)
   at System.Web.UI.WebControls.ObjectDataSourceView.ExecuteSelect(DataSourceSelectArguments arguments)
   at System.Web.UI.DataSourceView.Select(DataSourceSelectArguments arguments, DataSourceViewSelectCallback callback)
   at System.Web.UI.WebControls.DataBoundControl.PerformSelect()
   at System.Web.UI.WebControls.BaseDataBoundControl.DataBind()
   at System.Web.UI.WebControls.GridView.DataBind()
   at System.Web.UI.WebControls.BaseDataBoundControl.EnsureDataBound()
   at System.Web.UI.WebControls.CompositeDataBoundControl.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
   --- End of inner exception stack trace --
```

**Comment by raphael-m** [comment]
This needs to be fixed in EAV... GetEntityVersion does not work without a defaultCultureDimension: https://github.com/2sic/eav/blob/master/ToSic.Eav/Persistence/EavContext.cs#L1515

**Comment by grayspace** [comment]
Bump! Our users love this feature, and we'll need it in 8 before we can upgrade.

**Comment by iJungleboy** [comment]
@grayspace  note: it only fails on non-multi-language sites - which is actualy an old bug. so if your users had the feature before, they still should have it now :)

**Comment by grayspace** [comment]
I don't see a "History" button anywhere in the 2sxc 8.0.5 editor dialog, so I assumed it is not working.

**Comment by iJungleboy** [comment]
The button is currently only in the management ui.

**Comment by grayspace** [comment]
I've looked through the management ui, and can't seem to find the history button, or anywhere to revert back to older versions of an entity. If I can't easily find it, I know content editors will have difficulty finding it as well.

**Comment by iJungleboy** [comment]
@grayspace thx - I'll check...

**Comment by iJungleboy** [comment]
Close as replaced by #580
