### ISSUE TITLE
CreateSource<RelationshipFilter> raises error

### ISSUE THREAD

**Issue by nicpitsch** [2sic/2sxc#1986]
**I'm submitting a ...** 

[x] bug report 
[x] not sure whether only missing a @using

**...about**   
[x] Razor templating
[x] Content Types or data management

**Current behavior**
Create a RelationshipFilter programmatically:
```
@using ToSic.Eav.Data;
@using ToSic.Eav.DataSources;
...
public override void CustomizeData()
{
   var ds = CreateSource<RelationshipFilter>(App.Data["Contents"]);
}
```

Raises an Error:

Message:The given key was not present in the dictionary.

StackTrace:
   at System.ThrowHelper.ThrowKeyNotFoundException()
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ToSic.Sxc.Code.DynamicCodeRoot.get_ConfigurationProvider() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Code\DynamicCodeRoot.cs:line 120
   at ToSic.Sxc.Code.DynamicCodeRoot.CreateSource[T](IDataSource inSource, ILookUpEngine configurationProvider) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Code\DynamicCodeRoot.cs:line 131
   at ToSic.Sxc.Code.DynamicCodeRoot.CreateSource[T](IDataStream inStream) in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Code\DynamicCodeRoot.cs:line 148
   at ASP._Page_Portals_pteng_2sxc_NPi_Content__ListView_cshtml.CustomizeData() in c:\data\HostingSpaces\Nicolo\youri2\wwwroot\Portals\pteng\2sxc\NPi_Content\_ListView.cshtml:line 42
   at ToSic.Sxc.Engines.EngineBase.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Engines\EngineBase.cs:line 99
   at ToSic.Sxc.Blocks.BlockBuilder.Render() in C:\Projects\2sxc-dnn742\Website\DesktopModules\ToSIC_SexyContent\ToSic.Sxc\Blocks\BlockBuilder_Render.cs:line 61

**Expected behavior**
Return a DataSource respectively no error.

**Minimal reproduction of the problem with instructions**

* Look at *Current behavior*.
* Could this by related to `[PublicApi_Stable_ForUseInYourCode]` attribute of *ToSic.Eav.DataSources.RelationshipFilter* class?

**Please tell us about your environment:**
Tried with:
* 2scx version 10.25.04 and/or 10.26.
* DNN version 09.04.04 and/or 09.05.00

**Comment by iJungleboy** [comment]
just fyi: this seems to happen because CreateSource needs to find a configuration provider, and it usually gets it from the Data (not the App.Data) of the current module. Your current view probably doesn't have any data (no content-type assigned and no query). 

We'll try to fix this some time, but as a workaround, just ensure the view has a content-type or query assigned, and then it should work.

**Comment by iJungleboy** [comment]
Though on second thought, my guess is your app may not have a "Contents" type. Could you check that?
because I tried the other case and it works + I did enhance the code a bit to not require a "Default" stream.

**Comment by nicpitsch** [comment]
> Though on second thought, my guess is your app may not have a "Contents" type. Could you check that?

There is a "Content" type in the app. Instead "Contents" is a name of a query which itself returns a stream named "Contents". How should that be refered in a RelationshipFilter source?
```javascript
...
public override void CustomizeData()
{
   var query = ...
   var ds = CreateSource<RelationshipFilter>(query...);
}
```

**Comment by iJungleboy** [comment]
Ah! You don't want `App.Data["name"]`, but instead `App.Query["name"]` 👍

see https://docs.2sxc.org/api/dot-net/ToSic.Eav.Apps.IApp.html#ToSic_Eav_Apps_IApp_Query

The App.Query["query-name"] is a data-source, which in turn can have many streams - but the default is always "Default" and other ones would be 

```
var query = App.Query["query-name"];
var list = query["Categories"]
```

also check out the tutorials https://2sxc.org/dnn-tutorials/en/razor/data220/page
