### ISSUE TITLE
Error Exporting Data for Content Type

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#2249]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] Content Types or data management

**Current behavior**
The following error occurs when trying to export data for a content type:

```
Message:
A suitable constructor for type 'ToSic.Eav.Apps.ImportExport.ExportListXml' could not be located. Ensure the type is concrete and services are registered for all parameters of a public constructor.

StackTrace:
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at ToSic.Eav.Plumbing.IServiceProviderExtensions.Build[T](IServiceProvider serviceProvider) in C:\Projects\2sxc\eav-server\ToSic.Eav.Core\Plumbing\IServiceProviderExtensions.cs:line 13
   at ToSic.Eav.Apps.Parts.EntitiesManager.Exporter(String contentType) in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\Parts\Entity\EntitiesManager_ExportImport.cs:line 12
   at ToSic.Eav.WebApi.ContentExportApi.ExportContent(IUser user, String language, String defaultLanguage, String contentType, ExportSelection exportSelection, ExportResourceReferenceMode exportResourcesReferences, ExportLanguageResolution exportLanguageReferences, String selectedIds) in C:\Projects\2sxc\eav-server\ToSic.Eav.WebApi\ContentExportApi.cs:line 63
   at ToSic.Sxc.Dnn.WebApi.Admin.EntityController.Download(Int32 appId, String language, String defaultLanguage, String contentType, ExportSelection recordExport, ExportResourceReferenceMode resourcesReferences, ExportLanguageResolution languageReferences, String selectedIds) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.WebApi\Dnn\WebApi\Admin\EntityController.cs:line 101
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.<GetExecutor>b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__0.MoveNext()

Source:
Microsoft.Extensions.DependencyInjection.Abstractions
```

* **2sxc version(s):** 11.10.0
* **Browser:** all
* **DNN:** 09.08.00
* **Language:** English

**Comment by iJungleboy** [comment]
thx, just fixed, will release tonight.
