### ISSUE TITLE
DnnTokenReplace errors after upgrading Dnn to 9.08.00

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2265]
I'm submitting a 
[x] bug report 

about
[x] Razor templating
[x] DNN parts
[x] other / unknown

The site was working fine on Dnn 9.03.02 with 2sxc 11.7.3 and Mobius 4.1.1. No Content App installed if that matters. The forms only had 4 fields and were sending emails and storing data, all was fine.

Then upgraded to Dnn 9.08.00. All seemed fine, but I did not test the 2sxc/Mobius forms right away. Proceed with the de-Telerik steps, replaced the file managers, ran the SQL Console scripts, etc.

Since most everything else was working - no other errors that I could find - I went ahead and **upgraded 2sxc to 11.10.1**. This made no difference, still get the errors.

**Current behavior**
Now every time a page with 2sxc/Mobius on it displays, it generated two errors, first a General Exception and then a Module Load Exception. Both copied below.

**Expected behavior**
Things should have continued working after the upgrade.

**Minimal reproduction of the problem with instructions**
Install Dnn 9.03.02, 2sxc 11.7.3 and get Mobius 4.1.1 working. Then upgrade to Dnn 9.08.00.

**Please tell us about your environment:**
Windows Server 2019, MSSQL 2019

2sxc version(s): 11.7.3 and 11.10.1 
Browser: all (no console errors or issues)
DNN: 9.08.00 
Language: any/all

**Anything you would like to add**

## **General Exception**
```
AbsoluteURL: /Default.aspx
DefaultDataProvider: DotNetNuke.Data.SqlDataProvider, DotNetNuke
PortalId:-1
UserId:-1
TabId:-1
Message:Object reference not set to an instance of an object.
StackTrace:
   at DotNetNuke.Services.Tokens.BaseCustomTokenReplace.ReplaceTokens(String sourceText)
   at ToSic.Sxc.Dnn.LookUp.DnnTokenReplace..ctor(Int32 instanceId, PortalSettings ps, UserInfo userInfo) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\LookUp\TokenReplaceDnn.cs:line 24
   at ToSic.Sxc.Dnn.LookUp.GetDnnEngine.GenerateDnnBasedLookupEngine(PortalSettings portalSettings, Int32 instanceId) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\LookUp\GetDnnEngine.cs:line 40
   at ToSic.Sxc.LookUp.AppConfigDelegate.GetConfigProviderForModule(Int32 moduleId, IApp app, IBlock block)
   at ToSic.Sxc.LookUp.AppConfigDelegate.<>c__DisplayClass3_0.<Build>b__0(App appToUse)
   at ToSic.Eav.Apps.App.get_ConfigurationProvider()
   at ToSic.Eav.Apps.App.BuildData()
   at ToSic.Eav.Apps.App.get_Data()
   at ToSic.Sxc.Engines.EngineBase.TryToFindPolymorphPath(String root, IView view, String subPath)
   at ToSic.Sxc.Engines.EngineBase.Init(IBlock block, Purpose purpose, ILog parentLog)
   at ToSic.Sxc.Blocks.BlockBuilder.GetEngine(Purpose renderingPurpose)
   at ToSic.Sxc.Dnn.Web.DnnClientResources.EnsurePre1025Behavior() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\Web\DnnClientResources.cs:line 54
   at ToSic.SexyContent.View.TryCatchAndLogToDnn(Action action, Action`1 timerWrap) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Main\View.ascx.Errors.cs:line 44
```
## **Module Load Exception**
```
ModuleId:553
ModuleDefId:139
FriendlyName: Start a Conversation
ModuleControlSource: DesktopModules/ToSIC_SexyContent/View.ascx
AbsoluteURL:/Default.aspx
DefaultDataProvider: DotNetNuke.Data.SqlDataProvider, DotNetNuke
AssemblyVersion:9.8.0
PortalId:0
UserId:5
TabId:55
RawUrl:/
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at DotNetNuke.Services.Tokens.BaseCustomTokenReplace.ReplaceTokens(String sourceText)
   at ToSic.Sxc.Dnn.LookUp.DnnTokenReplace..ctor(Int32 instanceId, PortalSettings ps, UserInfo userInfo) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\LookUp\TokenReplaceDnn.cs:line 24
   at ToSic.Sxc.Dnn.LookUp.GetDnnEngine.GenerateDnnBasedLookupEngine(PortalSettings portalSettings, Int32 instanceId) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\LookUp\GetDnnEngine.cs:line 40
   at ToSic.Sxc.LookUp.AppConfigDelegate.GetConfigProviderForModule(Int32 moduleId, IApp app, IBlock block)
   at ToSic.Sxc.LookUp.AppConfigDelegate.<>c__DisplayClass3_0.<Build>b__0(App appToUse)
   at ToSic.Eav.Apps.App.get_ConfigurationProvider()
   at ToSic.Eav.Apps.App.BuildData()
   at ToSic.Eav.Apps.App.get_Data()
   at ToSic.Sxc.Engines.EngineBase.TryToFindPolymorphPath(String root, IView view, String subPath)
   at ToSic.Sxc.Engines.EngineBase.Init(IBlock block, Purpose purpose, ILog parentLog)
   at ToSic.Sxc.Blocks.BlockBuilder.GetEngine(Purpose renderingPurpose)
   at ToSic.Sxc.Dnn.Web.DnnClientResources.EnsurePre1025Behavior() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\Web\DnnClientResources.cs:line 54
   at ToSic.SexyContent.View.TryCatchAndLogToDnn(Action action, Action`1 timerWrap) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Main\View.ascx.Errors.cs:line 44
```

**Comment by jeremy-farrance** [comment]
After restoring from a backup and re-doing the Telerik Removal, I was able to avoid the errors above. I believe they were caused by doing too many steps too fast and skipping testing things. In particular the Dnn Scheduler was off and "mistakes were made" in web.config and /bin folder cleanups. The above error situation may still be valid, but I did not encounter it again on the (more careful) retries. Cheers!
