### ISSUE TITLE
No image encoder was found for the request

### ISSUE THREAD

**Issue by rthoeni** [2sic/2sxc#2278]
**I'm submitting a ...** 

[x] bug report => search github for a similar issue before submitting 

2020-12-08 17:51:53.305+01:00 [Infra][D:2][T:76][FATAL] DotNetNuke.Web.Common.Internal.DotNetNukeHttpApplication - ImageResizer.ImageProcessingException (0x80004005): Image Resizer: No image encoder was found for the request.
   at ImageResizer.Configuration.HttpModuleRequestAssistant.EstimateResponseInfo()
   at ImageResizer.InterceptModule.HandleRequest(HttpContext context, HttpModuleRequestAssistant ra, IVirtualFile vf)
   at ImageResizer.InterceptModule.CheckRequest_PostAuthorizeRequest(Object sender, EventArgs e)
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStepImpl(IExecutionStep step)
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**...about**   
[x] other / unknown

**Current behavior**

Upgrade 2sic 11.11.00/DNN 9.8.0 from Version 11.10.01/DNN 9.8.0

**Expected behavior**

**Minimal reproduction of the problem with instructions**

11.10.01 App Swiper function and after Upgrade 2SC to 11.11.00 App Swiper shows nothing, but the Image is there
<img width="1128" alt="Bildschirmfoto 2020-12-08 um 18 05 53" src="https://user-images.githubusercontent.com/12658708/101516783-33a54b80-3980-11eb-9186-457a9e1b15ed.png">

**What is the motivation / use case for changing the behavior?**

**Please tell us about your environment:**

Windows Server 2019, SQL Express 2019, IIS 10, ASP.net 4.8

* **2sxc version(s):** 11.11.0  
* **Browser:** [ i have only OS 14.0.1 Safari ]
* **DNN:** [9.8.0 ] 
* **Language:** [any/all]

**Anything you would like to add**

**Comment by iJungleboy** [comment]
My guess is it's the WebP encoding that causes trouble. The swiper had an option to use WebP (a new experimental feature in 11.7 or so) but WebP caused so much trouble we had to disable it again #2266  . Pls check if it's trying to request webp in the url (`format=webp`). 

If that is the case, disable it in the app-settings and everything should work again.

**Comment by rthoeni** [comment]
Thanks Daniel
it function. I closed this here. Great thanks for you work all time.
