### ISSUE TITLE
Inserting new 2sxc entity - DNN schedule task

### ISSUE THREAD

**Issue by josip8** [2sic/2sxc#2357]
**I'm submitting a ...** 
[x] bug report
[x] feature request
[x] not sure

**...about**   
[x] Content Types or data management
[x] DNN parts
[x] other / unknown

---

When I try to insert new 2sxc entity inside DNN schedule task I get an error. I have no problem with fetching data from 2sxc, only inserting.

I tried multiple ways of doing this. Here are all of the examples:
```
// create new entry
var guid = Guid.NewGuid();
var newEntry = new Dictionary<string, object>
            {
              { "Name", "Test" },
              { "EntityGuid", guid }
            };

// First try 
var firstApp= ToSic.Sxc.Dnn.Factory.App(2, 6);
firstApp.Data.Create("ContentTypeName", newEntry);

// Second try
var secondTry = ToSic.Sxc.Dnn.Factory.CmsBlock(55, 446);
sxcInstance.Block.App.Data.Create("ContentTypeName", newEntry);

// Third try
var thirdApp = ToSic.Sxc.Dnn.Factory.App(6, new PortalSettings(0));
thirdApp.Data.Create("ContentTypeName", newEntry);


// getting data works
var existing = firstApp.Data["ContentTypeName"].FirstOrDefault();

```

I tested 'First try' inside 2sxc web api and it works there.

I don't know if this is a bug, or 2sxc doesn't allow this feature.

This is the error from first try only (I can post other errors if needed, but I wanted to keep this post smaller):
```
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:40dc2013-4edc-4695-b41a-499c942756fc

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:Dv7XsVcC4fclBmLlQd+T3sq8BeQ=

Message:Value cannot be null. Parameter name: key

StackTrace:

   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at DotNetNuke.Services.Localization.LocaleController.GetLocale(Int32 portalID, String code)
   at DotNetNuke.Services.Localization.LocaleController.GetLocale(String code)
   at DotNetNuke.Entities.Portals.PortalController.GetPortal(Int32 portalId, String cultureCode)
   at DotNetNuke.Entities.Portals.PortalController.GetPortal(Int32 portalId)
   at DotNetNuke.Entities.Portals.PortalSettings..ctor(Int32 tabId, Int32 portalId)
   at ToSic.Sxc.Dnn.Run.DnnZoneMapper.CulturesWithState(Int32 siteId, Int32 zoneId) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\Run\DnnZoneMapper.cs:line 78
   at ToSic.Eav.Apps.AppData.GetDefaultLanguage() in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\AppData.cs:line 49
   at ToSic.Eav.Apps.AppData.DataController() in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\AppData.cs:line 63
   at ToSic.Eav.Apps.AppData.Create(String contentTypeName, Dictionary`2 values, String userName, ITarget target) in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\AppData.cs:line 75
   at Sistemi.Modules.KbcXml.Schedules.ImportXml.import() in d:\Materijali\KBCSplit\Website\Dev\kbsplit-website2021\Website\App_Code\ImportXml.cs:line 71
InnerMessage:

InnerStackTrace:

Source:mscorlib

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:
```
---

* **2sxc version(s):** 11.11.4  
* **Browser:** [all | Chrome XX | Firefox XX | Edge XX | IE XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari ]
* **DNN:** [ 9.8.0 ] 
* **Language:** [any/all ]

**Comment by iJungleboy** [comment]
This is probably an issue related to how DNN works. 

Basically in a real DNN context (page request) various pieces of information have been prepared by DNN and the code can just pick it up. This includes things like `PortalId` and similar. 

Outside of a real DNN context things get more difficult - for example in the search scheduler, which is probably the most similar setup to yours. 

Based on the error, it seems that it's not possible to get the languages activated on this portal, so it fails. 

You have two options

1. Cheap: create a Web-API which does this, and call that from a scheduled job
2. Good: work on 2sxc and change the code which finds this information to handle this edge case.

**Comment by iJungleboy** [comment]
I'll close this for now.
