### ISSUE TITLE
All apps in one site return "Object reference not set to an instance of an object"

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2541]
**I'm submitting a ...**  
[x] bug report 

**...about**  
[x] other / unknown

**Current behavior** 
App pages with apps return to
Default.aspx?tabid=92&error=Object+reference+not+set+to+an+instance+of+an+object.&content=0

This only happens in one of the three sites of my DNN install. The other two work fine.

```
Errors on log:
Message:Sequence contains no matching element

StackTrace:

   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at ToSic.Eav.Caching.AppsCacheBase.GetIdentity(Nullable`1 zoneId, Nullable`1 appId) in C:\Projects\2sxc\eav-server\ToSic.Eav.Core\Caching\Apps\AppsCacheBase.cs:line 177
   at ToSic.Eav.Persistence.Efc.Efc11Loader.LoadBasicAppState(Int32 appId) in C:\Projects\2sxc\eav-server\ToSic.Eav.Persistence.Efc\Efc11Loader_App.cs:line 31
   at ToSic.Eav.Persistence.Efc.Efc11Loader.AppState(Int32 appId, Boolean ensureInitialized) in C:\Projects\2sxc\eav-server\ToSic.Eav.Persistence.Efc\Efc11Loader_App.cs:line 43
   at ToSic.Eav.Caching.AppsCacheBase.GetOrBuild(IAppIdentity appIdentity, String primaryLanguage) in C:\Projects\2sxc\eav-server\ToSic.Eav.Core\Caching\Apps\AppsCacheBase.cs:line 133
   at ToSic.Sxc.Context.ContextOfApp.get_AppState() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Context\ContextOfApp.cs:line 60
   at ToSic.Sxc.Context.ContextOfApp.get_UserMayEdit() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Context\ContextOfApp.cs:line 55
   at ToSic.Sxc.Blocks.BlockBuilder.RenderInternal() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Blocks\BlockBuilder_Render.cs:line 78
```

```
InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

   at ToSic.Sxc.Dnn.Web.DnnClientResources.get_Features() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\Web\DnnClientResources.cs:line 43
   at ToSic.Sxc.Dnn.Web.DnnClientResources.AddEverything(List`1 features) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\Web\DnnClientResources.cs:line 51
   at ToSic.Sxc.Dnn.View.Page_PreRender(Object sender, EventArgs e) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Main\View.ascx.cs:line 108
   at System.Web.UI.Control.OnPreRender(EventArgs e)
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.UI.Control.<PreRenderRecursiveInternalAsync>d__249.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Util.WithinCancellableCallbackTaskAwaitable.WithinCancellableCallbackTaskAwaiter.GetResult()
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
```

```
InnerMessage:Object reference not set to an instance of an object.

InnerStackTrace:

   at ToSic.Sxc.Dnn.View.<>c__DisplayClass12_0.<RenderViewAndGatherJsCssSpecs>b__0() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Main\View.ascx.cs:line 159
   at ToSic.Sxc.Dnn.View.TryCatchAndLogToDnn(Action action, Action`1 timerWrap) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Main\View.ascx.Errors.cs:line 21
```

**Instructions to Reproduce the Problem**
Updated to 12.4. I am unsure if this is the only thing I changed.

**Your environment**

* **2sxc version(s):** 12.4 
* **Browser:** [ all ]
* **DNN:** [ 9.9 ] 
* **Language:** [ English | Portuguese ]

**Comment by iJungleboy** [comment]
I haven't seen this, but I have a guess because it seems to break an entire site.

Basically there is a ZoneId in the PortalSettings which tells 2sxc which Zone is used in a specific site. If the PortalSettings have a bug (it's happened a few years ago) then 2sxc will ask for this, not get a result and create a new zone - which of course then doesn't exist and doesn't have any apps in it yet. 

I suggest you compare the list of zones (don't know the table name, but it should be obvious) and compare the zone which should be used with the ID in the PortalSettings table of Dnn which should be used. I think that should get you there.

**Comment by eXistenZe** [comment]
Everything seems fine.

![appzones](https://user-images.githubusercontent.com/26518879/136008616-0fd6b96c-9d73-46c1-9525-772094a6499b.jpg)

![pseetings](https://user-images.githubusercontent.com/26518879/136008622-e17dcf82-a70d-4167-b7c9-003789317cce.jpg)

![zones](https://user-images.githubusercontent.com/26518879/136008629-04e5e721-e9db-45e5-971e-b4dc322e9da5.jpg)

**Comment by eXistenZe** [comment]
Update:
This happens in nearly all pages, but not all.
I opened the 2sxc app manager and found that the problematic apps are gone :(
Let's hope the backups have up to date versions...

**Comment by iJungleboy** [comment]
I don't think the apps are gone - it's just not looking for them in the right place. 
Can you check the insights-logs? you should usually see what zone / app it's trying to get.

I could also give you a pre-release of 12.05 in case that might fix it...
