### ISSUE TITLE
Issue with List Feature (Accordions)

### ISSUE THREAD

**Issue by marcelom2s** [2sic/2sxc#2674]
**I'm submitting a ...**   
[x] bug report => I did a search in git hug it and nothing has been found

**...about** 
[x] edit experience / UI

**Current behavior**   
Content list feature is not working as expected. When new list items are added and edited, any previously added items are either reverted back to the demo content or removed from the list entirely. This is reproducible in the Accordions components as well. Please see video attached below for details if needed. Please find attached the code for that if needed.

**Expected behavior**  
Only the edited item should be affected, without side effects to the other elements in the list.

**Instructions to Reproduce the Problem**
Please find attached in this video how to reproduce it:
https://user-images.githubusercontent.com/40805926/157544489-2e1a7320-c68c-4fbd-9769-f336f2eac23b.mp4
Code (it is reproducible in the 2sxc accordion app as well):
[_accordion-list.cshtml.txt](https://github.com/2sic/2sxc/files/8218477/_accordion-list.cshtml.txt)

**Why change the behavior?**  
Because it sounds like a bug that prevents the component usage for that. It wasn't an issue in when we built the Accordion List view in an earlier version (10.3). It started after we updated to 12.08. So we tried two things:
- Upgrade to version 13 but the issue persists.
- Attempted to downgrade for now to v10.3 but v12 has database changes.

* **2sxc version(s):** 11.08.0 and 13.2.0 
* **Browser:** [all]
* **DNN:** [9.1.1 ] 
* **Language:** [any/all ]

**Anything you would like to add**
Thanks for the great product. Let me me know if there is anything else that we can do to help resolving it.

**Comment by iJungleboy** [comment]
Thx, we'll look into it. It could be related to #2653

**Comment by iJungleboy** [comment]
I must say it's very strange - haven't seen this behavior before. 

I noticed you're using Evoq, not Dnn. I have heard of a few issues related to page workflows. Can you also reproduce this on Dnn or only on Evoq?

**Comment by marcelom2s** [comment]
Thanks for the response. We didn't try in DNN as our product is built on EVOQ.

**Comment by iJungleboy** [comment]
Please test, to better verify the root cause. Evoq may be interefering with the page workflow, in which case we would research a different fix. 

See for example #2637

**Comment by marcelom2s** [comment]
Thank you! Any information that you could provide will be very helpful. We will try to see if we can have it fixed in the source code and share it here, but time constraint may be a blocker from our side. I assume that this component is not compatible with EVOQ so? Or that's a wrong assumption? I'm asking because we start having another issue (after we upgraded to V13), this is happening while adding the Content to a page:

2022-03-10 23:55:38,597 [DSVWCPCORD0013][Thread:78][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=1750&error=An unexpected error has occurred&content=0
System.ArgumentNullException: Value cannot be null.
Parameter name: provider
at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
at ToSic.Sxc.Dnn.DnnStaticDi.GetPageServiceProvider() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\DnnStaticDi.cs:line 60
at ToSic.Sxc.Dnn.DnnStaticDi.CreateModuleServiceProvider() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\DnnStaticDi.cs:line 74
at ToSic.Sxc.Dnn.View.get_ServiceProvider() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\View.ascx.cs:line 23
at ToSic.Sxc.Dnn.View.Page_Load(Object sender, EventArgs e) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\View.ascx.cs:line 0
at System.Web.UI.Control.OnLoad(EventArgs e)
at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e)
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Control.LoadRecursive()
at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by iJungleboy** [comment]
AFAIK quite a lot of people use 2sxc on Evoq. 

We from 2sic don't, as we don't have a need for the Evoq feature set. 

The error described in your last message may be fixed with v13.03

**Comment by marcelom2s** [comment]
Thanks for the feedback. Since this is not reproducible at your side it may be something specific in our side and the fact that we use EVOQ. I will go ahead and close this issue, we have decided to use a different component to the accordions implementation, thanks!
