### ISSUE TITLE
Custom Data Types & Views Issue

### ISSUE THREAD

**Issue by marcelom2s** [2sic/2sxc#2686]
I'm submitting a bug report about edit experience / UI

Current behavior
We are unable to create or use custom Content Types or Views in any way. 

Expected behavior
We should be able to create or use custom Content Types or Views without errors. 

Instructions to Reproduce the Problem
1) Add an Adam Content module to the page
2) Open the Adam admin menu
3) Create a new Content Type
3.1)Navigate to the “Data” pane.
3.2)Click the button in the bottom left corner (tooltip: “Create a new content type”)
3.3)Create content type as normal (add a name, fields, etc.)
4) Create a new View
4.1) Navigate to the “Views” pane.
4.2) Click the button in the bottom left corner (tooltip: “Create a new view”)
4.3) Create view as normal (add a name, .cshtml file, assign it to a content type, etc.)
5) Exit the admin menu.
6) Press the “new element” (tooltip text) icon to add a Content Type to the page. 
7) Select the previously made Content Type
8) Select the previously made View. 

A shortened error message displays after selecting a custom Content Type, before selecting a view. 
Another error message displays when trying to use a custom View with an out-of-the-box Content Type such as Basic Content. 

2sxc version(s): 12.08.0
Browser: [all]
DNN: [9.1.1 ] (EVOQ)
Language: [any/all ]

**Comment by iJungleboy** [comment]
@marcelom2s Please include some print-screens of the error. 

Also maybe some console details from the network, so we can see what the server reported.

**Comment by iJungleboy** [comment]
I've never seen this.

For clarification: this doesn't seem to happen when creating the view - that probably works - but when you load the page you see this error, right?

To me it feels like there is some kind of issue with the .net framework, not related to 2sxc. 
I would recommend you flush your compiled .net-pages file cache in system32

**Comment by marcelom2s** [comment]
Thanks for you response. Answering your question, yes, it happens while loading the page. I will give it a try after business hours.

**Comment by marcelom2s** [comment]
I tried it but the problem persists. If that helps this is the DNN log:

2022-03-24 03:00:19,308 [DSVWCPCORD0016][Thread:55][ERROR] DotNetNuke.Services.Exceptions.Exceptions - FriendlyMessage="Error: Content is currently unavailable." ctrl="ASP.desktopmodules_tosic_sexycontent_view_ascx" exc="System.Web.HttpCompileException (0x80004005): c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\0aa5b5ed\8b7df453\App_Web__myfile.cshtml.5f25b303.q4f6ffsy.0.cs(31): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @
   at System.Web.Compilation.AssemblyBuilder.Compile()
   at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)
   at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath)
   at ToSic.Sxc.Engines.RazorEngine.CreateWebPageInstance() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Razor\Engines\Razor\RazorEngine.cs:line 98
   at ToSic.Sxc.Engines.RazorEngine.InitWebpage() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Razor\Engines\Razor\RazorEngine.cs:line 106
   at ToSic.Sxc.Engines.RazorEngine.Init() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Razor\Engines\Razor\RazorEngine.cs:line 47
   at ToSic.Sxc.Blocks.BlockBuilder.GetEngine(Purpose renderingPurpose)
   at ToSic.Sxc.Dnn.Web.DnnClientResources.NeedsPre1025Behavior() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\Web\DnnClientResources.cs:line 98
   at ToSic.Sxc.Dnn.View.<>c__DisplayClass9_0.<Page_Load>b__0() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Main\View.ascx.cs:line 79
   at ToSic.Sxc.Dnn.View.TryCatchAndLogToDnn(Action action, Action`1 timerWrap) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Main\View.ascx.Errors.cs:line 21"
2022-03-24 03:00:19,338 [DSVWCPCORD0016][Thread:55][ERROR] DotNetNuke.Services.Exceptions.Exceptions - System.Web.HttpCompileException (0x80004005): c:\Windows\Microsoft.NET\Framework64\v4.0.30319\Temporary ASP.NET Files\root\0aa5b5ed\8b7df453\App_Web__myfile.cshtml.5f25b303.q4f6ffsy.0.cs(31): error CS1646: Keyword, identifier, or string expected after verbatim specifier: @
   at System.Web.Compilation.AssemblyBuilder.Compile()
   at System.Web.Compilation.BuildProvidersCompiler.PerformBuild()
   at System.Web.Compilation.BuildManager.CompileWebFile(VirtualPath virtualPath)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultInternal(VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVPathBuildResultWithNoAssert(HttpContext context, VirtualPath virtualPath, Boolean noBuild, Boolean allowCrossApp, Boolean allowBuildInPrecompile, Boolean throwIfNotFound, Boolean ensureIsUpToDate)
   at System.Web.Compilation.BuildManager.GetVirtualPathObjectFactory(VirtualPath virtualPath, HttpContext context, Boolean allowCrossApp, Boolean throwIfNotFound)
   at System.Web.Compilation.BuildManager.GetCompiledType(VirtualPath virtualPath)
   at ToSic.Sxc.Engines.RazorEngine.CreateWebPageInstance() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Razor\Engines\Razor\RazorEngine.cs:line 98
   at ToSic.Sxc.Engines.RazorEngine.InitWebpage() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Razor\Engines\Razor\RazorEngine.cs:line 106
   at ToSic.Sxc.Engines.RazorEngine.Init() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Razor\Engines\Razor\RazorEngine.cs:line 47
   at ToSic.Sxc.Blocks.BlockBuilder.GetEngine(Purpose renderingPurpose)
   at ToSic.Sxc.Dnn.Web.DnnClientResources.NeedsPre1025Behavior() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\Dnn\Web\DnnClientResources.cs:line 98
   at ToSic.Sxc.Dnn.View.<>c__DisplayClass9_0.<Page_Load>b__0() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Main\View.ascx.cs:line 79
   at ToSic.Sxc.Dnn.View.TryCatchAndLogToDnn(Action action, Action`1 timerWrap) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Main\View.ascx.Errors.cs:line 21

**Comment by marcelom2s** [comment]
See below. It was generated with invalid characters. We have deleted it to have it working.
![1](https://user-images.githubusercontent.com/40805926/160399671-504a0933-018a-49d9-bf59-27342a8cdfb1.PNG)

**Comment by iJungleboy** [comment]
Do you know what the invalid character was? So we could change that in the template.

AFAIK a comment after `@inherits` should be ok, so there must be something else - or was that the problem?
