### ISSUE TITLE
Exception on DNN start: "Some Stream-Wirings were not created"

### ISSUE THREAD

**Issue by tvatavuk** [2sic/2sxc#2697]
**I'm submitting a ...**   
[x] bug report => search github for a similar issue before submitting 

**...about**   
[x] other / unknown

**Current behavior**   

Exception on DNN start: "Some Stream-Wirings were not created" that on page reload go away.

![image](https://user-images.githubusercontent.com/2724850/160817656-35a09cec-03c4-4fc4-923b-05291ee0f62e.png)

Message:Some Stream-Wirings were not created: 298de0e3-67d8-45ec-a864-c84132ad1ea6:Default>376cd440-59fd-493c-b791-f0b526d7255c:Default, 298de0e3-67d8-45ec-a864-c84132ad1ea6:Drafts>376cd440-59fd-493c-b791-f0b526d7255c:Drafts, 298de0e3-67d8-45ec-a864-c84132ad1ea6:Published>376cd440-59fd-493c-b791-f0b526d7255c:Published, 376cd440-59fd-493c-b791-f0b526d7255c:Default>0d974619-a658-422f-88e5-8cd5340f62d6:Default, e8128768-dcba-4cb0-a011-e662579e9b2c:Default>ad6acded-b4c7-4ad9-b33b-57bc2a659716:Default, 0d974

StackTrace:

InnerMessage:Some Stream-Wirings were not created: 298de0e3-67d8-45ec-a864-c84132ad1ea6:Default>376cd440-59fd-493c-b791-f0b526d7255c:Default, 298de0e3-67d8-45ec-a864-c84132ad1ea6:Drafts>376cd440-59fd-493c-b791-f0b526d7255c:Drafts, 298de0e3-67d8-45ec-a864-c84132ad1ea6:Published>376cd440-59fd-493c-b791-f0b526d7255c:Published, 376cd440-59fd-493c-b791-f0b526d7255c:Default>0d974619-a658-422f-88e5-8cd5340f62d6:Default, e8128768-dcba-4cb0-a011-e662579e9b2c:Default>ad6acded-b4c7-4ad9-b33b-57bc2a659716:Default, 0d974

InnerStackTrace:

   at ToSic.Eav.DataSources.Queries.QueryBuilder.InitWirings(QueryDefinition queryDef, IDictionary`2 dataSources)
   at ToSic.Eav.DataSources.Queries.QueryBuilder.BuildQuery(QueryDefinition queryDef, ILookUpEngine lookUpEngineToClone, IEnumerable`1 overrideLookUps, Boolean showDrafts)
   at ToSic.Eav.DataSources.Queries.Query.CreateOutWithAllStreams()
   at ToSic.Eav.DataSources.Queries.Query.get_Out()
   at ToSic.Sxc.DataSources.Block.SetOut(Query querySource)
   at ToSic.Sxc.DataSources.BlockDataSourceFactory.GetBlockDataSource(IBlock block, ILookUpEngine configurationProvider)
   at ToSic.Sxc.Blocks.BlockBase.get_Data()
   at ToSic.Sxc.Engines.EngineBase.Init(IBlock block, Purpose purpose, ILog parentLog)
   at ToSic.Sxc.Blocks.BlockBuilder.GetEngine()
   at ToSic.Sxc.Dnn.Web.DnnClientResources.NeedsPre1025Behavior() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Web\DnnClientResources.cs:line 97
   at ToSic.Sxc.Dnn.View.<>c__DisplayClass12_0.b__0() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\View.ascx.cs:line 78
   at ToSic.Sxc.Dnn.View.TryCatchAndLogToDnn(Action action, Action`1 timerWrap) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\View.ascx.Errors.cs:line 21
Source:

**Instructions to Reproduce the Problem**

- restart dnn (rebuild 2sxc code)
- run 2 (or more) parallel requests on dnn page with 2sxc module 

**Your environment**  

* **2sxc version(s):** 12.X  
* **Browser:** [all]
* **DNN:** [all] 
* **Language:** [any/all]

**Anything you would like to add**

**Comment by tvatavuk** [comment]
@iJungleboy fix it with https://github.com/2sic/eav-server/commit/a64a01c040f8b7cfbeeb474fff15786f5d7e1b14
