### ISSUE TITLE
After updating to v13 we get errore on views that have permissions set 

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2704]
**I'm submitting a ...**
[x] bug report

**...about**
[x] admin experience UI
[x] other / unknown

**Current behavior**
After updating to 2sxc v13, all my views with access permissions set (based on user or group) return this error on log and becomes inacessible for non-admin user.

```
Message:Object reference not set to an instance of an object.

StackTrace:

   at ToSic.Sxc.Engines.RazorEngine.Render(TextWriter writer) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Engines\Razor\RazorEngine.cs:line 102
   at ToSic.Sxc.Engines.RazorEngine.RenderTemplate() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Razor\Engines\Razor\RazorEngine.cs:line 113
   at ToSic.Sxc.Engines.EngineBase.Render() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Engines\EngineBase.cs:line 155
   at ToSic.Sxc.Blocks.BlockBuilder.RenderInternal() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Blocks\BlockBuilder_Render.cs:line 113
```

**Expected behavior** 
Update does not break apps.
There are also new options in the permissions settings that I can't figure out, such as the permission type.

**Comment by iJungleboy** [comment]
The features management has changed in v13, so features must be activated again. 

Please install 13.05, as 13.04 had a bug where it kept on disabling other features. You should be good to go then. 

Otherwise ping and I'll reopen the issue.
