### ISSUE TITLE
Upgrade from 11.22 to 13.10.1 results in view.ascx error

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2737]
**I'm submitting a ...**   
[x] bug report

**...about**   
[x] upgrade

**Current behavior**   

DNN 9.10.2
2sxc 11.22

On a staging website, I upgraded from 11.22 to 13.10.1 and the installation went through but now all the modules on each page show:

"Something went really wrong in view.ascx - check error logs"

ModuleControlSource:DesktopModules/ToSIC_SexyContent/View.ascx
Message:Unable to resolve service for type 'ToSic.Eav.Plumbing.Generator`1[ToSic.Sxc.Context.IModule]' while attempting to activate 'ToSic.Sxc.Dnn.DnnModuleAndBlockBuilder'.

StackTrace:

InnerMessage:Unable to resolve service for type 'ToSic.Eav.Plumbing.Generator`1[ToSic.Sxc.Context.IModule]' while attempting to activate 'ToSic.Sxc.Dnn.DnnModuleAndBlockBuilder'.

InnerStackTrace:

   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateArgumentCallSites(Type serviceType, Type implementationType, CallSiteChain callSiteChain, ParameterInfo[] parameters, Boolean throwIfCallSiteNotFound)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateConstructorCallSite(Type serviceType, Type implementationType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(ServiceDescriptor descriptor, Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.TryCreateExact(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteFactory.CreateCallSite(Type serviceType, CallSiteChain callSiteChain)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at ToSic.Eav.Plumbing.IServiceProviderExtensions.Build[T](IServiceProvider serviceProvider) in C:\Projects\2sxc\eav-server\ToSic.Eav.Core\Plumbing\IServiceProviderExtensions.cs:line 11
   at ToSic.Sxc.Dnn.View.get_Block() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\View.ascx.cs:line 31
   at ToSic.Sxc.Dnn.View.<>c__DisplayClass12_0.<Page_Load>b__0() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\View.ascx.cs:line 77
   at ToSic.Sxc.Dnn.View.TryCatchAndLogToDnn(Action action, Action`1 timerWrap) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn\View.ascx.Errors.cs:line 21

**Expected behavior** 

Smooth upgrade

**Instructions to Reproduce the Problem**

Upgrade from 11.22 to 13.10.1

**Why change the behavior?**

Bug

**Your environment** 

* **2sxc version(s):** 11.22 to 13.10.1  
* **Browser:** [all  ]
* **DNN:** [9.10.2 ] 
* **Language:** [English ]

**Anything you would like to add**
I realize in hindsight I should probably follow an upgrade path. Like 11.22.01 -> 12.08.01. Is that a safe bet? Is there a way to fix what's broken now or should I restart?

**Comment by iJungleboy** [comment]
This is super strange. Basically if this error were true, nothing would work on any of our installations. 

I do assume you restarted?

Any other ideas? because this is really so foundational that everything would break if it didn't work.

**Comment by iJungleboy** [comment]
thanks, do let us know. if you need direct help, reach out to @tvatavuk - I'll mail you his contact.

It could be related to changes in Dependency-Injection, maybe the upgrade-path missed a clean-up.

**Comment by iJungleboy** [comment]
@ajplopez Since I'm not sure this is really a 2sxc issue, or just something strange that happened in your install I'll close this for now. Add more stuff if necessary and I'll reopen.
