### ISSUE TITLE
Import Content-Type Fails after upgrade to v14

### ISSUE THREAD

**Issue by jeremy-farrance** [2sic/2sxc#2761]
**I'm submitting a [x] bug report**

**...about**   
[x] admin experience UI
[x] Content Types or data management

**Current behavior**   
We re-use common Content-Types across projects. Did an export of the content-type from a 2sxc v13.05 app and tried to import it into another project/app with 2sxc v14.00.00 (recently upgraded, started life at v13.x).
 
Admin Logs:
```
Message: Sequence contains no elements

StackTrace:
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ResultEnumerable`1.GetEnumerator()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.<_TrackEntities>d__17`2.MoveNext()
   at Microsoft.EntityFrameworkCore.Query.Internal.LinqOperatorProvider.ExceptionInterceptor`1.EnumeratorExceptionInterceptor.MoveNext()
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass15_1`1.<CompileQueryCore>b__0(QueryContext qc)
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.GetDbEntity(Int32 entityId) in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_read.cs:line 41
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.<>c__DisplayClass21_0.<SaveEntity>b__3() in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_save.cs:line 118
...
```

**Expected behavior**  
Freshly export CT should just import without an error.

**Instructions to Reproduce the Problem**
Export a content-type, import a content-type

**Your environment**  

* **2sxc version(s):** 14.00.00 
* **Browser:** all/any
* **DNN:** 9.10.02 
* **Language:** any/all

**Anything you would like to add**
Exported CT is attached, Zipped

[ImportFiles-ContentType.zip](https://github.com/2sic/2sxc/files/8794665/ImportFiles-ContentType.zip)

**Comment by iJungleboy** [comment]
thanks - also for the zip, which will help us reproduce this. 
Do you know if this already caused problems in v13, or only in v14?
@tvatavuk pls review.

**Comment by tvatavuk** [comment]
Reproduced issue in 2sxc v13.05 and v14.

**Comment by tvatavuk** [comment]
@jeremy-farrance, I just committed fix, but if You can not wait for next release than there is simple workaround for import of your Content-Type with Metadata json.

In your json, in line 829 there is `"Id:" 1711,` 
![image](https://user-images.githubusercontent.com/2724850/171252586-8bae4db5-4322-43ec-8525-8a9903fffadc.png)

In Your can change line 829 to `"Id:" 0,` and import it, than import will not fail.
![image](https://user-images.githubusercontent.com/2724850/171252650-2d279491-9218-40cc-80e7-678babcec104.png)
![image](https://user-images.githubusercontent.com/2724850/171252255-2fdb3940-1b2d-44ac-a9d1-7f34a6745511.png)
