### ISSUE TITLE
Public forms stopped working at v13

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2797]
**I'm submitting a ...**
[x] bug report
[x] support request

**...about**
[x] JS development
[x] APIs like REST

**Current behavior**
When I try to activate a public form from a non-SU account, I get:
```
ERROR Error: Context is missing some of the required parameters
    at T.value (context.ts:97:13)
    at new he (app.component.ts:40:18)
    at R.ɵfac [as factory] (app.component.ts:20:35)
    at Za (core.mjs:3541:44)
    at u_ (core.mjs:10122:23)
    at vd (core.mjs:12223:23)
    at n.value (core.mjs:21544:25)
    at t.value (core.mjs:26348:42)
    at core.mjs:26031:64
    at Array.forEach (<anonymous>)
ERROR Error: Uncaught (in promise): Error: Cannot match any routes. URL Segment: 'edit/new:RecordUnits&prefill:Whatever'
Error: Cannot match any routes. URL Segment: 'edit/new:RecordUnits&prefill:Whatever'
    at g.value (router.mjs:2938:16)
    at router.mjs:2920:28
    at catchError.js:10:39
    at H._error (OperatorSubscriber.js:19:21)
    at H.value (Subscriber.js:40:18)
    at H.value [as _error] (Subscriber.js:64:30)
    at H.value (Subscriber.js:40:18)
    at H.value [as _error] (Subscriber.js:64:30)
    at H.value (Subscriber.js:40:18)
    at H.value [as _error] (Subscriber.js:64:30)
    at j (zone.js:1213:31)
    at j (zone.js:1167:17)
    at zone.js:1279:17
    at _.value (zone.js:406:31)
    at Object.onInvokeTask (core.mjs:25415:33)
    at _.value (zone.js:405:60)
    at p.value (zone.js:178:47)
    at v (zone.js:582:35)
```

I'm guessing this is because I'm still using:
@Edit.Enable(api: true, forms: true, context: true, autoToolbar: false)

**Expected behavior** 
Please document every breaking change between version updates.
Every documentation on public forms still point to Edit.Enable.

This tutorial has some examples, but not for forms: true.
https://docs.2sxc.org/net-code/razor/services/page-service-activate.html

**Instructions to Reproduce the Problem**
```
$2sxc.cms.run(tag,
        {
            action: "new", 
            contentType: "whatever",
            prefill: {
                var: "whatever"
            }
        })
```

**Your environment** 
* **2sxc version(s):** 13.3

**Comment by iJungleboy** [comment]
The problem is not the `@Edit.Enable` - that still works. 

The problem is probably that the feature activate changed, and for some reason you didn't get notified that the feature isn't enabled any more. 

We've added these warnings and will release it in 14.07.03 LTS tomorrow.
