### ISSUE TITLE
Error: The column name "DisplayName" specified in the PIVOT operator conflicts with the existing column name in the PIVOT argument. The column 'DisplayName' was specified multiple times for 'T'.

### ISSUE THREAD

**Issue by eXistenZe** [2sic/2sxc#2940]
**I'm submitting a ...** 
[x] bug report

**...about**
[x] admin experience UI
[x] Content Types or data management

**Current behavior**
In my custom app, when I try to view the data on a specific data type or configure the fields, I get this error. All other apps and content types work fine. There is no DisplayName field anywhere on the app, but there is one in the users profile.

Error log:
```
Message:The column name "DisplayName" specified in the PIVOT operator conflicts with the existing column name in the PIVOT argument. The column 'DisplayName' was specified multiple times for 'T'.

StackTrace:

   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at DotNetNuke.Data.PetaPoco.PetaPocoExt.ExecuteReader(Database database, String sql, Object[] args)
   at DotNetNuke.Data.PetaPoco.PetaPocoHelper.ExecuteReader(String connectionString, CommandType type, Int32 timeoutSec, String sql, Object[] args)
   at DotNetNuke.Data.SqlDataProvider.ExecuteReader(Int32 timeoutSec, String procedureName, Object[] commandParameters)
   at DotNetNuke.Data.DataProvider.GetAvailableUsersForIndex(Int32 portalId, DateTime startDate, Int32 startUserId, Int32 numberOfUsers)
   at DotNetNuke.Services.Search.UserIndexer.FindModifiedUsers(Int32 portalId, DateTime startDateLocal, IDictionary`2 searchDocuments, IList`1 profileDefinitions, IList`1& indexedUsers, Int32& startUserId)
   at DotNetNuke.Services.Search.UserIndexer.IndexSearchDocuments(Int32 portalId, ScheduleHistoryItem schedule, DateTime startDateLocal, Action`1 indexer)
```

**Instructions to Reproduce the Problem**
Try to open this specific data type. Either the data view or fields view will generate the error.

![image](https://user-images.githubusercontent.com/26518879/204002557-0491d353-80cf-4151-aa8c-123b6ba4ed4b.png)

**Your environment** 

* **2sxc version(s):** 14.12.2
* **DNN:** [ 9.11 ]

**Comment by iJungleboy** [comment]
We have never seen such an issue. 
Could it be that you created a field which is called `DisplayName` and this resulted in surprises?

**Comment by eXistenZe** [comment]
No such field in the app.

**Comment by iJungleboy** [comment]
So we have never seen this, it must be something unique to your setup. Are you able to export the app and publish it here?

does it happen on all types of this app, or just on that one called `Systems` ? could you maybe rename it to something else just to test - in case Systems somehow triggers a internal-name-conflict?

**Comment by eXistenZe** [comment]
[2sxcApp_MaterialVNI_0.0.11.zip](https://github.com/2sic/2sxc/files/10093830/2sxcApp_MaterialVNI_0.0.11.zip)

Here. Please delete the file after download.
This was a poor insight on my part. I deleted the DisplayName profile field, the error does not show on the log again, but the app 500 error remains, so the log and the error were not related.
I tried enabling debug mode but nothing is logged when the 500 error shows (trying to open the entity data or fields).
I uploaded the app into a new install, and the issue remains.

**Comment by iJungleboy** [comment]
@eXistenZe did you restart after deleting the field with that name? just to be sure...

**Comment by eXistenZe** [comment]
Always cleared cache and restart the server after changes for testing.

**Comment by iJungleboy** [comment]
It seems that the field KeyMask has a problem. Here's how it seems to surface: 
![image](https://user-images.githubusercontent.com/5321186/204030199-d386dc2f-6d25-4bff-b6a6-0b60889ae607.png)

The reason is as follows: field configuration varies depending on the field type. To make this possible, fields have Metadata. For example, the first metadata entity is usually of type `@All` and contains name, field type, etc. Another contains information specific to this field - in this case `@Entity` metadata. 

It seems that your field has two `@Entity` metadata attached. I don't know how this could happen, but we've never seen it before. My guess is that for some unlucky reason, two save operations happened at the same time and both thought they should add it. 

You can also see it in the app.xml in the zip line 359+

```
<Entity TargetType="2" AssignmentObjectType="EAV Field Properties" AttributeSetStaticName="@Entity" AttributeSetName="@Entity" EntityGUID="a6773795-ea86-44ed-a296-5528df9d69b8" Json="True" KeyNumber="1871">
  <Value Key="AllowMultiValue" Value="True" Type="Boolean">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="EnableAddExisting" Value="True" Type="Boolean">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="EnableCreate" Value="True" Type="Boolean">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="EnableDelete" Value="False" Type="Boolean">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="EnableEdit" Value="True" Type="Boolean">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="EnableRemove" Value="True" Type="Boolean">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="EntityType" Value="" Type="String">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="Prefill" Value="" Type="String">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
</Entity>
<Entity TargetType="2" AssignmentObjectType="EAV Field Properties" AttributeSetStaticName="@Entity" AttributeSetName="@Entity" EntityGUID="a6773795-ea86-44ed-a296-5528df9d69b8" Json="True" KeyNumber="1871">
  <Value Key="AllowMultiValue" Value="True" Type="Boolean">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="EnableAddExisting" Value="True" Type="Boolean">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="EnableCreate" Value="True" Type="Boolean">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="EnableDelete" Value="False" Type="Boolean">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="EnableEdit" Value="True" Type="Boolean">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="EnableRemove" Value="True" Type="Boolean">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="EntityType" Value="" Type="String">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
  <Value Key="Prefill" Value="" Type="String">
    <Dimension DimensionID="10" ReadOnly="false" />
  </Value>
</Entity>
```

Note that they also seem to have the same guid/id, which I cannot explain ATM

```
EntityGUID="a6773795-ea86-44ed-a296-5528df9d69b8" Json="True" KeyNumber="1871"
```

Since it's the first we've ever seen, I don't think we'll do anything about it. To fix it on your side, do the following:

Go to scope fields in the data - that's where these metadata entities are stored

![image](https://user-images.githubusercontent.com/5321186/204030645-68e83763-a6a9-4eca-b93b-469f31e3752f.png)

Select the `@Entity` items

![image](https://user-images.githubusercontent.com/5321186/204030742-305d9790-ee17-42aa-80c8-38f42767ed23.png)

I see these:

![image](https://user-images.githubusercontent.com/5321186/204030827-c7e934df-b2a7-4eb6-b60a-c4081d856fa8.png)

I deleted one of the last two, without names, and everything worked again.

**Comment by eXistenZe** [comment]
Great. Thanks.
