### ISSUE TITLE
404 Error Page Not Showing on DNN 9.11 with 2sxc 14.12.3

### ISSUE THREAD

**Issue by ajplopez** [2sic/2sxc#2986]
### I'm submitting a ...
[x] bug report

### ...about

[x] admin experience UI
[x] other / unknown

### Current Behavior / Expected Behavior

I have a DNN 9.11 website that has 2sxc 14.12.3 installed. On my site, I have a 404 Error Page (the typical DNN page). On that page, I had 2 x 2sxc apps dropped on the page, as well as a theme that injected 2sxc for the header and footer.

Since upgrading to DNN 9.11 and patching to 2sxc 14.12.3, my site would throw a 503 error whenever a user browsed to a non-existent URL. For example, if one browsed to domain.org/fasd (not a real URL), it would throw an error like this:

"Application Error
No sites currently exist for this installation. - 503 Service Unavailable"

Typically, if a user browses to a bad URL, it will just show the 404 page set in DNN.

It's a bug. Typically I like to have a nicely styled 404 page that uses 2sxc apps.

I have not yet tested this in 2sxc 15.

Here's what Managed said:

Hello,
 
The issue appears to be related to the 2sxc App module in use on the 404 page. It is causing a 503 error somewhere along the line and that is what ends up being rendered. When I change the permissions on the modules in the 404 page, a normal-ish 404 page is rendered, sans whatever content the 'App' module was intended to produce.
 
I do see there is an update for the module, I would recommend installing that and then changing the permissions of the modules back to being inherited from the page. It is likely simply an incompatibility as you are running the latest version of DNN, hopefully upgrading the module fixes it. If it does not, you'll need to reach out to the module vendor as this is not something we will be able to troubleshoot or fix. The following two errors may be of use to them:

2023-01-23 14:44:58.845-06:00 [GW1010][D:4][T:62][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.NullReferenceException: Object reference not set to an instance of an object.
   at ToSic.Sxc.Services.DnnExtensions.GetScopedService[T]() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\ToSic.Sxc.Services\DnnExtensions.cs:line 49
   at ASP.portals__default_skins_website_full_ascx.__Render__control1(HtmlTextWriter __w, Control parameterContainer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer)
   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.HtmlControls.HtmlForm.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at DotNetNuke.Framework.PageBase.Render(HtmlTextWriter writer)
   at DotNetNuke.Framework.DefaultPage.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()

2023-01-23 14:44:58.850-06:00 [GW1010][D:4][T:62][ERROR] DotNetNuke.Services.Exceptions.Exceptions - ~/Default.aspx?tabid=24&error=An unexpected error has occurred&content=0
System.NullReferenceException: Object reference not set to an instance of an object.
   at ToSic.Sxc.Services.DnnExtensions.GetScopedService[T]() in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\ToSic.Sxc.Services\DnnExtensions.cs:line 49
   at ASP.portals__default_skins_website_full_ascx.__Render__control1(HtmlTextWriter __w, Control parameterContainer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.HtmlControls.HtmlForm.RenderChildren(HtmlTextWriter writer)
   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.HtmlControls.HtmlForm.RenderControl(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at System.Web.UI.HtmlControls.HtmlContainerControl.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Control.RenderChildrenInternal(HtmlTextWriter writer, ICollection children)
   at DotNetNuke.Framework.PageBase.Render(HtmlTextWriter writer)
   at DotNetNuke.Framework.DefaultPage.Render(HtmlTextWriter writer)
   at System.Web.UI.Control.RenderControlInternal(HtmlTextWriter writer, ControlAdapter adapter)
   at System.Web.UI.Page.<ProcessRequestMainAsync>d__523.MoveNext()
   
   The first error above is what is generated when the module settings are set to allow anyone to view the module ( permissions inherited from the parent page ), the second error is what is produced even when the module is effectively disabled on the page ( permissions set to disallow viewing ).
 
I've left the permissions to where at least a page from the site is rendered, although it contains no relevant content, but it will allow you to add an HTML module or something along those lines so you can at least display something meaningful until this can be properly resolved.
 
Again, hopefully it is just a matter of upgrading the module."

### Instructions to Reproduce the Problem

In DNN 9.11 and 14.12.3, add a 2sxc app to the 404 Error Page. Then browse to a non-existent URL to trigger the 404 page. (Assuming that you have a 404 page set in the DNN Site Settings). You'll get an Application 503 error instead of the 404 page that you set.

### Your environment**

* **2sxc version(s):** 14.12.03  
* **Browser:** all
* **DNN:**9.11
* **Hosting platform:** all
* **Language:** English

**Comment by iJungleboy** [comment]
We never heard of this, but I understand the problem - not sure what the root cause is.
Upgrading to v15 won't do anything, since we haven't worked on this. 

We'll review. It probably won't be in 15.01 as we plan to release that soon, but probably 15.02.

BTW: Your error throws on `ToSic.Sxc.Services.DnnExtensions.GetScopedService<T>`. That's actually an indication that DNN does something wrong - because this is just a shorthand to get the ServiceProvider. My guess is that in DNN the ServiceProvider isn't available on error pages. 

Maybe you can find a workaround till we have a solution.

**Comment by ajplopez** [comment]
Thanks for looking into it - I'm happy to log it.

My workaround for now has been to just use the Xcillion theme with an HTML module instead of anything that uses 2sxc on the 404 Error Page. But it will be definitely nice to use 2sxc on the 404 page when it's fixed :)

**Comment by tvatavuk** [comment]
This happens because DNN extension method `GetScope()` returns null while is used on 404 page on non exiting url.
I created issue https://github.com/dnnsoftware/Dnn.Platform/issues/5540

**Comment by iJungleboy** [comment]
@tvatavuk thanks. Can we cheat it, so that in our API it falls back to creating an own scope or something from http like we used to?

**Comment by tvatavuk** [comment]
Added 2 fixes for 404 edge case in DNN.
- one is to use DnnStaticDi.StaticBuild<T>() when dnn GetScope() return null
- other is in DnnPageChanges.ApplyHttpStatus to catch exception "Response is not available in this context."
