### ISSUE TITLE
2SXC v14.12.3 - WebAPI SaveInAdam Error

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#3007]
### I'm submitting a ...
[x] bug report

### ...about
[x] APIs like REST

### Current Behavior / Expected Behavior
Hi folks, we recently upgraded an app from 2SXC v13.01 to v14.12.3 which was functioning previously and now is returning an error with the SaveInAdam command in a WebAPI. We checked the API reference at https://docs.2sxc.org/net-code/web-api/custom-web-api-dotnet-saveinadam.html and don't notice any changes.

Here's what we're posting:

```
                fileName = file;
                var tmpFilePath = PortalSettings.HomeDirectoryMapPath + "tmp\\";
                var filePath = tmpFilePath + file;

                if (System.IO.File.Exists(filePath))
                {
                    var ms = GetFileMemoryStream(filePath);
                    fileByteArray = GetByteArrayFromMemoryStream(ms);

                    SaveInAdam(
                        stream: ms,
                        fileName: file,
                        contentType: "Watercraft",
                        guid: watercraftGuid,
                        field: "RegistrationPhoto");

                    // delete the tmp image
                    System.IO.File.Delete(filePath);
                }
```
The error log reports this:

```
Message:Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.

StackTrace:

   at ToSic.Sxc.Adam.AdamContext.Init(IContextOfApp context, String contentType, String fieldName, Guid entityGuid, Boolean usePortalRoot, ILog parentLog) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Adam\AdamContext.cs:line 78
   at ToSic.Sxc.Adam.AdamContext`2.Init(IContextOfApp context, String contentType, String fieldName, Guid entityGuid, Boolean usePortalRoot, ILog parentLog) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc\Adam\AdamContext_T.cs:line 26
   at ToSic.Sxc.WebApi.Adam.AdamTransactionBase`3.Init(Int32 appId, String contentType, Guid itemGuid, String field, Boolean usePortalRoot, ILog parentLog) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc.WebApi\Adam\AdamTransactionBase.cs:line 32
   at ToSic.Sxc.WebApi.Adam.AdamCode.SaveInAdam(String noParamOrder, Stream stream, String fileName, String contentType, Nullable`1 guid, String field, String subFolder) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc.WebApi\Adam\AdamCode.cs:line 50
   at Custom.Hybrid.Api12.SaveInAdam(String noParamOrder, Stream stream, String fileName, String contentType, Nullable`1 guid, String field, String subFolder) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.WebApi\Custom\Hybrid\Api12_Api.cs:line 116
   at StripeWebhookController.UpdateBoatSlips(Object owner, Int32 propertyId, Object boatSlips) in (ourpath)\Portals\0\2sxc\Members\api\stripeWebhookController.cs:line 460
   at StripeWebhookController.<Post>d__c0.MoveNext() in (ourpath)\Portals\0\2sxc\Members\api\stripeWebhookController.cs:line 108
```
Not sure where further detail might be reported in Insights on where the error is coming from, but this should be working now that the licensing issue has been corrected in issue #3006.

**Comment by tpperlman** [comment]
As an FYI, we had changed the inherit from ToSic.Sxc.Dnn.ApiController to the newer Custom.Dnn.Api12. After switching back as a test, the error is the same.

**Comment by iJungleboy** [comment]
I tested it with a new DNN 911 + 2sxc 14.12.03 LTS with the auto-installed mobius app and there it works.

So there must be some difference that causes the bug - but it can still be a 2sxc bug. Could you please research more and give us more details?

**Comment by tpperlman** [comment]
We've looked through some of the insights logs and see these entries below, not sure if it is helpful. We didn't change any of the code prior to upgrading, and did enable the SaveInAdamApi in features. We don't know where else to look to see if it is a permissions issue or something internal to 2SXC since the event log above showed an error in ToSic.Sxc.Adam.AdamContext.Init.

```
Api.Dnn12[98]AdamCo[82]Adm.TrnUpl[f1] - Init(app: 2/3, type: Watercraft, itemGuid: b7d04e2c-c565-496c-8efb-aa133cf90d33, field: RegistrationPhoto, portalRoot: False) C# LOGGER WARNING: This logger was never closed

    Adm.CtxTT[fe] - Init(..., usePortalRoot: False) C# LOGGER WARNING: This logger was never closed
        Adm.MngrTT[ad] - Init() = ready C#
            Api.Dnn12[98]AdamCo[82]Adm.TrnUpl[f1]Sxc.CtxRes[52]Sxc.CtxApp[4c] - UserMayEdit() = False C#
                App.PrmChk[5e] - Init(type:, itm: (), permList1: 2, permList2: ) = ready C#
                App.PrmChk[5e] - Init(..., , app: 3, ) C#
                App.PrmChk[5e] - ForAppInInstance(ctx, app: ToSic.Eav.Apps.AppState, log) = ok C#
                    App.PrmChk[5e] - Permissions: 2 C#
                App.PrmChk[5e] - UserMay([Delete,DeleteDraft,Create,CreateDraft,Develop,Full,Approve,UpdateDraft,Update]) = False (Undefined) C#
                    Dnn.EnvPrm[47] - EnvironmentAllows([Delete,DeleteDraft,Create,CreateDraft,Develop,Full,Approve,UpdateDraft,Update]) = False because:Undefined C#
                        Dnn.EnvPrm[47] - UserIsAnonymous() UserId:-1= True C#
                    Dnn.EnvPrm[47] - UserIsSystemAdmin() = False C#
                    Dnn.EnvPrm[47] - CurrentZoneMatchesSiteZone() = True C#
                    Dnn.EnvPrm[47] - UserIsContentAdmin() = False C#
                    Dnn.EnvPrm[47] - UserIsModuleAdmin() = False C#
                    Dnn.EnvPrm[47] - UserIsModuleEditor() = False C#
                    Dnn.EnvPrm[47] - Log Warning: Wrapper already closed from previous call
                App.PrmChk[5e] - PermissionList() = found 2 items C#
                App.PrmChk[5e] - PermissionsAllow([Delete, DeleteDraft, Create, CreateDraft, Develop, Full, Approve, UpdateDraft, Update]) for 2 permission items= False C#
                    App.PrmChk[5e] - PermissionAllows(dďcčvfaǔu) = False C#
                        App.PrmChk[5e] - VerifyConditionApplies() = False no-match: false C#
                            App.PrmChk[5e] - condition:, identity:5 C#
                            Dnn.EnvPrm[47] - VerifyConditionOfEnvironment() = False unknown condition: false C#
                    App.PrmChk[5e] - PermissionAllows(dďcčvfaǔu) = False C#
                        App.PrmChk[5e] - VerifyConditionApplies() = False no-match: false C#
                            App.PrmChk[5e] - condition:, identity:7 C#
                            Dnn.EnvPrm[47] - VerifyConditionOfEnvironment() = False unknown condition: false C#
    Adm.CtxTT[fe]Adm.MngrTT[ad]Dnn.FilSys[bb] - Init() = ok C#
    Adm.CtxTT[fe] - Init(app: 2/3, field:RegistrationPhoto, guid:b7d04e2c-c565-496c-8efb-aa133cf90d33) C# LOGGER WARNING: This logger was never closed
        Sec.MPTyps[ee] - Init(..., appId: 3, ...) = ready for z/a:2/3 t/z:0/2 same:True C#
        Dnn.TnScCk[fb] - Init() C#
            Api.Dnn12[98]AdamCo[82]Adm.TrnUpl[f1]Adm.CtxTT[fe]Sec.MPTyps[ee] - BuildTypePermissionChecker(Watercraft) C#
            Api.Dnn12[98]AdamCo[82]Adm.TrnUpl[f1]Adm.CtxTT[fe]Sec.MPTyps[ee] - BuildPermissionChecker(type:Watercraft, item:) C#
            Api.Dnn12[98]AdamCo[82]Adm.TrnUpl[f1]Adm.CtxTT[fe]Sec.MPTyps[ee]App.PrmChk[44] - Init(type:61393528-b401-411f-a001-f423ea46700a, itm: (), permList1: 2, permList2: ) = ready C#
            Api.Dnn12[98]AdamCo[82]Adm.TrnUpl[f1]Adm.CtxTT[fe]Sec.MPTyps[ee]App.PrmChk[44] - Init(..., , app: 3, ) C#
            Api.Dnn12[98]AdamCo[82]Adm.TrnUpl[f1]Adm.CtxTT[fe]Sec.MPTyps[ee]App.PrmChk[44] - ForParts() = ok C#
            Api.Dnn12[98]AdamCo[82]Adm.TrnUpl[f1]Adm.CtxTT[fe]Sec.MPTyps[ee]App.PrmChk[44] - UserMay([Create,Update,Approve,Full,Develop]) = False (Undefined) C#
                Dnn.EnvPrm[f0] - EnvironmentAllows([Create,Update,Approve,Full,Develop]) = False because:Undefined C#
                    Dnn.EnvPrm[f0] - UserIsAnonymous() UserId:-1= True C#
                Dnn.EnvPrm[f0] - UserIsSystemAdmin() = False C#
                Dnn.EnvPrm[f0] - CurrentZoneMatchesSiteZone() = True C#
                Dnn.EnvPrm[f0] - UserIsContentAdmin() = False C#
                Dnn.EnvPrm[f0] - UserIsModuleAdmin() = False C#
                Dnn.EnvPrm[f0] - UserIsModuleEditor() = False C#
                Dnn.EnvPrm[f0] - Log Warning: Wrapper already closed from previous call
            Api.Dnn12[98]AdamCo[82]Adm.TrnUpl[f1]Adm.CtxTT[fe]Sec.MPTyps[ee]App.PrmChk[44] - PermissionList() = found 2 items C#
            Api.Dnn12[98]AdamCo[82]Adm.TrnUpl[f1]Adm.CtxTT[fe]Sec.MPTyps[ee]App.PrmChk[44] - PermissionsAllow([Create, Update, Approve, Full, Develop]) for 2 permission items= False C#
                App.PrmChk[44] - PermissionAllows(cuafv) = False C#
                    App.PrmChk[44] - VerifyConditionApplies() = False no-match: false C#
                        App.PrmChk[44] - condition:, identity:5 C#
                        Dnn.EnvPrm[f0] - VerifyConditionOfEnvironment() = False unknown condition: false C#
                App.PrmChk[44] - PermissionAllows(cuafv) = False C#
                    App.PrmChk[44] - VerifyConditionApplies() = False no-match: false C#
                        App.PrmChk[44] - condition:, identity:7 C#
                        Dnn.EnvPrm[f0] - VerifyConditionOfEnvironment() = False unknown condition: false C#
        Dnn.TnScCk[fb] - adminSome:False, restricted:True C#
```

**Comment by tpperlman** [comment]
For some additional background, this API receives webhooks from Stripe, so it isn't running in a user context. We previously had an issue #2706 for SaveInAdam and the code and app permissions remain unchanged from when we were running 2SXC v13.1.

Perhaps permissions changed somewhere in subsequent releases?

**Comment by tpperlman** [comment]
We were able to stage the Stripe webhook on our local server and get a more detailed error response. It turns out that the error below wasn't being presented anywhere that we could find, but we were able to resolve:

"Permission denied. low-permission users may not access this - Features 'PublicEditForm' not enabled - see also https://r.2sxc.org/features"

Thank you for your time, we're going to close this issue.

**Comment by iJungleboy** [comment]
Glad to hear it "fixed itself" :) - thanks for the closure

**Comment by tpperlman** [comment]
Thank you @iJungleboy. It might be nice if error messages like the one above showed in the event log or insights so we can avoid opening tickets. In a production environment, it isn't always possible to step through code and see more detailed messages.

Happy Valentines Day!

**Comment by iJungleboy** [comment]
Absolutely agree - work in progress...

Happy Valentines to you too
