### ISSUE TITLE
Error when choose under edit the fieldtype like STRING

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#321]
New installation
DNN: 7.4.1
2SXC: 7.2.2

2Sexy Content
When I add a field string type at first I can't specify somewhere witch kind of string type it is (single-line text, multi-line text, wysiwyg-text). When I later-on under edit click on STRING (or another field-type) I get an error. In the log is the following info registered

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:ab466fd6-789b-4f3f-aaaa-a61c63a97e3a
AssemblyVersion:7.4.1
PortalId:0
UserId:1
TabId:111
RawUrl:/home/Aanvraag-templates/ctl/eavmanagement/mid/496/AppID/13?popUp=true&ManagementMode=NewItem&AttributeSetId=159&keyNumber=334&keyGuid=&AssignmentObjectTypeId=2&ReturnUrl=https%3a%2f%2fwww.perfocus.nl%2fhome%2fAanvraag-templates%2fctl%2feavmanagement%2fmid%2f4
Referrer:https://www.perfocus.nl/home/Aanvraag-templates/ctl/eavmanagement/mid/496/AppID/13?popUp=true&ManagementMode=ContentTypeFields&AttributeSetId=272
UserAgent:Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.157 Safari/537.36
ExceptionHash:YDNxl/HZtcira260TrEv1w==
Message:Nullable object must have a value.
StackTrace:
InnerMessage:Nullable object must have a value.
InnerStackTrace:
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at ToSic.Eav.ManagementUI.EavManagement.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at System.Web.UI.ControlCollection.Add(Control child)
   at ToSic.SexyContent.EAVManagement.Page_Load(Object sender, EventArgs e)
   at System.Web.Util.CalliEventHandlerDelegateProxy.Callback(Object sender, EventArgs e)
   at System.Web.UI.Control.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by iJungleboy** [comment]
This is same as #258 will close this.
