### ISSUE TITLE
Can't add module in DNN 8.0 CTP3 or CTP4

### ISSUE THREAD

**Issue by efficiondave** [2sic/2sxc#323]
I know the module isn't supported in a pre-release version of DNN but I thought I'd point out that while the module installs fine in DNN 8 CTP3 and CTP4, when you try to add either the Content or App module, nothing happens. Here's the error from the Error Log:

9/1/2015 11:04:05 AM
General Exception 
AbsoluteURL DefaultDataProvider DotNetNuke.Data.SqlDataProvider DotNetNuke 

AbsoluteURL:
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:504ae4e5-f85d-41c8-9604-bdd3bc68ce55

AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:

ExceptionHash:3cIH2GIfoLzETTQXa0qoCA==

Message:Error Creating BusinessControllerClass 'ToSic.SexyContent.SexyContent' of module(2sxc-app) id=(422) in tab(55) and portal(0)

StackTrace:

   at DotNetNuke.Services.Search.ModuleIndexer.ThrowLogError(ModuleInfo module, Exception ex)
InnerMessage:Exception has been thrown by the target of an invocation.
InnerStackTrace:
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at DotNetNuke.Services.Search.ModuleIndexer.GetModuleList(Int32 portalId)

Source:DotNetNuke
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: DEV2

**Comment by iJungleboy** [comment]
@efficiondave thanks for the feedback. We haven't tested it yet. 
Since we're refactoring a LOT right now (almost everything will be AngularJS and not require dnn-urls any more), we'll postpone the test till after that.

**Comment by iJungleboy** [comment]
@efficiondave could you help us and try out the new 7.3 beta with dnn 8? I would really appreciate it and I'm guessing most things will work. 
will close this for now.

**Comment by efficiondave** [comment]
I upgraded to 7.3 and tried to add the module and got the same error:

AbsoluteURL:

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:b707645d-f98b-474b-bd8a-2dc1dfaf81bb

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:KAQRTLVWgF7mCf1zB8iHoQ==

Message:Error Creating BusinessControllerClass 'ToSic.SexyContent.SexyContent' of module(2sxc) id=(452) in tab(89) and portal(0)

StackTrace:

   at DotNetNuke.Services.Search.ModuleIndexer.ThrowLogError(ModuleInfo module, Exception ex)

InnerMessage:Exception has been thrown by the target of an invocation.

InnerStackTrace:

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at System.Activator.CreateInstance(Type type)
   at DotNetNuke.Services.Search.ModuleIndexer.GetModuleList(Int32 portalId)

Source:DotNetNuke

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: DEV2

**Comment by iJungleboy** [comment]
The error seems to come from a moduleindexer. do you see this as a user or is this in the background? do you know what the "module indexer" is?
