### ISSUE TITLE
XML import issue

### ISSUE THREAD

**Issue by EzraM** [2sic/2sxc#329]
Fresh install of DNN 7.4.0
Install 2sxc 7.2.3
Create content type with three strings
Add sample values
Export content type as xml
Open exported xml file in text editor, change a string
Reimport content
(System says import was successful, string is unchanged)
(No error logged)

**Comment by iJungleboy** [comment]
May be related to #311 - will check

**Comment by iJungleboy** [comment]
@EzraM what export/import did you use, as this might be by design. 

The "technical" export/import is meant for various things, but it purposely does not modify existing data, as it's mainly used for update-style operations where it would be dangerous to everwrite changes to the existing system. 

So did you use the partial-export/import or the data-table export-import?

**Comment by EzraM** [comment]
Not sure I understand.

Here's the export content options:

![image](https://cloud.githubusercontent.com/assets/1278543/10499589/f551daca-7296-11e5-81d3-24db49003273.png)

You get an XML file. TestField is a string. I change the value to a different string.
```
<SexyContentData>
  <Entity Type="Test">
    <Guid>1d659f36-105a-4774-aea3-3c9bfd0506a8</Guid>
    <Language></Language>
    <TestField>Check one two</TestField>
  </Entity>
</SexyContentData>
```

Then, reimport:

![image](https://cloud.githubusercontent.com/assets/1278543/10499622/3630937e-7297-11e5-8550-d3fc2b413f3d.png)

Today, I seem to be getting this error when I try, which is strange because I do not remember getting it before.

```
2015-10-14 17:12:04,241 [LCNU419BS3M][Thread:5][FATAL] DotNetNuke.Framework.PageBase - An error has occurred while loading page.
System.Exception: have too many to keep, don't know what to do, abort...
   at ToSic.Eav.EavContext.UpdateEntityFromImportModel(Entity currentEntity, Dictionary`2 newValuesImport, List`1 updateLog, List`1 attributeList, List`1 currentValues, Boolean preserveUndefinedValues)
   at ToSic.Eav.EavContext.UpdateEntity(Int32 entityId, IDictionary newValues, Boolean autoSave, ICollection`1 dimensionIds, Boolean masterRecord, List`1 updateLog, Boolean preserveUndefinedValues, Boolean isPublished)
   at ToSic.Eav.Import.Import.PersistOneImportEntity(ImportEntity importEntity)
   at ToSic.Eav.Import.Import.RunImport(IEnumerable`1 newAttributeSets, IEnumerable`1 newEntities, Boolean commitTransaction, Boolean purgeCache)
   at ToSic.Eav.ImportExport.Refactoring.XmlImport.PersistImportToRepository(String userId)
   at ToSic.SexyContent.Administration.DataImport.OnImportDataClick(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

This does seem like an update use case. Is there a different place I could export from?

**Comment by iJungleboy** [comment]
I have a guess but I'm not 100% sure. But it would be a bug. Could you mail me your app and the export/import file?

**Comment by EzraM** [comment]
What do you mean by app? We're using 2sxc Content, not Apps, at this time.
Do you want a DB dump and zip of the DNN application?
Attached is the editable export of the Test content type, `2sxc Test Data 20151019100826.xml`.
Also attached is a partial export of the 2sxc data, `SexyContent-Export.xml`

The partial export has a suspicious looking set of duplicate values.

    <Value Key="TestField" Value="Test test test" Type="String" />
    <Value Key="TestField" Value="Test 1 2" Type="String" />

**Comment by iJungleboy** [comment]
@EzraM thanks. This does look strange - like it has the same value-item stored multiple times. We have implemented a clean-up in the newest beta of 2sxc 7.3.3 (download in 5 minutes). Could you give it a try?

**Comment by EzraM** [comment]
Tried it, worked great. Love the new UI, well done.

**Comment by iJungleboy** [comment]
thx :) 
always love positive feedback
