### ISSUE TITLE
Sequence contains more than one matching element when closing a form

### ISSUE THREAD

**Issue by enfJoao** [2sic/2sxc#3436]
### I'm submitting a
[x] bug report

### ...about
[x] Content Types or data management

### Current Behavior / Expected Behavior
When adding an item (entity data type) and trying to save a form, I get the error: "sequence contains more than one matching element".
This only happens when adding one specific item.

### Instructions to Reproduce the Problem
Can't reproduce it.

### Your environment

* **2sxc version(s):** 17.10
* **DNN:** 9.13.03
Log:
```
AbsoluteURL:/api/2sxc/cms/edit/save
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:6319680b-ce81-49fa-9322-bd9ba31e443d
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:qRIbaAlNeoNmkV6hrIMY8pavp8Q=
Message:Sequence contains more than one matching element
StackTrace:
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.<>c.<GetMostCurrentDbEntities>b__16_2(IGrouping`2 g) in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_read.cs:line 89
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.GetMostCurrentDbEntities(Guid[] entityGuids) in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_read.cs:line 85
   at ToSic.Eav.Repository.Efc.Parts.DbRelationship.<>c__DisplayClass7_0.<ImportRelationshipQueueAndSave>b__5() in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\Parts\DbRelationship.cs:line 128
   at ToSic.Eav.Repository.Efc.DbDataController.DoInTransaction(Action action) in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 268
   at ToSic.Eav.Repository.Efc.Parts.DbRelationship.<ImportRelationshipQueueAndSave>b__7_0(ILogCall l) in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\Parts\DbRelationship.cs:line 162
   at ToSic.Lib.Logging.ILog_Actions.DoLogCall(ILog log, String parameters, Action`1 action, Boolean timer, Boolean enabled, String message, String cPath, String cName, Int32 cLine) in C:\Projects\2sxc\eav-server\ToSic.Lib.Core\Logging\Log\ILog_Actions.cs:line 120
   at ToSic.Eav.Repository.Efc.Parts.DbRelationship.ImportRelationshipQueueAndSave() in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\Parts\DbRelationship.cs:line 100
   at ToSic.Eav.Repository.Efc.Parts.DbRelationship.<>c__DisplayClass1_0.<DoWhileQueueingRelationships>b__0() in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\Parts\DbRelationship.cs:line 20
   at ToSic.Lib.Logging.ILog_Actions.Do(ILog log, String parameters, Action action, Boolean timer, Boolean enabled, String message, String cPath, String cName, Int32 cLine) in C:\Projects\2sxc\eav-server\ToSic.Lib.Core\Logging\Log\ILog_Actions.cs:line 67
   at ToSic.Eav.Repository.Efc.Parts.DbRelationship.DoWhileQueueingRelationships(Action action) in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\Parts\DbRelationship.cs:line 23
   at ToSic.Eav.Repository.Efc.Parts.DbVersioning.DoAndSaveHistoryQueue(Action action) in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\Parts\DbVersioning.cs:line 57
   at ToSic.Eav.Repository.Efc.DbDataController.DoInTransaction(Action action) in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 268
   at ToSic.Eav.Repository.Efc.Parts.DbEntity.SaveEntity(List`1 entities, SaveOptions saveOptions) in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\Parts\DbEntity_SaveMany.cs:line 23
   at ToSic.Eav.Repository.Efc.DbDataController.Save(List`1 entities, SaveOptions saveOptions) in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 312
   at ToSic.Eav.Apps.Internal.Work.WorkEntitySave.<>c__DisplayClass8_1.<Save>b__4() in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\Eav.Apps.Internal\Work\Entity\WorkEntitySave.cs:line 86
   at ToSic.Eav.Repository.Efc.DbDataController.DoButSkipAppCachePurge(Action action) in C:\Projects\2sxc\eav-server\ToSic.Eav.Repository.Efc\DbDataController.cs:line 285
   at ToSic.Eav.Apps.Internal.Work.WorkEntitySave.<>c__DisplayClass8_0.<Save>g__InnerSaveInLock|1() in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\Eav.Apps.Internal\Work\Entity\WorkEntitySave.cs:line 89
   at ToSic.Eav.Apps.Internal.Work.WorkEntitySave.<>c__DisplayClass8_0.<Save>b__0() in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\Eav.Apps.Internal\Work\Entity\WorkEntitySave.cs:line 56
   at ToSic.Eav.Apps.State.AppState.DoInLock(ILog parentLog, Action transaction) in C:\Projects\2sxc\eav-server\ToSic.Eav.Core\Apps\State\AppState\AppState_Transaction.cs:line 21
   at ToSic.Eav.Apps.Internal.Work.WorkEntitySave.Save(List`1 entities, SaveOptions saveOptions) in C:\Projects\2sxc\eav-server\ToSic.Eav.Apps\Eav.Apps.Internal\Work\Entity\WorkEntitySave.cs:line 57
   at ToSic.Eav.WebApi.SaveHelpers.SaveEntities.UpdateGuidAndPublishedAndSaveMany(IAppWorkCtx appCtx, List`1 itemsToImport, Boolean enforceDraft) in C:\Projects\2sxc\eav-server\ToSic.Eav.WebApi\SaveHelpers\SaveEntities.cs:line 38
   at ToSic.Sxc.Backend.Cms.EditSaveBackend.DoSave(WorkEntities workEntities, List`1 items, Boolean forceSaveAsDraft) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc.WebApi\Backend\Cms\Edit\EditSaveBackend.cs:line 142
   at ToSic.Sxc.Backend.SaveHelpers.SxcPagePublishing.<>c__DisplayClass4_1.<SaveInPagePublishing>g__SaveAndSaveGroupsInnerCall|1(Func`2 call, Boolean forceSaveAsDraft) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc.WebApi\Backend\SaveHelpers\SxcPagePublishing.cs:line 49
   at ToSic.Sxc.Backend.SaveHelpers.SxcPagePublishing.<>c__DisplayClass4_1.<SaveInPagePublishing>b__3(VersioningActionInfo args) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc.WebApi\Backend\SaveHelpers\SxcPagePublishing.cs:line 62
   at ToSic.Sxc.Dnn.Cms.DnnPagePublishing.DoInsidePublishing(IContextOfSite context, Action`1 action) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.Core\Dnn\Cms\DnnPagePublishing.cs:line 52
   at ToSic.Sxc.Backend.SaveHelpers.SxcPagePublishing.<>c__DisplayClass4_0.<SaveInPagePublishing>b__0() in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc.WebApi\Backend\SaveHelpers\SxcPagePublishing.cs:line 61
   at ToSic.Lib.Logging.ILog_Func.Func[TResult](ILog log, Func`1 func, Boolean timer, Boolean enabled, String message, String cPath, String cName, Int32 cLine) in C:\Projects\2sxc\eav-server\ToSic.Lib.Core\Logging\Log\ILog_Func.cs:line 33
   at ToSic.Sxc.Backend.SaveHelpers.SxcPagePublishing.SaveInPagePublishing(IBlock blockOrNull, Int32 appId, List`1 items, Boolean partOfPage, Func`2 internalSaveMethod, IMultiPermissionCheck permCheck) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc.WebApi\Backend\SaveHelpers\SxcPagePublishing.cs:line 33
   at ToSic.Sxc.Backend.Cms.EditSaveBackend.Save(EditDto package, Boolean partOfPage) in C:\Projects\2sxc\2sxc\Src\Sxc\ToSic.Sxc.WebApi\Backend\Cms\Edit\EditSaveBackend.cs:line 126
   at ToSic.Sxc.Dnn.Backend.Cms.EditController.Save(EditDto package, Int32 appId, Boolean partOfPage) in C:\Projects\2sxc\2sxc\Src\Dnn\ToSic.Sxc.Dnn.WebApi\Dnn\Backend\Cms\EditController.cs:line 35
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass6_2.<GetExecutor>b__2(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Web.Http.Filters.ActionFilterAttribute.<CallOnActionExecutedAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.ActionFilterAttribute.<ExecuteActionFilterAsyncCore>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
InnerMessage:

InnerStackTrace:

Source:System.Core

FileName:

FileLineNumber:0

FileColumnNumber:0
```

**Comment by iJungleboy** [comment]
Apparently something is wrong in a very specific situation. 

The provided description doesn't contain anything to go on.

In this form we cannot do anything at all - so I must simply close this again. 

Pls find a way to provide more info - screenshots, setup, which value is probably causing the problem etc. then I can reopen.

**Comment by 6TELOIV** [comment]
This mistery issue is striking us; only on one content item. Will try and see if I can recreate or get useful logs.

**Comment by 6TELOIV** [comment]
Here is our insights log for the error:

[Sequence contains more than one matching element.htm.txt](https://github.com/user-attachments/files/18564318/Sequence.contains.more.than.one.matching.element.htm.txt) (changed to .txt for github upload; rename to htm to view)

**Comment by 6TELOIV** [comment]
I'm not sure at all what is going on, but based on error (Sequence contains more than one matching element), I think what's happening is a data race condition on saving.

Our users have been having some latency issues when saving, and will sometimes hit save multiple times while the original request(s) are processing. Maybe there is an issue in the 2sxc saving code that is causing the same entity to be written to the DB multiple times, making the save fail?

**Comment by 6TELOIV** [comment]
some more wishy washy, maybe helpful, maybe not, information:

To fix this, we had to delete the DNN module from the page, and make a new one, using a new content item.

**Comment by 6TELOIV** [comment]
However, with the same content (except for re-creating inner-content apps, but populating them with their existing data), it works.
