### ISSUE TITLE
/api/2sxc/app/auto/query/System.EntityPicker/Default gives an error after closing dialogue after saving

### ISSUE THREAD

**Issue by BondForWebSolutions** [2sic/2sxc#3442]
### I'm submitting a
[x] bug report 

### ...about
[x] edit experience / UI
[x] APIs like REST

### Current Behavior / Expected Behavior
This issue happens in the News app (but other apps might have the same issues) after upgrading to 2sxc 17.9.
I've tried this on multiple dnn installations and they all had this behaviour.
I tried this on an installation with 2sxc 17.9 with a clean install (so no upgrade) and it did not give the issue there.
So this might be related to upgrades only...

When editing or adding a newsarticle you can select related entities, like categories or authors so this will call the entitypicket api.
So, you see a call to something like:

https://[website]/api/2sxc/app/auto/query/System.EntityPicker/Default?typeNames=Category&appId=10&itemIds=&$select=Title,Id,Guid

And this works fine...
However, when I click on the save button it will first call something like:

https://[website]/api/2sxc/cms/edit/save?appId=10&partOfPage=true

And then it will also call the entitypicker api again for the category, and the authors 
However when the save api is done, it will close the popup and end the connection before the entitypicker api can give the response.
So this will give some errors (in F12 developer tools, and in de DNN eventlog). 

In F12 developer tools you see something like:
![image](https://github.com/2sic/2sxc/assets/68665410/06addfb6-16cb-41e9-9abe-4fd0d84430e2)

And in the DNN eventlog it will show about 10 errors relating to this issue.
Saying something like:

**AbsoluteURL:**/api/2sxc/app/auto/query/System.EntityPicker/Default
**DefaultDataProvider:**DotNetNuke.Data.SqlDataProvider, DotNetNuke
**ExceptionGUID:**5b2666d1-76f4-4cca-aafa-7719e5d5314c
**AssemblyVersion:**
**PortalId:**-1
**UserId:**-1
**TabId:**-1
**RawUrl:**
**Referrer:**
**UserAgent:**
**ExceptionHash:**QNQ1dFJLAV3lVWxfsQiVlPXM8bk=
**Message:**The operation was canceled.
**StackTrace:**
   at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Net.Http.HttpContentExtensions.<ReadAsAsyncCore>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.ModelBinding.FormatterParameterBinding.<ExecuteBindingAsyncCore>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.HttpActionBinding.<ExecuteBindingAsyncCore>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.<TraceBeginEndAsyncCore>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.<ExecuteAuthorizationFilterAsyncCore>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.<ExecuteAsync>d__6.MoveNext()
**InnerMessage:**
**InnerStackTrace:**
**Source:**mscorlib
**FileName:**
**FileLineNumber:**0
**FileColumnNumber:**0

**Comment by iJungleboy** [comment]
thx, we'll look into this.

We've been doing a LOT of work (more than a week) on the pickers, so my guess is it will be automatically resolved in the next release.

**Comment by iJungleboy** [comment]
believe fixed in v18
