### ISSUE TITLE
Page Load Exception when editing settings of a field.

### ISSUE THREAD

**Issue by hbuchel** [2sic/2sxc#375]
On a new install, when I click on "String" to edit the settings of a string field I've created, I get a page load exception (have also tried with a hyperlink field and the hyperlink settings page also throws an exception).

This is the stack trace for the error I get:

```
InnerMessage:Nullable object must have a value.
InnerStackTrace:
   at System.Nullable`1.get_Value()
   at ToSic.Eav.ManagementUI.EavManagement.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at ToSic.SexyContent.EAVManagement.Page_Load(Object sender, EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

Also, clicking on "General" for a field returns an empty page like this screenshot, instead of the usual general settings for the field: http://cl.ly/image/1l1G0J2J3H2k

Any idea why I'm having those errors?

I'm using 7.2.3 of the module, on DNN 07.04.01

**Comment by hbuchel** [comment]
Ah, I see now that it is probably related to this. https://github.com/2sic/2sxc/issues/258
