### ISSUE TITLE
After adding a field and setting a fieldname an exception occurred

### ISSUE THREAD

**Issue by KosVos37** [2sic/2sxc#433]
It is reproducable. It happens if the Published property is set to false while saving the field change

9-11-2015 15:20:29
Page Load Exception 
michel 
Patient Lifting Solutions 
 AbsoluteURL /Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataProvi 
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:cd5c307f-2989-4bf0-998c-8183bf93ee8f
AssemblyVersion:7.4.2
PortalId:2
UserId:4
TabId:183
RawUrl:/Home/ctl/eavmanagement/mid/873/AppID/21?popUp=true&ManagementMode=ContentTypeFields&AttributeSetId=744
Referrer:http://pls.nl.me/Home/ctl/eavmanagement/mid/873/AppId/21?popUp=true
UserAgent:Mozilla/5.0 (Windows NT 10.0; WOW64; rv:42.0) Gecko/20100101 Firefox/42.0
ExceptionHash:xnL7fg7ZeHtqFs7t8kIFnA==
Message:Exception has been thrown by the target of an invocation.
StackTrace:
InnerMessage:Exception has been thrown by the target of an invocation.
InnerStackTrace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Web.UI.WebControls.ObjectDataSourceView.InvokeMethod(ObjectDataSourceMethod method, Boolean disposeInstance, Object& instance)
   at System.Web.UI.WebControls.ObjectDataSourceView.ExecuteSelect(DataSourceSelectArguments arguments)
   at System.Web.UI.DataSourceView.Select(DataSourceSelectArguments arguments, DataSourceViewSelectCallback callback)
   at System.Web.UI.WebControls.BaseDataBoundControl.EnsureDataBound()
   at System.Web.UI.WebControls.CompositeDataBoundControl.CreateChildControls()
   at System.Web.UI.Control.EnsureChildControls()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Control.PreRenderRecursiveInternal()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:

**Comment by iJungleboy** [comment]
Thanks - sounds like a bug, but in a strange use case. To decide on priority, can you tell me why you would want to do this?

**Comment by KosVos37** [comment]
Hi iJungleboy,

 

I wanted to avoid other designers to use this field until I configured the popup that would be connected to this field. The critical error kept coming so I had to remove it from the DB by deleting it from the ToSIC_EAV_AttributesInSets. Probably not the best way to do it but it worked (at least, it got away the critical error). So, it is not a big issue anymore. I will not check that radiobutton anymore…

 

Thanks,

Marcel

 

 

 

Van: iJungleboy [mailto:notifications@github.com] 
Verzonden: dinsdag 10 november 2015 16:55
Aan: 2sic/2sxc <2sxc@noreply.github.com>
CC: KosVos37 <kosvos37@martan.nl>
Onderwerp: Re: [2sxc] After adding a field and setting a fieldname an exception occurred (#433)

 

Thanks - sounds like a bug, but in a strange use case. To decide on priority, can you tell me why you would want to do this?

**Comment by iJungleboy** [comment]
This wouldn't achieve this. I'll close fir now, thx
