### ISSUE TITLE
When i delete a contenttype in the data tab (in 2sxc8) the views tab is not accessible anymore

### ISSUE THREAD

**Issue by Frankwalraven** [2sic/2sxc#449]
Occurs in 2sxc 7 and 8
When I delete an content-type in the data tab in the admin pop-up of 2sxc, and the content type is used in a template in the views tab (8) in the admin pop-up, the views tab is not accessible anhymore. In 7 the module will crash in 8 you get an status 500 error and no templates are visible in the tab.
You have to restore a backup of the site to make the views tab accesible again :-(

When you try to delete in the views tab a template in version 8 you get the folowing error
Had an error talking to the server (status 500). Message: An error has occurred.
and nothing is deleted

In 2sxc 7.2.3 there is no error, only it looks like the module is crashed. When you go to the log you find the following error
Message:Entity has 10 Child-Relationships to Entities: 476, 555, 583, 589, 599, 629, 632, 637, 639, 643. Entity has 1 assigned Field-Property-Entities: 1258.
StackTrace:
  at ToSic.SexyContent.Templates.DeleteTemplate(Int32 templateId)
   at ToSic.SexyContent.ManageTemplates.grdTemplates_DeleteCommand(Object sender, GridCommandEventArgs e)
   at Telerik.Web.UI.RadGrid.OnDeleteCommand(GridCommandEventArgs e)
   at Telerik.Web.UI.RadGrid.CallOnDeleteCommand(GridCommandEventArgs e)
   at Telerik.Web.UI.GridCommandEventArgs.ExecuteCommand(Object source)
   at Telerik.Web.UI.RadGrid.OnBubbleEvent(Object source, EventArgs e)
   at System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args)
   at Telerik.Web.UI.GridItem.OnBubbleEvent(Object source, EventArgs e)
   at System.Web.UI.Control.RaiseBubbleEvent(Object source, EventArgs args)
   at System.Web.UI.WebControls.ImageButton.OnCommand(CommandEventArgs e)
   at System.Web.UI.WebControls.ImageButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.WebControls.ImageButton.System.Web.UI.IPostBackEventHandler.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(IPostBackEventHandler sourceControl, String eventArgument)
   at System.Web.UI.Page.RaisePostBackEvent(NameValueCollection postData)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by tpperlman** [comment]
I upvote this bug for fixing because it leads to zombie entries in the View tab. We can't even delete a view once the content type has been removed. These errors should also be clearer in the javascript alerts.

**Comment by iJungleboy** [comment]
Thx. Note also that @thedeadlybulb had a workaround at the end of issue #292

**Comment by iJungleboy** [comment]
Technically the best solution is a fairly far-reaching re-architecture which we'll have to do at some point. To be able to live with it I created a separate quick-fix issue #658 which will won't really fix much, but ensure that the dialogs don't break when this situation happens.

**Comment by iJungleboy** [comment]
Ok, implemented a quick fix, now deleted content-types won't kill the view. Will close this for now.
