### ISSUE TITLE
Export App with Content Groups throws exception

### ISSUE THREAD

**Issue by SCullman** [2sic/2sxc#612]
Message:Object reference not set to an instance of an object.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at ToSic.Eav.Data.Value`1.<>c.b__5_0(IEntity e)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.String.Join[T](String separator, IEnumerable`1 values)
   at ToSic.Eav.Data.Value`1.get_Serialized()
   at ToSic.Eav.ImportExport.XmlExport.GetValueXElement(String attributeStaticname, IValue value, String attributeType)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at System.Xml.Linq.XContainer.AddContentSkipNotify(Object content)
   at ToSic.Eav.ImportExport.XmlExport.GetEntityXElement(IEntity entity)
   at ToSic.Eav.ImportExport.XmlExport.GetEntityXElement(Int32 entityId)
   at ToSic.SexyContent.ImportExport.XmlExporter.GetEntityXElement(Entity e)
   at ToSic.SexyContent.ImportExport.XmlExporter.get_ExportXDocument()
   at ToSic.SexyContent.ImportExport.XmlExporter.GenerateNiceXml()
   at ToSic.SexyContent.ImportExport.ZipExport.ExportApp(Boolean includeContentGroups, Boolean resetAppGuid)
   at ToSic.SexyContent.Administration.Apps.AppExport.btnExportApp_OnClick(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.OnClick(EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

**Comment by iJungleboy** [comment]
Thanks, I have a guess - will check.

**Comment by iJungleboy** [comment]
was able to reproduce...
