### ISSUE TITLE
Installing 2SXC on DNN Install Using Existing ImageResizer.dll Breaks Site

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#635]
I just tried to install 2SXC v8.01.03 for the first time on my development server. I develop custom modules and had one that uses ImageResizer.dll V3.4.3. It appears that your install overwrites the existing one, which in turn takes down the site.

Here are some logs that may help:

2/11/2016 1:09:31 PM
Page Load Exception 
tpperlman 
DNN DEV 
 AbsoluteURL /Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataProvi 
2/11/2016 1:09:31 PM
Page Load Exception 
tpperlman 
DNN DEV 
 AbsoluteURL /Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataProvi 

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:b9fe8785-b361-4dda-ba92-83d1b8f595dc

AssemblyVersion:7.4.1

PortalId:0

UserId:1

TabId:55

RawUrl:/Default.aspx?tabid=55&error=Exception+has+been+thrown+by+the+target+of+an+invocation.&content=0

Referrer:http://dnndev.me/Default.aspx?tabid=55&error=Exception+has+been+thrown+by+the+target+of+an+invocation.&content=0

UserAgent:Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0

ExceptionHash:/Zea2aqMn+nwyIobPDBG3g==

Message:Exception has been thrown by the target of an invocation.

StackTrace:

InnerMessage:Exception has been thrown by the target of an invocation.

InnerStackTrace:

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at DotNetNuke.Framework.ServiceLocator`2.InitInstance()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at DotNetNuke.Framework.ServiceLocator`2.get_Instance()
   at DotNetNuke.UI.ControlPanels.ControlBar.LoadCustomMenuItems() in c:\...\dnn-dev\admin\ControlPanel\ControlBar.ascx.cs:line 198
   at DotNetNuke.UI.ControlPanels.ControlBar.OnInit(EventArgs e) in c:\...\dnn-dev\admin\ControlPanel\ControlBar.ascx.cs:line 121
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.UI.Skins.Skin.InjectControlPanel()
   at DotNetNuke.UI.Skins.Skin.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.Framework.DefaultPage.OnInit(EventArgs e) in c:\...\dnn-dev\Default.aspx.cs:line 755
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

[L]Server Name: HOME
2/11/2016 1:09:31 PM
Page Load Exception 
tpperlman 
DNN DEV 
 AbsoluteURL /Default.aspx DefaultDataProvider DotNetNuke.Data.SqlDataProvi 

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:a4b2cf56-89d3-4fd4-bc98-b76246a3bb16

AssemblyVersion:7.4.1

PortalId:0

UserId:1

TabId:55

RawUrl:/Default.aspx

Referrer:http://dnndev.me/Default.aspx?tabid=55&error=Exception+has+been+thrown+by+the+target+of+an+invocation.&content=0

UserAgent:Mozilla/5.0 (Windows NT 10.0; WOW64; rv:43.0) Gecko/20100101 Firefox/43.0

ExceptionHash:/XgNqRG5aSGkjlEytlB9cw==

Message:Exception has been thrown by the target of an invocation.

StackTrace:

InnerMessage:Exception has been thrown by the target of an invocation.

InnerStackTrace:

   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance[T]()
   at DotNetNuke.Framework.ServiceLocator`2.InitInstance()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at DotNetNuke.Framework.ServiceLocator`2.get_Instance()
   at DotNetNuke.UI.ControlPanels.ControlBar.LoadCustomMenuItems() in c:\...\dnn-dev\admin\ControlPanel\ControlBar.ascx.cs:line 198
   at DotNetNuke.UI.ControlPanels.ControlBar.OnInit(EventArgs e) in c:\...\dnn-dev\admin\ControlPanel\ControlBar.ascx.cs:line 121
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.UI.Skins.Skin.InjectControlPanel()
   at DotNetNuke.UI.Skins.Skin.OnInit(EventArgs e)
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Control.AddedControl(Control control, Int32 index)
   at DotNetNuke.Framework.DefaultPage.OnInit(EventArgs e) in c:\...\dnn-dev\Default.aspx.cs:line 755
   at System.Web.UI.Control.InitRecursive(Control namingContainer)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

[L]Server Name: HOME

**Comment by tpperlman** [comment]
Ended up uninstalling and reinstalling my custom app, updating the imageresizer.dll version and now it all works.
