### ISSUE TITLE
App export does not work

### ISSUE THREAD

**Issue by raphael-m** [2sic/2sxc#655]
Exception when exporting apps. Event log:

```
Message:The directory is not empty.
StackTrace:
InnerMessage:The directory is not empty.
InnerStackTrace:
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at ToSic.SexyContent.ImportExport.ZipExport.ExportApp(Boolean includeContentGroups, Boolean resetAppGuid)
   at ToSic.SexyContent.Administration.Apps.AppExport.btnExportApp_OnClick(Object sender, EventArgs e)
   at System.Web.UI.WebControls.LinkButton.RaisePostBackEvent(String eventArgument)
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)
```

**Comment by iJungleboy** [comment]
Can't reproduce - I'm able to export apps. Will close, pls re-open when you have clearer details.
