### ISSUE TITLE
Error in blueimp Gallery

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#657]
The App for blueimp Gallery has a bug. I installed it fresh, and when I add it to a page I receive the error below. It appears that App.Settings.BasePath is not a valid object?

Affected lines are:

21:                var basePath = (string)App.Settings.BasePath;
22:                var path = basePath + "/" + Dnn.Module.ModuleID.ToString();

System.NullReferenceException: Object reference not set to an instance of an object.

   at ToSic.SexyContent.Razor.SexyContentWebPage.get_App()
   at ASP._Page_Portals_0_2sxc_blueimp_Gallery__GalleryHelpers_cshtml.get_Folder() in c:\Users\Phil\documents\bigideas\web development\dotnetnuke\dnn-dev\Portals\0\2sxc\blueimp Gallery\_GalleryHelpers.cshtml:line 21
   at ASP._Page_Portals_0_2sxc_blueimp_Gallery__Gallery_cshtml.Execute() in c:\Users\Phil\documents\bigideas\web development\dotnetnuke\dnn-dev\Portals\0\2sxc\blueimp Gallery\_Gallery.cshtml:line 22
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at ToSic.SexyContent.Engines.RazorEngine.RenderTemplate()
   at ToSic.SexyContent.Engines.EngineBase.Render()
   at ToSic.SexyContent.SexyViewContentOrApp.ProcessView(PlaceHolder phOutput, Panel pnlError, Panel pnlMessage)

**Comment by iJungleboy** [comment]
Please review your error again - the two lines mentioned seem to be from different cshtml files.

**Comment by tpperlman** [comment]
Oops, yes.. thank you. Here is the correction to the affected lines:

**_GalleryHelpers.cshtml**

21:    var basePath = (string)App.Settings.BasePath;

**_Gallery.cshtml**
22:    @RenderPage("_UploadHelper.cshtml", Helpers.Folder, App.Settings.AllowedExtensions.Split(','), int.Parse(App.Settings.MaxFileSizeMB))

**Comment by iJungleboy** [comment]
Just to be sure - could you check the app-setting for base-path and see what you have in there? This is a value you can add yourself into the app-settings.

**Comment by tpperlman** [comment]
The base-path in the app's settings is "Galleries/blueimp".

I installed the app from the Zip archive using the App Import feature, and it installed it into the /Portals/0/2sxc/blueimp Gallery folder (notice the space before 'Gallery').

Looking at the App.xml file, I see this entity on line 629:

`      <Value Key="Folder" Value="blueimp Gallery" Type="String">`
`        <Dimension DimensionID="14" ReadOnly="false" />`
`      </Value>`

...and the base path is set in this entity starting on line 646...

`      <Value Key="BasePath" Value="Galleries/blueimp" Type="String">`
`        <Dimension DimensionID="14" ReadOnly="false" />`
`      </Value>`

Is there a path problem on the base install?

**Comment by iJungleboy** [comment]
just some background infos: these are two separate folders

1. the app-folder where the program is installed is in 2sxc
2. the other folder is the gallery-pictures folder

my guess is that you don't have the galleries/blueimp folder or something. 

BTW: i'm reworking blueimp to use the new ADAM features, which makes everything much, much easier. Should have a new version out by Monday or so, so maybe you don't want to invest time any more :)

**Comment by iJungleboy** [comment]
Note: i prepared everything and will publish a new 2sxc and a new blueimp tomorrow. 

So solution 1 is to download this, otherwise it most likely is a setting on your app-settings.
