### ISSUE TITLE
2SXC 8.3.4 - Export / Import App

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#737]
I wrote an app, and exported it from the portal using the standard options (did not tick the two boxes on the export screen). The app has one sample content item, a CSHTML template, and one image.

I created a new child portal on my development site to test the import and ran into a number of errors. I'll walk through them one by one:

1. I added a new APP module to the page.

2. In the "Choose App" drop-down, I selected "get more apps"

3. I clicked on the "browse" button to choose my exported app's ZIP file and clicked upload:

![capture1](https://cloud.githubusercontent.com/assets/1871915/13760719/e5bdc48e-ea0a-11e5-9916-d45f50ef7f5d.JPG)

This message appears, but clicking on the "close" button does nothing, so I have to click the close button on the top right of the modal window.

The error log shows this:
```
AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:c00c3bb5-233e-4b80-b980-249b4daaf21f
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:Uq6U5nvSJwnQrAigIuIbaw==
Message:The underlying system threw an exception. The file has not been added.
StackTrace:
   at DotNetNuke.Services.FileSystem.FileManager.AddFile(IFolderInfo folder, String fileName, Stream fileContent, Boolean overwrite, Boolean checkPermissions, Boolean ignoreWhiteList, String contentType, Int32 createdByUserID)
   at DotNetNuke.Services.FileSystem.FileManager.AddFile(IFolderInfo folder, String fileName, Stream fileContent, Boolean overwrite)
   at ToSic.SexyContent.ImportExport.ZipImport.CopyAllFilesDnnPortal(String sourceFolder, String destinationFolder, Boolean overwriteFiles, List`1 messages) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\ZipImport.cs:line 271
InnerMessage:Could not find a part of the path 'C:\Users\Phil\Documents\BIGideas\Web Development\DotNetNuke\DNN-DEV\Portals\1\adam\BIGideas_Mosaic\6C46UJYifkiEufJVWATTLQ\Image\SampleImage.jpg'.
InnerStackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at DotNetNuke.Services.FileSystem.Internal.FileWrapper.Create(String path)
   at DotNetNuke.Services.FileSystem.StandardFolderProvider.UpdateFile(IFolderInfo folder, String fileName, Stream content)
   at DotNetNuke.Services.FileSystem.FileManager.AddFile(IFolderInfo folder, String fileName, Stream fileContent, Boolean overwrite, Boolean checkPermissions, Boolean ignoreWhiteList, String contentType, Int32 createdByUserID)
Source:DotNetNuke
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: HOME

...and this...

AbsoluteURL:/Default.aspx
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:d0ab541a-e141-4a63-956c-de822acfc8e5
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:YZSpxhSQ6ygACuID8fERMQ==
Message:The underlying system threw an exception. The file has not been added.
StackTrace:
   at DotNetNuke.Services.FileSystem.FileManager.AddFile(IFolderInfo folder, String fileName, Stream fileContent, Boolean overwrite, Boolean checkPermissions, Boolean ignoreWhiteList, String contentType, Int32 createdByUserID)
   at DotNetNuke.Services.FileSystem.FileManager.AddFile(IFolderInfo folder, String fileName, Stream fileContent, Boolean overwrite)
   at ToSic.SexyContent.ImportExport.ZipImport.CopyAllFilesDnnPortal(String sourceFolder, String destinationFolder, Boolean overwriteFiles, List`1 messages) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\ZipImport.cs:line 271
InnerMessage:Could not find a part of the path 'C:\Users\Phil\Documents\BIGideas\Web Development\DotNetNuke\DNN-DEV\Portals\1\adam\BIGideas_Mosaic\yS9cMGKtoE6X6YOsmTeSrw\Image\Penguins.jpg'.
InnerStackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at DotNetNuke.Services.FileSystem.Internal.FileWrapper.Create(String path)
   at DotNetNuke.Services.FileSystem.StandardFolderProvider.UpdateFile(IFolderInfo folder, String fileName, Stream content)
   at DotNetNuke.Services.FileSystem.FileManager.AddFile(IFolderInfo folder, String fileName, Stream fileContent, Boolean overwrite, Boolean checkPermissions, Boolean ignoreWhiteList, String contentType, Int32 createdByUserID)
Source:DotNetNuke
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: HOME

4. After closing the previous modal window, I am brought back to the original page where I am prompted to "<Choose App>". I select the name of the app I just added and receive this error:

Message:Object reference not set to an instance of an object.
StackTrace:
   at DotNetNuke.Entities.Urls.AdvancedFriendlyUrlProvider.FriendlyUrlInternal(TabInfo tab, String path, String pageName, String portalAlias, PortalSettings portalSettings)
   at DotNetNuke.Entities.Urls.AdvancedFriendlyUrlProvider.FriendlyUrl(TabInfo tab, String path, String pageName, PortalSettings portalSettings)
   at DotNetNuke.Common.Globals.NavigateURL(Int32 tabID, Boolean isSuperTab, PortalSettings settings, String controlKey, String language, String pageName, String[] additionalParameters)
   at DotNetNuke.Common.Globals.NavigateURL(Int32 tabID, Boolean isSuperTab, PortalSettings settings, String controlKey, String language, String[] additionalParameters)
   at ToSic.SexyContent.EAV.Implementation.ValueConverter.SexyContentValueConverter.ResolvePageLink(Int32 id, String defaultValue) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\EAV\Implementation\ValueConverter\SexyContentValueConverter.cs:line 155
   at ToSic.SexyContent.EAV.Implementation.ValueConverter.SexyContentValueConverter.TryToResolveDnnCodeToLink(String value) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\EAV\Implementation\ValueConverter\SexyContentValueConverter.cs:line 97
   at ToSic.Eav.Data.Entity.GetBestValue(String attributeName, String[] dimensions, Boolean resolveHyperlinks) in C:\Projects\eav-server\ToSic.Eav.Core\Entity.cs:line 219
   at ToSic.SexyContent.DynamicEntity.GetEntityValue(String attributeName, Boolean& propertyNotFound) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\DynamicEntity.cs:line 106
   at ToSic.SexyContent.DynamicEntity.TryGetMember(GetMemberBinder binder, Object& result) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\DynamicEntity.cs:line 63
   at CallSite.Target(Closure , CallSite , Object )
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at ASP._Page_Portals_1_2sxc_BIGideas_Mosaic__Mosaic_cshtml.Execute() in c:\Users\Phil\documents\bigideas\web development\dotnetnuke\dnn-dev\Portals\1\2sxc\BIGideas_Mosaic\_Mosaic.cshtml:line 36
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at ToSic.SexyContent.Engines.RazorEngine.RenderTemplate() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 75
   at ToSic.SexyContent.Engines.EngineBase.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Engines\EngineBase.cs:line 89
   at ToSic.SexyContent.SexyViewContentOrApp.ProcessView(PlaceHolder phOutput, Panel pnlError) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SexyViewContentOrApp.cs:line 136

5. I go into Edit mode in DNN, and click on the Admin link for my app on the module's context menu and see this error in the log:

Message:Object reference not set to an instance of an object.
StackTrace:
   at DotNetNuke.Entities.Urls.AdvancedFriendlyUrlProvider.FriendlyUrlInternal(TabInfo tab, String path, String pageName, String portalAlias, PortalSettings portalSettings)
   at DotNetNuke.Entities.Urls.AdvancedFriendlyUrlProvider.FriendlyUrl(TabInfo tab, String path, String pageName, PortalSettings portalSettings)
   at DotNetNuke.Common.Globals.NavigateURL(Int32 tabID, Boolean isSuperTab, PortalSettings settings, String controlKey, String language, String pageName, String[] additionalParameters)
   at DotNetNuke.Common.Globals.NavigateURL(Int32 tabID, Boolean isSuperTab, PortalSettings settings, String controlKey, String language, String[] additionalParameters)
   at ToSic.SexyContent.EAV.Implementation.ValueConverter.SexyContentValueConverter.ResolvePageLink(Int32 id, String defaultValue) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\EAV\Implementation\ValueConverter\SexyContentValueConverter.cs:line 155
   at ToSic.SexyContent.EAV.Implementation.ValueConverter.SexyContentValueConverter.TryToResolveDnnCodeToLink(String value) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\EAV\Implementation\ValueConverter\SexyContentValueConverter.cs:line 97
   at ToSic.Eav.Data.Entity.GetBestValue(String attributeName, String[] dimensions, Boolean resolveHyperlinks) in C:\Projects\eav-server\ToSic.Eav.Core\Entity.cs:line 219
   at ToSic.SexyContent.DynamicEntity.GetEntityValue(String attributeName, Boolean& propertyNotFound) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\DynamicEntity.cs:line 106
   at ToSic.SexyContent.DynamicEntity.TryGetMember(GetMemberBinder binder, Object& result) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\DynamicEntity.cs:line 63
   at CallSite.Target(Closure , CallSite , Object )
   at ASP._Page_Portals_1_2sxc_BIGideas_Mosaic__Mosaic_cshtml.Execute() in c:\Users\Phil\documents\bigideas\web development\dotnetnuke\dnn-dev\Portals\1\2sxc\BIGideas_Mosaic\_Mosaic.cshtml:line 36
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy()
   at System.Web.WebPages.WebPageBase.ExecutePageHierarchy(WebPageContext pageContext, TextWriter writer, WebPageRenderingBase startPage)
   at ToSic.SexyContent.Engines.RazorEngine.RenderTemplate() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\2Sexy Content Razor\RazorEngine.cs:line 75
   at ToSic.SexyContent.Engines.EngineBase.Render() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Engines\EngineBase.cs:line 89
   at ToSic.SexyContent.SexyViewContentOrApp.ProcessView(PlaceHolder phOutput, Panel pnlError) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\SexyViewContentOrApp.cs:line 136

6. When I go to the data tab, I can see that my content type is configured properly. But when I go to click to view the actual data, I get another error:

Message:An error occurred while executing the request. Please consult the event log for details.
StackTrace:
InnerMessage:Object reference not set to an instance of an object.
InnerStackTrace:
   at DotNetNuke.Entities.Urls.AdvancedFriendlyUrlProvider.FriendlyUrlInternal(TabInfo tab, String path, String pageName, String portalAlias, PortalSettings portalSettings)
   at DotNetNuke.Entities.Urls.AdvancedFriendlyUrlProvider.FriendlyUrl(TabInfo tab, String path, String pageName, PortalSettings portalSettings)
   at DotNetNuke.Common.Globals.NavigateURL(Int32 tabID, Boolean isSuperTab, PortalSettings settings, String controlKey, String language, String pageName, String[] additionalParameters)
   at DotNetNuke.Common.Globals.NavigateURL(Int32 tabID, Boolean isSuperTab, PortalSettings settings, String controlKey, String language, String[] additionalParameters)
   at ToSic.SexyContent.EAV.Implementation.ValueConverter.SexyContentValueConverter.ResolvePageLink(Int32 id, String defaultValue) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\EAV\Implementation\ValueConverter\SexyContentValueConverter.cs:line 155
   at ToSic.SexyContent.EAV.Implementation.ValueConverter.SexyContentValueConverter.TryToResolveDnnCodeToLink(String value) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\EAV\Implementation\ValueConverter\SexyContentValueConverter.cs:line 97
   at ToSic.Eav.Data.Entity.GetBestValue(String attributeName, String[] dimensions, Boolean resolveHyperlinks) in C:\Projects\eav-server\ToSic.Eav.Core\Entity.cs:line 219
   at ToSic.Eav.Serializers.Serializer.<>c__DisplayClass27_0.b__2(IAttribute v) in C:\Projects\eav-server\ToSic.Eav.WebApi\Serializers\Serializer.cs:line 126
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at ToSic.Eav.Serializers.Serializer.GetDictionaryFromEntity(IEntity entity, String language) in C:\Projects\eav-server\ToSic.Eav.WebApi\Serializers\Serializer.cs:line 124
   at ToSic.SexyContent.Serializers.Serializer.GetDictionaryFromEntity(IEntity entity, String language) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Serializers\Serializer.cs:line 59
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ToSic.Eav.WebApi.EntitiesController.GetAllOfTypeForAdmin(Int32 appId, String contentType) in C:\Projects\eav-server\ToSic.Eav.WebApi\EntitiesController.cs:line 67
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext()
```
I am hopeful that it is a simple import error that is causing this chain of errors.

**Comment by iJungleboy** [comment]
I think the file doesn't exist on your pc, you probably deleted it manually. 

Could you check? it says 

```
InnerMessage:Could not find a part of the path 'C:\Users\Phil\Documents\BIGideas\Web Development\DotNetNuke\DNN-DEV\Portals\1\adam\BIGideas_Mosaic\6C46UJYifkiEufJVWATTLQ\Image\SampleImage.jpg'.
```

Also note: pls always put logs in the code-wrapper syntax (three back-apos) in github...

**Comment by iJungleboy** [comment]
Note: I'll also add a try/catch around the resolve-url, to prevent it from throwing an error if a page/etc. doesn't exist

**Comment by tpperlman** [comment]
In regards to your comment above, the "Could not find a part of the path" error related to where the file was supposed to be saved when imported into the portal. I exported it from /Portals/0 and tested the import into /Portals/1. So, maybe the import routine didn't create the subfolder. I can confirm that the file is in the ZIP archive:

![capture2](https://cloud.githubusercontent.com/assets/1871915/13779678/9d51defa-ea92-11e5-878e-cd7a14627275.JPG)

**Comment by tpperlman** [comment]
The above issue will probably always happen any time there is a demo content type with an image.

**Comment by tpperlman** [comment]
The other issue under "#4" in the original post appears to happen because the demo item had a link to a tab id in one of the fields. When it is exported and imported, the destination portal doesn't have that tab id, resulting in the error above related the friendly URLs.

The import routine should first check for the presence of the URL, and if it doesn't exist it should either note it doesn't exist in the UI or import the field as null. In an existing app, if the target tab id no longer exists the link goes to page:xxx instead of the friendly url.

**Comment by iJungleboy** [comment]
Just released 8.3.5, which checks the missing-page issue and doesn't break down. so check :)

The other error could have been related to this, pls just give it another try with the latest version.

**Comment by tpperlman** [comment]
I just re-exported the app and reimported it. Received the following error for each of the images that are a part of the ZIP:

```
Message:The underlying system threw an exception. The file has not been added.

StackTrace:

   at DotNetNuke.Services.FileSystem.FileManager.AddFile(IFolderInfo folder, String fileName, Stream fileContent, Boolean overwrite, Boolean checkPermissions, Boolean ignoreWhiteList, String contentType, Int32 createdByUserID)
   at DotNetNuke.Services.FileSystem.FileManager.AddFile(IFolderInfo folder, String fileName, Stream fileContent, Boolean overwrite)
   at ToSic.SexyContent.ImportExport.ZipImport.CopyAllFilesDnnPortal(String sourceFolder, String destinationFolder, Boolean overwriteFiles, List`1 messages) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ImportExport\ZipImport.cs:line 271

InnerMessage:Could not find a part of the path 'C:\Users\Phil\Documents\BIGideas\Web Development\DotNetNuke\DNN-DEV\Portals\1\adam\BIGideas_Mosaic\WthNg_luMkKa8UnwInV2NQ\Image\SampleImage.jpg'.

InnerStackTrace:

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   at DotNetNuke.Services.FileSystem.Internal.FileWrapper.Create(String path)
   at DotNetNuke.Services.FileSystem.StandardFolderProvider.UpdateFile(IFolderInfo folder, String fileName, Stream content)
   at DotNetNuke.Services.FileSystem.FileManager.AddFile(IFolderInfo folder, String fileName, Stream fileContent, Boolean overwrite, Boolean checkPermissions, Boolean ignoreWhiteList, String contentType, Int32 createdByUserID)
```
In reality, there is only one image needed in the export, but it also exports images from deleted data... which is another issue that I have logged.

**Comment by iJungleboy** [comment]
thanks. could you check if the file exists or not? the error says it's not there, but it's referring to a file in your portals/x/folder - so the target-system...

**Comment by tpperlman** [comment]
The log above is what occurs DURING the import, so for whatever reason the import doesn't appear to be creating the folder structure... I see the /adam folder under the portal root, but none of the subdirectories for each of the images.

**Comment by iJungleboy** [comment]
could it be a permission problem? that the adam-folder can't create sub-folders / items?

**Comment by tpperlman** [comment]
nope, since the app folder itself is being created... can you please try in 8.3.5 to export an app with an image and try to import it? I'd be happy to share my install with you if you want to test it on you machine.

**Comment by iJungleboy** [comment]
I tried export/import on 08.03.05 and it worked as expected. Could you upload your app to here (just add the zip) so I can try importing yours?

**Comment by tpperlman** [comment]
Where can I email you the ZIP instead? It contains a jquery app that I had to purchase and don’t think I should post it.

**Comment by iJungleboy** [comment]
ok. info 2sxc org

**Comment by iJungleboy** [comment]
I was able to install it without any problems

![image](https://cloud.githubusercontent.com/assets/5321186/13829996/615a6a96-ebca-11e5-8def-f89ac0568b5d.png)

**Comment by iJungleboy** [comment]
could you try it in another portal? just to make sure you don't have left-over files from some actions you had done previously or something...

**Comment by iJungleboy** [comment]
BTW: My guess is that your portal files are not in sync with the dnn-structure, so dnn thinks it has (or doesn't have) files already, which then turn out to exist / or not. This happens a lot on dev installations where users tend to add/delete files directly in the file system. Pls re-sync the folder structure in dnn file manager.

**Comment by tpperlman** [comment]
Thanks! Syncing the portal files fixed the import issue, but might I recommend that the import routine include a check to see if the directory and/or files exist, and if not then create and save them. I also uninstalled the app and re-imported it as a test. I see the notification that the ADAM images already exist, but shouldn't the ADAM folders be deleted when an app is uninstalled?

**Comment by iJungleboy** [comment]
As of now it checks if it exists (asking the dnn-api) and then performing the action. This is important, because the file-system could be non-Windows (like a cloud storage), so we have to rely on dnn to manage the files. 

I've updated the system to give a nicer error message in a future release. 

Deleting ADAM: I'll have to think it through, as it might have unexpected consequences, but then again maybe not. I'll sleep on it.
