### ISSUE TITLE
"Complete Upgrade" doesn't seem to complete the upgrade

### ISSUE THREAD

**Issue by jncraig** [2sic/2sxc#753]
I have tried 8.3.5 and 8.3.6.  Both install.  When App module is placed on a page, I get the invitation to "Complete Upgrade."  How may minutes is a few?  I waited in excess of 15 minutes and no message that the upgrade had completed.  Also, no indication of progress.  Should I see something?

**Comment by iJungleboy** [comment]
it should normally just take a few seconds. Pls check what's happening in fiddler - is the web-api call placed to the upgrade? does it give an answer? does the application restart?

it can take longer than a few seconds if you are upgradin gacross many versions, but I'm guessing that's not your scenario; so I'm guessing it some kind of url-bug. Pls check the fiddler stuff and tell me what happens.

**Comment by jncraig** [comment]
#	Result	Protocol	Host	URL	Body	Caching	Content-Type	Process	Comments	Custom	
17	500	HTTP	dnncon.patapscoresearch.com	/DesktopModules/2sxc/API/view/module/finishinstallation	36	no-cache; Expires: -1	application/json; charset=utf-8	chrome:12584			

The returned content:  {"Message":"An error has occurred."}

From the event log when the module was installed:

AbsoluteURL:/DesktopModules/2sxc/API/view/module/finishinstallation
DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke
ExceptionGUID:4cc62820-1045-40d2-b6e1-0e67c7e35d3b
AssemblyVersion:
PortalId:-1
UserId:-1
TabId:-1
RawUrl:
Referrer:
UserAgent:
ExceptionHash:oNpJ49lofJsirNMWPpHWpA==
Message:An error occurred while executing the request. Please consult the event log for details.
StackTrace:
InnerMessage:Cannot create a file when that file already exists.
InnerStackTrace:
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.__Error.WinIOError()
   at System.IO.File.InternalMove(String sourceFileName, String destFileName, Boolean checkHost)
   at ToSic.SexyContent.Installer.set_IsUpgradeRunning(Boolean value) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Installer.cs:line 266
   at ToSic.SexyContent.Installer.UpgradeModule(String version) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Installer.cs:line 141
   at ToSic.SexyContent.Installer.FinishAbortedUpgrade() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\Installer.cs:line 179
   at ToSic.SexyContent.ViewAPI.ModuleController.FinishInstallation() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\WebApi\ViewAPI\ModuleController.cs:line 316
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.Execute(Object instance, Object[] arguments)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext()
Source:
FileName:
FileLineNumber:0
FileColumnNumber:0
Method:
Server Name: GENERIC191

**Comment by iJungleboy** [comment]
Will look into this the next few days, don't have a quick answer. If you want it faster, check out the line-numbers mentioned in the error message and follow it up...

**Comment by jncraig** [comment]
This issue seems to have disappeared.  Before posting I had cleared
recycled the app pool several times and waited a couple of hours with no
solution.  Waiting overnight seems to have been what counted.

**Comment by iJungleboy** [comment]
Strange. I'll close this for now, but re-open it if someone else reports something like this.
