### ISSUE TITLE
Deleted a Content field, renamed another and it broke all 2sxc content modules

### ISSUE THREAD

**Issue by ech01** [2sic/2sxc#894]
Hello,

I removed a field and renamed another. Now all 2sxc content modules are throwing an error and it is not possible to get back to the admin (none of the settings, even module menu settings are present).

Message:Error getting List of Stream. Stream Name: Default DataSource Name: EntityTypeFilter
StackTrace:
InnerMessage:Error getting List of Stream. Stream Name: Default DataSource Name: EntityTypeFilter
InnerStackTrace:
   at ToSic.Eav.DataSources.DataStream.get_LightList() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 156
   at ToSic.Eav.DataSources.DataStream.get_List() in C:\Projects\eav-server\ToSic.Eav.DataSources\DataStream.cs:line 82
   at ToSic.SexyContent.ContentGroupManager.GetContentGroup(Guid contentGroupGuid) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentGroupManager.cs:line 42
   at ToSic.SexyContent.ContentGroupManager.GetContentGroupOrGeneratePreview(Guid groupGuid, Guid previewTemplateGuid) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentGroupManager.cs:line 142
   at ToSic.SexyContent.ContentGroupManager.GetContentGroupForModule(Int32 moduleId) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentGroupManager.cs:line 136
   at ToSic.SexyContent.ContentBlock.ModuleContentBlock..ctor(ModuleInfo moduleInfo, IEnumerable`1 overrideParams) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentBlock\ModuleContentBlock.cs:line 49
   at ToSic.SexyContent.View.get_UserMayEditThisModule() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 90
   at ToSic.SexyContent.View.Page_Load(Object sender, EventArgs e) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 30
   at DotNetNuke.Entities.Modules.PortalModuleBase.OnLoad(EventArgs e)
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Control.LoadRecursive()
   at System.Web.UI.Page.ProcessRequestMain(Boolean includeStagesBeforeAsyncPoint, Boolean includeStagesAfterAsyncPoint)

A few things I noted:
- The table named ToSic_EAV_ContextInfo has 6 records in it and all with the update stamp of when I was making the edits.
- There were internet connectivity issues when making the field changes. I may have lost service during the process intermittently.

**Comment by iJungleboy** [comment]
I believe what you did is the following - pls confirm:

1. you had an "original" content-type (not a field, a type, right?) - called "a", which you deleted
2. you had another content-type with another name, called "b", which you then renamed to "a"

Pls confirm or correct this. 

If this is the case - then I'm just guessing here, but there could be a bug in the entity-type filter which may still find just deleted types. In this case, I would recommend to find the deleted type in the DB and change its name to something strange like "deleted a - just a test" and then restart your dnn (to clear the cache) and try again.

**Comment by ech01** [comment]
1. Did not delete a content type, renamed 4 fields, removed one, untitled one field (clicked the star), added another to this content type. Exited the admin and saw the error.

2. Did not rename the content type, just the fields with in the content type

**Comment by ech01** [comment]
I was able to compare to an older backup and found what needed to be changed. 

//remove the delete
UPDATE ToSIC_EAV_Values
SET ChangeLogDeleted = NULL
WHERE ChangeLogDeleted = 3268
//reset the field names
UPDATE ToSIC_EAV_Attributes SET StaticName = 'Photo' WHERE AttributeID = 424
UPDATE ToSIC_EAV_Attributes SET StaticName = 'Video_Title' WHERE AttributeID = 433
UPDATE ToSIC_EAV_Attributes SET StaticName = 'Video_Image' WHERE AttributeID = 434
UPDATE ToSIC_EAV_Attributes SET StaticName = 'Video_Embed' WHERE AttributeID = 435
UPDATE ToSIC_EAV_Attributes SET StaticName = 'Border' WHERE AttributeID = 462

In the future, it would be great to have some better error handling or at least make it so that ALL content modules are not affected.   It was like searching for hay in a needlestack. 

Thanks for the pointers.

**Comment by iJungleboy** [comment]
Thanks - so was it that the content-types had the same name which cause the problem?

**Comment by ech01** [comment]
Sorry, on holiday, but that appears to be the case.

**Comment by iJungleboy** [comment]
Found that there was a special case where the content-types weren't checked for delete - should be fixed now...
