### ISSUE TITLE
Very Frequent "Content Encoding Error" Messages Across All Pages/Modules

### ISSUE THREAD

**Issue by tpperlman** [2sic/2sxc#901]
Keep getting constant "Content Encoding Error" messages on a fresh install of 2XSC v8.4.3 and above in DNN v8.0.3. I've tried upgrading to higher versions up to v8.4.8 with the same result.

Basically, nearly every time I try to click on any App or Content action button (e.g. edit, new, manage apps) this message appears in Firefox:

```
Content Encoding Error
The page you are trying to view cannot be shown because it uses an invalid or unsupported form of compression. Please contact the website owners to inform them of this problem.
```
Event viewer has this message:

```
Message:Object reference not set to an instance of an object.

StackTrace:

   at ToSic.SexyContent.View.InitModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 157
   at ToSic.SexyContent.View.get_ModuleActions() in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\View.ascx.cs:line 108
```
It does this constantly, and then will mysteriously start working again.

Then I'll occasionally get errors like this:

```
Had an error talking to the server (status 400).
Message: Bad Request
Detail: Resolution of the dependency failed, type = "ToSic.Eav.DataSources.Caches.ICache", name = "(none)".

Exception occurred while: Calling constructor ToSic.Eav.DataSources.SqlSources.EavSqlStore().

Exception is: Exception - Couldn't load Connection String with name "EavContext"

-----------------------------------------------

At the time of the exception, the container was:

  Resolving ToSic.Eav.DataSources.Caches.QuickCache,(none) (mapped from ToSic.Eav.DataSources.Caches.ICache, (none))

  Resolving value for property QuickCache.Backend

    Resolving ToSic.Eav.DataSources.SqlSources.EavSqlStore,(none) (mapped from ToSic.Eav.DataSources.RootSources.IRootSource, (none))

    Calling constructor ToSic.Eav.DataSources.SqlSources.EavSqlStore()
```
Then I'll click the "Try Again" button on the error screen and it will work fine again for a couple of minutes.

And at times when I try and add an app, a message like this will popup:

```
Had an error talking to the server (status 400).
Message: Bad Request
Detail: The given key was not present in the dictionary.
```
And Event Logs like these:

```
Message:The given key was not present in the dictionary.

StackTrace:

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ToSic.SexyContent.ContentBlock.ContentGroupReferenceManagerBase.SaveTemplateId(Int32 templateId, Boolean forceCreateContentGroup, Nullable`1 newTemplateChooserState) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentBlock\ContentGroupReferenceManagerBase.cs:line 54
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext()
```

```
Message:The given key was not present in the dictionary.

StackTrace:

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at ToSic.SexyContent.ContentBlock.ContentGroupReferenceManagerBase.SaveTemplateId(Int32 templateId, Boolean forceCreateContentGroup, Nullable`1 newTemplateChooserState) in C:\Projects\2SexyContent\Web\DesktopModules\ToSIC_SexyContent\SexyContent\ContentBlock\ContentGroupReferenceManagerBase.cs:line 54
   at lambda_method(Closure , Object , Object[] )
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ActionExecutor.<>c__DisplayClass10.b__9(Object instance, Object[] methodParameters)
   at System.Web.Http.Controllers.ReflectedHttpActionDescriptor.ExecuteAsync(HttpControllerContext controllerContext, IDictionary`2 arguments, CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Tracing.ITraceWriterExtensions.d__18`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Filters.AuthorizationFilterAttribute.d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ExceptionFilterResult.d__0.MoveNext()
```

It just seems to me that this entire project is unstable, no matter how many times I reinstall and start to build fresh apps in a new install of DNN.

**Comment by tpperlman** [comment]
Determined cause to be bad cache in Firefox.
